/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import net.nova.api.models.components.DistributionInput;
import net.nova.api.utils.SpeakeasyMetadata;
import net.nova.api.utils.Utils;


public class CreateDistributionsRequest {
    /**
     * ID of the organization the request acts on
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Organization-Id")
    private String xOrganizationId;

    /**
     * Unique key for idempotent requests. If you retry a request with the same key, the API returns the
     * original response without performing the operation again.
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=Idempotency-Key")
    private String idempotencyKey;


    @SpeakeasyMetadata("request:mediaType=application/json")
    private List<DistributionInput> body;

    @JsonCreator
    public CreateDistributionsRequest(
            @Nonnull String xOrganizationId,
            @Nullable String idempotencyKey,
            @Nonnull List<DistributionInput> body) {
        this.xOrganizationId = Optional.ofNullable(xOrganizationId)
            .orElseThrow(() -> new IllegalArgumentException("xOrganizationId cannot be null"));
        this.idempotencyKey = idempotencyKey;
        this.body = Optional.ofNullable(body)
            .orElseThrow(() -> new IllegalArgumentException("body cannot be null"));
    }
    
    public CreateDistributionsRequest(
            @Nonnull String xOrganizationId,
            @Nonnull List<DistributionInput> body) {
        this(xOrganizationId, null, body);
    }

    /**
     * ID of the organization the request acts on
     */
    public String xOrganizationId() {
        return this.xOrganizationId;
    }

    /**
     * Unique key for idempotent requests. If you retry a request with the same key, the API returns the
     * original response without performing the operation again.
     */
    public Optional<String> idempotencyKey() {
        return Optional.ofNullable(this.idempotencyKey);
    }

    public List<DistributionInput> body() {
        return this.body;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * ID of the organization the request acts on
     */
    public CreateDistributionsRequest withXOrganizationId(@Nonnull String xOrganizationId) {
        this.xOrganizationId = Utils.checkNotNull(xOrganizationId, "xOrganizationId");
        return this;
    }


    /**
     * Unique key for idempotent requests. If you retry a request with the same key, the API returns the
     * original response without performing the operation again.
     */
    public CreateDistributionsRequest withIdempotencyKey(@Nullable String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
        return this;
    }


    public CreateDistributionsRequest withBody(@Nonnull List<DistributionInput> body) {
        this.body = Utils.checkNotNull(body, "body");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateDistributionsRequest other = (CreateDistributionsRequest) o;
        return 
            Utils.enhancedDeepEquals(this.xOrganizationId, other.xOrganizationId) &&
            Utils.enhancedDeepEquals(this.idempotencyKey, other.idempotencyKey) &&
            Utils.enhancedDeepEquals(this.body, other.body);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            xOrganizationId, idempotencyKey, body);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateDistributionsRequest.class,
                "xOrganizationId", xOrganizationId,
                "idempotencyKey", idempotencyKey,
                "body", body);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String xOrganizationId;

        private String idempotencyKey;

        private List<DistributionInput> body;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * ID of the organization the request acts on
         */
        public Builder xOrganizationId(@Nonnull String xOrganizationId) {
            this.xOrganizationId = Utils.checkNotNull(xOrganizationId, "xOrganizationId");
            return this;
        }

        /**
         * Unique key for idempotent requests. If you retry a request with the same key, the API returns the
         * original response without performing the operation again.
         */
        public Builder idempotencyKey(@Nullable String idempotencyKey) {
            this.idempotencyKey = idempotencyKey;
            return this;
        }

        public Builder body(@Nonnull List<DistributionInput> body) {
            this.body = Utils.checkNotNull(body, "body");
            return this;
        }

        public CreateDistributionsRequest build() {
            return new CreateDistributionsRequest(
                xOrganizationId, idempotencyKey, body);
        }

    }
}
