/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.operations;

import static net.nova.api.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.List;
import net.nova.api.SDKConfiguration;
import net.nova.api.models.components.EntityPaymentInstructionsInput;
import net.nova.api.operations.CreatePaymentInstructions;
import net.nova.api.utils.Headers;
import net.nova.api.utils.Utils;

public class CreatePaymentInstructionsRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final CreatePaymentInstructionsRequest.Builder pojoBuilder;
    private CreatePaymentInstructionsRequest request;
    private boolean _setterCalled;

    public CreatePaymentInstructionsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = CreatePaymentInstructionsRequest.builder();
    }

    public CreatePaymentInstructionsRequestBuilder xOrganizationId(@Nonnull String xOrganizationId) {
        this.pojoBuilder.xOrganizationId(xOrganizationId);
        this._setterCalled = true;
        return this;
    }

    public CreatePaymentInstructionsRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public CreatePaymentInstructionsRequestBuilder body(@Nonnull List<EntityPaymentInstructionsInput> body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    private CreatePaymentInstructionsRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public CreatePaymentInstructionsRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CreatePaymentInstructionsResponse call() {
        RequestOperation<CreatePaymentInstructionsRequest, CreatePaymentInstructionsResponse> operation
              = new CreatePaymentInstructions.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
