/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.operations;

import static net.nova.api.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import java.lang.String;
import net.nova.api.SDKConfiguration;
import net.nova.api.operations.GetDistribution;
import net.nova.api.utils.Headers;
import net.nova.api.utils.Utils;

public class GetDistributionRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final GetDistributionRequest.Builder pojoBuilder;
    private GetDistributionRequest request;
    private boolean _setterCalled;

    public GetDistributionRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = GetDistributionRequest.builder();
    }

    public GetDistributionRequestBuilder id(@Nonnull String id) {
        this.pojoBuilder.id(id);
        this._setterCalled = true;
        return this;
    }

    public GetDistributionRequestBuilder xOrganizationId(@Nonnull String xOrganizationId) {
        this.pojoBuilder.xOrganizationId(xOrganizationId);
        this._setterCalled = true;
        return this;
    }

    private GetDistributionRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public GetDistributionRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public GetDistributionResponse call() {
        RequestOperation<GetDistributionRequest, GetDistributionResponse> operation
              = new GetDistribution.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
