/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import net.nova.api.utils.SpeakeasyMetadata;
import net.nova.api.utils.Utils;


public class GetEntityRequest {
    /**
     * ID of the entity
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    private String id;

    /**
     * ID of the organization the request acts on
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Organization-Id")
    private String xOrganizationId;

    @JsonCreator
    public GetEntityRequest(
            @Nonnull String id,
            @Nonnull String xOrganizationId) {
        this.id = Optional.ofNullable(id)
            .orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
        this.xOrganizationId = Optional.ofNullable(xOrganizationId)
            .orElseThrow(() -> new IllegalArgumentException("xOrganizationId cannot be null"));
    }

    /**
     * ID of the entity
     */
    public String id() {
        return this.id;
    }

    /**
     * ID of the organization the request acts on
     */
    public String xOrganizationId() {
        return this.xOrganizationId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * ID of the entity
     */
    public GetEntityRequest withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }


    /**
     * ID of the organization the request acts on
     */
    public GetEntityRequest withXOrganizationId(@Nonnull String xOrganizationId) {
        this.xOrganizationId = Utils.checkNotNull(xOrganizationId, "xOrganizationId");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetEntityRequest other = (GetEntityRequest) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.xOrganizationId, other.xOrganizationId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, xOrganizationId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetEntityRequest.class,
                "id", id,
                "xOrganizationId", xOrganizationId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private String xOrganizationId;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * ID of the entity
         */
        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        /**
         * ID of the organization the request acts on
         */
        public Builder xOrganizationId(@Nonnull String xOrganizationId) {
            this.xOrganizationId = Utils.checkNotNull(xOrganizationId, "xOrganizationId");
            return this;
        }

        public GetEntityRequest build() {
            return new GetEntityRequest(
                id, xOrganizationId);
        }

    }
}
