/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.errors;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Deprecated;
import java.lang.Exception;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.lang.Throwable;
import java.net.http.HttpResponse;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import net.nova.api.models.components.ApiErrorType;
import net.nova.api.models.components.ErrorObject;
import net.nova.api.utils.Blob;
import net.nova.api.utils.Utils;

@SuppressWarnings("serial")
public class Error extends NovaSDKException {

    @Nullable
    private final Data data;

    @Nullable
    private final Throwable deserializationException;

    public Error(
                int code,
                byte[] body,
                HttpResponse<?> rawResponse,
                @Nullable Data data,
                @Nullable Throwable deserializationException) {
        super("API error occurred", code, body, rawResponse, null);
        this.data = data;
        this.deserializationException = deserializationException;
    }

    /**
    * Parse a response into an instance of Error. If deserialization of the response body fails,
    * the resulting Error instance will have a null data() value and a non-null deserializationException().
    */
    public static Error from(HttpResponse<InputStream> response) {
        try {
            byte[] bytes = Utils.extractByteArrayFromBody(response);
            Data data = Utils.mapper().readValue(bytes, Data.class);
            return new Error(response.statusCode(), bytes, response, data, null);
        } catch (Exception e) {
            return new Error(response.statusCode(), null, response, null, e);
        }
    }

    /**
    * Parse a response into an instance of Error asynchronously. If deserialization of the response body fails,
    * the resulting Error instance will have a null data() value and a non-null deserializationException().
    */
    public static CompletableFuture<Error> fromAsync(HttpResponse<Blob> response) {
        return response.body()
                .toByteArray()
                .handle((bytes, err) -> {
                    // if a body read error occurs, we want to transform the exception
                    if (err != null) {
                        throw new AsyncAPIException(
                                "Error reading response body: " + err.getMessage(),
                                response.statusCode(),
                                null,
                                response,
                                err);
                    }

                    try {
                        return new Error(
                                response.statusCode(),
                                bytes,
                                response,
                                Utils.mapper().readValue(
                                        bytes,
                                        new TypeReference<Data>() {
                                        }),
                                null);
                    } catch (Exception e) {
                        return new Error(
                                response.statusCode(),
                                bytes,
                                response,
                                null,
                                e);
                    }
                });
    }

    /**
     * Object type identifier.
     */
    @Deprecated
    public Optional<ErrorObject> object() {
        return data().map(Data::object);
    }

    /**
     * High-level error category.
     */
    @Deprecated
    public Optional<ApiErrorType> type() {
        return data().map(Data::type);
    }

    /**
     * HTTP status code.
     */
    @Deprecated
    public Optional<Long> status() {
        return data().map(Data::status);
    }

    /**
     * The request parameter that caused the error, if applicable.
     */
    @Deprecated
    public Optional<String> param() {
        return data().flatMap(Data::param);
    }

    /**
     * Link to documentation about this error.
     */
    @Deprecated
    public Optional<String> docUrl() {
        return data().flatMap(Data::docUrl);
    }

    /**
     * Request identifier for support inquiries.
     */
    @Deprecated
    public Optional<String> requestId() {
        return data().flatMap(Data::requestId);
    }

    public Optional<Data> data() {
        return Optional.ofNullable(data);
    }

    /**
     * Returns the exception if an error occurs while deserializing the response body.
     */
    public Optional<Throwable> deserializationException() {
        return Optional.ofNullable(deserializationException);
    }

    public static class Data {
        /**
         * Object type identifier.
         */
        @JsonProperty("object")
        private ErrorObject object;

        /**
         * High-level error category.
         */
        @JsonProperty("type")
        private ApiErrorType type;

        /**
         * Machine-readable error code. Stable across releases for a given failure mode.
         */
        @JsonProperty("code")
        private String code;

        /**
         * Human-readable error message intended for developers, not end-users.
         */
        @JsonProperty("message")
        private String message;

        /**
         * HTTP status code.
         */
        @JsonProperty("status")
        private long status;

        /**
         * The request parameter that caused the error, if applicable.
         */
        @JsonInclude(Include.NON_ABSENT)
        @JsonProperty("param")
        private String param;

        /**
         * Link to documentation about this error.
         */
        @JsonInclude(Include.NON_ABSENT)
        @JsonProperty("doc_url")
        private String docUrl;

        /**
         * Request identifier for support inquiries.
         */
        @JsonInclude(Include.NON_ABSENT)
        @JsonProperty("request_id")
        private String requestId;

        @JsonCreator
        public Data(
                @JsonProperty("object") @Nonnull ErrorObject object,
                @JsonProperty("type") @Nonnull ApiErrorType type,
                @JsonProperty("code") @Nonnull String code,
                @JsonProperty("message") @Nonnull String message,
                @JsonProperty("status") long status,
                @JsonProperty("param") @Nullable String param,
                @JsonProperty("doc_url") @Nullable String docUrl,
                @JsonProperty("request_id") @Nullable String requestId) {
            this.object = Optional.ofNullable(object)
                .orElseThrow(() -> new IllegalArgumentException("object cannot be null"));
            this.type = Optional.ofNullable(type)
                .orElseThrow(() -> new IllegalArgumentException("type cannot be null"));
            this.code = Optional.ofNullable(code)
                .orElseThrow(() -> new IllegalArgumentException("code cannot be null"));
            this.message = Optional.ofNullable(message)
                .orElseThrow(() -> new IllegalArgumentException("message cannot be null"));
            this.status = status;
            this.param = param;
            this.docUrl = docUrl;
            this.requestId = requestId;
        }
        
        public Data(
                @Nonnull ErrorObject object,
                @Nonnull ApiErrorType type,
                @Nonnull String code,
                @Nonnull String message,
                long status) {
            this(object, type, code,
                message, status, null,
                null, null);
        }

        /**
         * Object type identifier.
         */
        public ErrorObject object() {
            return this.object;
        }

        /**
         * High-level error category.
         */
        public ApiErrorType type() {
            return this.type;
        }

        /**
         * Machine-readable error code. Stable across releases for a given failure mode.
         */
        public String code() {
            return this.code;
        }

        /**
         * Human-readable error message intended for developers, not end-users.
         */
        public String message() {
            return this.message;
        }

        /**
         * HTTP status code.
         */
        public long status() {
            return this.status;
        }

        /**
         * The request parameter that caused the error, if applicable.
         */
        public Optional<String> param() {
            return Optional.ofNullable(this.param);
        }

        /**
         * Link to documentation about this error.
         */
        public Optional<String> docUrl() {
            return Optional.ofNullable(this.docUrl);
        }

        /**
         * Request identifier for support inquiries.
         */
        public Optional<String> requestId() {
            return Optional.ofNullable(this.requestId);
        }

        public static Builder builder() {
            return new Builder();
        }


        /**
         * Object type identifier.
         */
        public Data withObject(@Nonnull ErrorObject object) {
            this.object = Utils.checkNotNull(object, "object");
            return this;
        }


        /**
         * High-level error category.
         */
        public Data withType(@Nonnull ApiErrorType type) {
            this.type = Utils.checkNotNull(type, "type");
            return this;
        }


        /**
         * Machine-readable error code. Stable across releases for a given failure mode.
         */
        public Data withCode(@Nonnull String code) {
            this.code = Utils.checkNotNull(code, "code");
            return this;
        }


        /**
         * Human-readable error message intended for developers, not end-users.
         */
        public Data withMessage(@Nonnull String message) {
            this.message = Utils.checkNotNull(message, "message");
            return this;
        }


        /**
         * HTTP status code.
         */
        public Data withStatus(long status) {
            this.status = status;
            return this;
        }


        /**
         * The request parameter that caused the error, if applicable.
         */
        public Data withParam(@Nullable String param) {
            this.param = param;
            return this;
        }


        /**
         * Link to documentation about this error.
         */
        public Data withDocUrl(@Nullable String docUrl) {
            this.docUrl = docUrl;
            return this;
        }


        /**
         * Request identifier for support inquiries.
         */
        public Data withRequestId(@Nullable String requestId) {
            this.requestId = requestId;
            return this;
        }


        @Override
        public boolean equals(java.lang.Object o) {
            if (this == o) {
                return true;
            }
            if (o == null || getClass() != o.getClass()) {
                return false;
            }
            Data other = (Data) o;
            return 
                Utils.enhancedDeepEquals(this.object, other.object) &&
                Utils.enhancedDeepEquals(this.type, other.type) &&
                Utils.enhancedDeepEquals(this.code, other.code) &&
                Utils.enhancedDeepEquals(this.message, other.message) &&
                Utils.enhancedDeepEquals(this.status, other.status) &&
                Utils.enhancedDeepEquals(this.param, other.param) &&
                Utils.enhancedDeepEquals(this.docUrl, other.docUrl) &&
                Utils.enhancedDeepEquals(this.requestId, other.requestId);
        }
        
        @Override
        public int hashCode() {
            return Utils.enhancedHash(
                object, type, code,
                message, status, param,
                docUrl, requestId);
        }
        
        @Override
        public String toString() {
            return Utils.toString(Data.class,
                    "object", object,
                    "type", type,
                    "code", code,
                    "message", message,
                    "status", status,
                    "param", param,
                    "docUrl", docUrl,
                    "requestId", requestId);
        }

        @SuppressWarnings("UnusedReturnValue")
        public final static class Builder {

            private ErrorObject object;

            private ApiErrorType type;

            private String code;

            private String message;

            private long status;

            private String param;

            private String docUrl;

            private String requestId;

            private Builder() {
              // force use of static builder() method
            }

            /**
             * Object type identifier.
             */
            public Builder object(@Nonnull ErrorObject object) {
                this.object = Utils.checkNotNull(object, "object");
                return this;
            }

            /**
             * High-level error category.
             */
            public Builder type(@Nonnull ApiErrorType type) {
                this.type = Utils.checkNotNull(type, "type");
                return this;
            }

            /**
             * Machine-readable error code. Stable across releases for a given failure mode.
             */
            public Builder code(@Nonnull String code) {
                this.code = Utils.checkNotNull(code, "code");
                return this;
            }

            /**
             * Human-readable error message intended for developers, not end-users.
             */
            public Builder message(@Nonnull String message) {
                this.message = Utils.checkNotNull(message, "message");
                return this;
            }

            /**
             * HTTP status code.
             */
            public Builder status(long status) {
                this.status = status;
                return this;
            }

            /**
             * The request parameter that caused the error, if applicable.
             */
            public Builder param(@Nullable String param) {
                this.param = param;
                return this;
            }

            /**
             * Link to documentation about this error.
             */
            public Builder docUrl(@Nullable String docUrl) {
                this.docUrl = docUrl;
                return this;
            }

            /**
             * Request identifier for support inquiries.
             */
            public Builder requestId(@Nullable String requestId) {
                this.requestId = requestId;
                return this;
            }

            public Data build() {
                return new Data(
                    object, type, code,
                    message, status, param,
                    docUrl, requestId);
            }

        }
    }

}

