/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.errors;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Deprecated;
import java.lang.Exception;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.lang.Throwable;
import java.net.http.HttpResponse;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import net.nova.api.models.components.Error;
import net.nova.api.utils.Blob;
import net.nova.api.utils.Utils;

@SuppressWarnings("serial")
public class OAuthError extends NovaSDKException {

    @Nullable
    private final Data data;

    @Nullable
    private final Throwable deserializationException;

    public OAuthError(
                int code,
                byte[] body,
                HttpResponse<?> rawResponse,
                @Nullable Data data,
                @Nullable Throwable deserializationException) {
        super("API error occurred", code, body, rawResponse, null);
        this.data = data;
        this.deserializationException = deserializationException;
    }

    /**
    * Parse a response into an instance of OAuthError. If deserialization of the response body fails,
    * the resulting OAuthError instance will have a null data() value and a non-null deserializationException().
    */
    public static OAuthError from(HttpResponse<InputStream> response) {
        try {
            byte[] bytes = Utils.extractByteArrayFromBody(response);
            Data data = Utils.mapper().readValue(bytes, Data.class);
            return new OAuthError(response.statusCode(), bytes, response, data, null);
        } catch (Exception e) {
            return new OAuthError(response.statusCode(), null, response, null, e);
        }
    }

    /**
    * Parse a response into an instance of OAuthError asynchronously. If deserialization of the response body fails,
    * the resulting OAuthError instance will have a null data() value and a non-null deserializationException().
    */
    public static CompletableFuture<OAuthError> fromAsync(HttpResponse<Blob> response) {
        return response.body()
                .toByteArray()
                .handle((bytes, err) -> {
                    // if a body read error occurs, we want to transform the exception
                    if (err != null) {
                        throw new AsyncAPIException(
                                "Error reading response body: " + err.getMessage(),
                                response.statusCode(),
                                null,
                                response,
                                err);
                    }

                    try {
                        return new OAuthError(
                                response.statusCode(),
                                bytes,
                                response,
                                Utils.mapper().readValue(
                                        bytes,
                                        new TypeReference<Data>() {
                                        }),
                                null);
                    } catch (Exception e) {
                        return new OAuthError(
                                response.statusCode(),
                                bytes,
                                response,
                                null,
                                e);
                    }
                });
    }

    /**
     * Machine-readable OAuth error code (RFC 6749 §5.2).
     */
    @Deprecated
    public Optional<Error> error() {
        return data().map(Data::error);
    }

    /**
     * Human-readable explanation of the error.
     */
    @Deprecated
    public Optional<String> errorDescription() {
        return data().flatMap(Data::errorDescription);
    }

    public Optional<Data> data() {
        return Optional.ofNullable(data);
    }

    /**
     * Returns the exception if an error occurs while deserializing the response body.
     */
    public Optional<Throwable> deserializationException() {
        return Optional.ofNullable(deserializationException);
    }

    public static class Data {
        /**
         * Machine-readable OAuth error code (RFC 6749 §5.2).
         */
        @JsonProperty("error")
        private Error error;

        /**
         * Human-readable explanation of the error.
         */
        @JsonInclude(Include.NON_ABSENT)
        @JsonProperty("error_description")
        private String errorDescription;

        @JsonCreator
        public Data(
                @JsonProperty("error") @Nonnull Error error,
                @JsonProperty("error_description") @Nullable String errorDescription) {
            this.error = Optional.ofNullable(error)
                .orElseThrow(() -> new IllegalArgumentException("error cannot be null"));
            this.errorDescription = errorDescription;
        }
        
        public Data(
                @Nonnull Error error) {
            this(error, null);
        }

        /**
         * Machine-readable OAuth error code (RFC 6749 §5.2).
         */
        public Error error() {
            return this.error;
        }

        /**
         * Human-readable explanation of the error.
         */
        public Optional<String> errorDescription() {
            return Optional.ofNullable(this.errorDescription);
        }

        public static Builder builder() {
            return new Builder();
        }


        /**
         * Machine-readable OAuth error code (RFC 6749 §5.2).
         */
        public Data withError(@Nonnull Error error) {
            this.error = Utils.checkNotNull(error, "error");
            return this;
        }


        /**
         * Human-readable explanation of the error.
         */
        public Data withErrorDescription(@Nullable String errorDescription) {
            this.errorDescription = errorDescription;
            return this;
        }


        @Override
        public boolean equals(java.lang.Object o) {
            if (this == o) {
                return true;
            }
            if (o == null || getClass() != o.getClass()) {
                return false;
            }
            Data other = (Data) o;
            return 
                Utils.enhancedDeepEquals(this.error, other.error) &&
                Utils.enhancedDeepEquals(this.errorDescription, other.errorDescription);
        }
        
        @Override
        public int hashCode() {
            return Utils.enhancedHash(
                error, errorDescription);
        }
        
        @Override
        public String toString() {
            return Utils.toString(Data.class,
                    "error", error,
                    "errorDescription", errorDescription);
        }

        @SuppressWarnings("UnusedReturnValue")
        public final static class Builder {

            private Error error;

            private String errorDescription;

            private Builder() {
              // force use of static builder() method
            }

            /**
             * Machine-readable OAuth error code (RFC 6749 §5.2).
             */
            public Builder error(@Nonnull Error error) {
                this.error = Utils.checkNotNull(error, "error");
                return this;
            }

            /**
             * Human-readable explanation of the error.
             */
            public Builder errorDescription(@Nullable String errorDescription) {
                this.errorDescription = errorDescription;
                return this;
            }

            public Data build() {
                return new Data(
                    error, errorDescription);
            }

        }
    }

}

