/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.hooks;

public final class OAuth2Scopes {

    private OAuth2Scopes() {
        // prevent instantiation
    }

    /**
     * Available scopes for the OAuth2 OAuth 2.0 scheme (clientCredentials flow).
     * 
     * <p>OAuth2 client_credentials grant for server-to-server access. Onboard via your Nova admin to receive
     * a `client_id` and `client_secret`, then `POST /oauth/token` to exchange them for a short-lived
     * access token. Send the token as `Authorization: Bearer &lt;access_token&gt;` on every authenticated
     * request.
     * 
     * <p>Tokens expire after 3600 seconds — refresh by re-exchanging credentials.
     * 
     * <p>Production and sandbox share the same host (`api.nova.net`); the mode is determined by the
     * credential prefix — `sk_prod_*` issues live-mode tokens, `sk_test_*` issues test-mode tokens.
     * Test-mode tokens never affect production data.
     */
    public static enum OAuth2 {

        /**
         * Read organization data
         */
        OrganizationsRead("organizations:read"),

        /**
         * Create or update organization data
         */
        OrganizationsWrite("organizations:write"),

        /**
         * Full access to organization data
         */
        OrganizationsWildcard("organizations:*"),

        /**
         * Read distribution data
         */
        DistributionsRead("distributions:read"),

        /**
         * Create or update distributions
         */
        DistributionsWrite("distributions:write"),

        /**
         * Full access to distributions
         */
        DistributionsWildcard("distributions:*"),

        /**
         * Read vehicle data
         */
        VehiclesRead("vehicles:read"),

        /**
         * Create or update vehicles
         */
        VehiclesWrite("vehicles:write"),

        /**
         * Full access to vehicles
         */
        VehiclesWildcard("vehicles:*"),

        /**
         * Read entity data
         */
        EntitiesRead("entities:read"),

        /**
         * Create or update entities
         */
        EntitiesWrite("entities:write"),

        /**
         * Full access to entities
         */
        EntitiesWildcard("entities:*"),

        /**
         * Read contact data
         */
        ContactsRead("contacts:read"),

        /**
         * Create or update contacts
         */
        ContactsWrite("contacts:write"),

        /**
         * Full access to contacts
         */
        ContactsWildcard("contacts:*");

        private final java.lang.String value;

        OAuth2(java.lang.String value) {
            this.value = value;
        }

        public java.lang.String value() {
            return value;
        }

        public static java.util.Optional<OAuth2> fromValue(java.lang.String value) {
            for (OAuth2 o: OAuth2.values()) {
                if (java.util.Objects.deepEquals(o.value, value)) {
                    return java.util.Optional.of(o);
                }
            }
            return java.util.Optional.empty();
        }
    }
}
