/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.operations.async;

import static net.nova.api.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import net.nova.api.SDKConfiguration;
import net.nova.api.models.components.ContactCreateInput;
import net.nova.api.models.operations.CreateContactsRequest;
import net.nova.api.operations.CreateContacts;
import net.nova.api.utils.Headers;
import net.nova.api.utils.Utils;

public class CreateContactsRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final CreateContactsRequest.Builder pojoBuilder;
    private CreateContactsRequest request;
    private boolean _setterCalled;

    public CreateContactsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = CreateContactsRequest.builder();
    }

    public CreateContactsRequestBuilder xOrganizationId(@Nonnull String xOrganizationId) {
        this.pojoBuilder.xOrganizationId(xOrganizationId);
        this._setterCalled = true;
        return this;
    }

    public CreateContactsRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public CreateContactsRequestBuilder body(@Nonnull List<ContactCreateInput> body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    private CreateContactsRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public CreateContactsRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<CreateContactsResponse> call() {
        AsyncRequestOperation<CreateContactsRequest, CreateContactsResponse> operation
              = new CreateContacts.Async(sdkConfiguration, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
