/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.operations.async;

import static net.nova.api.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import java.util.concurrent.CompletableFuture;
import net.nova.api.SDKConfiguration;
import net.nova.api.models.components.OAuthTokenRequest;
import net.nova.api.operations.CreateOAuthToken;
import net.nova.api.utils.Headers;
import net.nova.api.utils.Utils;

public class CreateOAuthTokenRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private OAuthTokenRequest request;

    public CreateOAuthTokenRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public CreateOAuthTokenRequestBuilder request(@Nonnull OAuthTokenRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private OAuthTokenRequest _buildRequest() {
        return this.request;
    }
    
    public CreateOAuthTokenRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<CreateOAuthTokenResponse> call() {
        AsyncRequestOperation<OAuthTokenRequest, CreateOAuthTokenResponse> operation
              = new CreateOAuthToken.Async(sdkConfiguration, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
