/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.operations.async;

import static net.nova.api.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import net.nova.api.SDKConfiguration;
import net.nova.api.models.components.DistributionInput;
import net.nova.api.models.operations.CreateDistributionsRequest;
import net.nova.api.operations.CreateDistributions;
import net.nova.api.utils.Headers;
import net.nova.api.utils.Utils;

public class CreateDistributionsRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final CreateDistributionsRequest.Builder pojoBuilder;
    private CreateDistributionsRequest request;
    private boolean _setterCalled;

    public CreateDistributionsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = CreateDistributionsRequest.builder();
    }

    public CreateDistributionsRequestBuilder xOrganizationId(@Nonnull String xOrganizationId) {
        this.pojoBuilder.xOrganizationId(xOrganizationId);
        this._setterCalled = true;
        return this;
    }

    public CreateDistributionsRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public CreateDistributionsRequestBuilder body(@Nonnull List<DistributionInput> body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    private CreateDistributionsRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public CreateDistributionsRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<CreateDistributionsResponse> call() {
        AsyncRequestOperation<CreateDistributionsRequest, CreateDistributionsResponse> operation
              = new CreateDistributions.Async(sdkConfiguration, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
