/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.operations.async;

import static net.nova.api.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import net.nova.api.SDKConfiguration;
import net.nova.api.models.operations.GetEntityRequest;
import net.nova.api.operations.GetEntity;
import net.nova.api.utils.Headers;
import net.nova.api.utils.Utils;

public class GetEntityRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final GetEntityRequest.Builder pojoBuilder;
    private GetEntityRequest request;
    private boolean _setterCalled;

    public GetEntityRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = GetEntityRequest.builder();
    }

    public GetEntityRequestBuilder id(@Nonnull String id) {
        this.pojoBuilder.id(id);
        this._setterCalled = true;
        return this;
    }

    public GetEntityRequestBuilder xOrganizationId(@Nonnull String xOrganizationId) {
        this.pojoBuilder.xOrganizationId(xOrganizationId);
        this._setterCalled = true;
        return this;
    }

    private GetEntityRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public GetEntityRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<GetEntityResponse> call() {
        AsyncRequestOperation<GetEntityRequest, GetEntityResponse> operation
              = new GetEntity.Async(sdkConfiguration, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
