/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api;

import net.nova.api.utils.Headers;

/**
 * Nova API: The Nova API exposes programmatic access to fund operations including distributions,
 * vehicles, entities, and contacts. Authentication is via OAuth2 client_credentials with per-scope
 * authorization. Live and test mode share the same host (`api.nova.net`); the mode is discriminated by
 * the credential prefix (`sk_prod_*` vs `sk_test_*`).
 * 
 * <p>All write operations require an `X-Organization-Id` header identifying the acting organization.
 */
public class AsyncNovaSDK {
    private static final Headers _headers = Headers.EMPTY;
    /**
     * OAuth2 client_credentials token exchange
     */
    private final AsyncAuthentication authentication;
    /**
     * Manage distributions
     */
    private final AsyncDistributions distributions;
    /**
     * Manage payment instructions for entities
     */
    private final AsyncPaymentInstructions paymentInstructions;
    /**
     * Manage entities
     */
    private final AsyncEntities entities;
    /**
     * Manage contacts
     */
    private final AsyncContacts contacts;
    /**
     * OAuth2 client_credentials token exchange
     */
    public AsyncAuthentication authentication() {
        return authentication;
    }
    /**
     * Manage distributions
     */
    public AsyncDistributions distributions() {
        return distributions;
    }
    /**
     * Manage payment instructions for entities
     */
    public AsyncPaymentInstructions paymentInstructions() {
        return paymentInstructions;
    }
    /**
     * Manage entities
     */
    public AsyncEntities entities() {
        return entities;
    }
    /**
     * Manage contacts
     */
    public AsyncContacts contacts() {
        return contacts;
    }

    private final SDKConfiguration sdkConfiguration;
    private final NovaSDK syncSDK;

    AsyncNovaSDK(NovaSDK syncSDK, SDKConfiguration sdkConfiguration) {
        this.syncSDK = syncSDK;
        this.sdkConfiguration = sdkConfiguration;
        this.authentication = new AsyncAuthentication(syncSDK.authentication(), sdkConfiguration);
        this.distributions = new AsyncDistributions(syncSDK.distributions(), sdkConfiguration);
        this.paymentInstructions = new AsyncPaymentInstructions(syncSDK.paymentInstructions(), sdkConfiguration);
        this.entities = new AsyncEntities(syncSDK.entities(), sdkConfiguration);
        this.contacts = new AsyncContacts(syncSDK.contacts(), sdkConfiguration);
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public NovaSDK toSync() {
        return syncSDK;
    }
}
