/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api;

import static net.nova.api.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import net.nova.api.models.components.ContactCreateInput;
import net.nova.api.models.operations.CreateContactsRequest;
import net.nova.api.models.operations.GetContactRequest;
import net.nova.api.models.operations.async.CreateContactsRequestBuilder;
import net.nova.api.models.operations.async.CreateContactsResponse;
import net.nova.api.models.operations.async.GetContactRequestBuilder;
import net.nova.api.models.operations.async.GetContactResponse;
import net.nova.api.operations.CreateContacts;
import net.nova.api.operations.GetContact;
import net.nova.api.utils.Headers;

/**
 * Manage contacts
 */
public class AsyncContacts {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Contacts syncSDK;

    AsyncContacts(Contacts syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Contacts toSync() {
        return syncSDK;
    }


    /**
     * Create contacts
     * 
     * <p>Create one or more contacts associated with the organization in a single request. The batch is
     * atomic — if any contact fails validation, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @return The async call builder
     */
    public CreateContactsRequestBuilder createContacts() {
        return new CreateContactsRequestBuilder(sdkConfiguration);
    }

    /**
     * Create contacts
     * 
     * <p>Create one or more contacts associated with the organization in a single request. The batch is
     * atomic — if any contact fails validation, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param xOrganizationId ID of the organization the request acts on
     * @param body 
     * @return {@code CompletableFuture<CreateContactsResponse>} - The async response
     */
    public CompletableFuture<CreateContactsResponse> createContacts(@Nonnull String xOrganizationId, @Nonnull List<ContactCreateInput> body) {
        return createContacts(xOrganizationId, null, body);
    }

    /**
     * Create contacts
     * 
     * <p>Create one or more contacts associated with the organization in a single request. The batch is
     * atomic — if any contact fails validation, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param xOrganizationId ID of the organization the request acts on
     * @param idempotencyKey Unique key for idempotent requests. If you retry a request with the same key, the API returns the original response without performing the operation again.
     * @param body 
     * @return {@code CompletableFuture<CreateContactsResponse>} - The async response
     */
    public CompletableFuture<CreateContactsResponse> createContacts(
            @Nonnull String xOrganizationId, @Nullable String idempotencyKey,
            @Nonnull List<ContactCreateInput> body) {
        CreateContactsRequest request = new CreateContactsRequest(xOrganizationId, idempotencyKey, body);
        AsyncRequestOperation<CreateContactsRequest, CreateContactsResponse> operation
              = new CreateContacts.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Retrieve a contact
     * 
     * <p>Retrieve a single contact by ID.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @return The async call builder
     */
    public GetContactRequestBuilder getContact() {
        return new GetContactRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve a contact
     * 
     * <p>Retrieve a single contact by ID.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param id ID of the contact
     * @param xOrganizationId ID of the organization the request acts on
     * @return {@code CompletableFuture<GetContactResponse>} - The async response
     */
    public CompletableFuture<GetContactResponse> getContact(@Nonnull String id, @Nonnull String xOrganizationId) {
        GetContactRequest request = new GetContactRequest(id, xOrganizationId);
        AsyncRequestOperation<GetContactRequest, GetContactResponse> operation
              = new GetContact.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
