/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api;

import static net.nova.api.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import net.nova.api.models.components.EntityPaymentInstructionsInput;
import net.nova.api.models.operations.CreatePaymentInstructionsRequest;
import net.nova.api.models.operations.async.CreatePaymentInstructionsRequestBuilder;
import net.nova.api.models.operations.async.CreatePaymentInstructionsResponse;
import net.nova.api.operations.CreatePaymentInstructions;
import net.nova.api.utils.Headers;

/**
 * Manage payment instructions for entities
 */
public class AsyncPaymentInstructions {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final PaymentInstructions syncSDK;

    AsyncPaymentInstructions(PaymentInstructions syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public PaymentInstructions toSync() {
        return syncSDK;
    }


    /**
     * Create payment instructions
     * 
     * <p>Create one or more payment instructions for one or more entities in a single request. Partial
     * instructions are supported, and this endpoint does not do any input validation. The batch is atomic
     * — if any fail to be created, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @return The async call builder
     */
    public CreatePaymentInstructionsRequestBuilder createPaymentInstructions() {
        return new CreatePaymentInstructionsRequestBuilder(sdkConfiguration);
    }

    /**
     * Create payment instructions
     * 
     * <p>Create one or more payment instructions for one or more entities in a single request. Partial
     * instructions are supported, and this endpoint does not do any input validation. The batch is atomic
     * — if any fail to be created, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param xOrganizationId ID of the organization the request acts on
     * @param body 
     * @return {@code CompletableFuture<CreatePaymentInstructionsResponse>} - The async response
     */
    public CompletableFuture<CreatePaymentInstructionsResponse> createPaymentInstructions(@Nonnull String xOrganizationId, @Nonnull List<EntityPaymentInstructionsInput> body) {
        return createPaymentInstructions(xOrganizationId, null, body);
    }

    /**
     * Create payment instructions
     * 
     * <p>Create one or more payment instructions for one or more entities in a single request. Partial
     * instructions are supported, and this endpoint does not do any input validation. The batch is atomic
     * — if any fail to be created, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param xOrganizationId ID of the organization the request acts on
     * @param idempotencyKey Unique key for idempotent requests. If you retry a request with the same key, the API returns the original response without performing the operation again.
     * @param body 
     * @return {@code CompletableFuture<CreatePaymentInstructionsResponse>} - The async response
     */
    public CompletableFuture<CreatePaymentInstructionsResponse> createPaymentInstructions(
            @Nonnull String xOrganizationId, @Nullable String idempotencyKey,
            @Nonnull List<EntityPaymentInstructionsInput> body) {
        CreatePaymentInstructionsRequest request = new CreatePaymentInstructionsRequest(xOrganizationId, idempotencyKey, body);
        AsyncRequestOperation<CreatePaymentInstructionsRequest, CreatePaymentInstructionsResponse> operation
              = new CreatePaymentInstructions.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
