/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api;

import static net.nova.api.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import java.util.concurrent.CompletableFuture;
import net.nova.api.models.components.OAuthTokenRequest;
import net.nova.api.models.operations.async.CreateOAuthTokenRequestBuilder;
import net.nova.api.models.operations.async.CreateOAuthTokenResponse;
import net.nova.api.operations.CreateOAuthToken;
import net.nova.api.utils.Headers;

/**
 * OAuth2 client_credentials token exchange
 */
public class AsyncAuthentication {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Authentication syncSDK;

    AsyncAuthentication(Authentication syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Authentication toSync() {
        return syncSDK;
    }


    /**
     * Exchange client credentials for an access token
     * 
     * <p>RFC 6749 client_credentials grant. Authenticate with HTTP Basic auth (`Authorization: Basic
     * <base64(client_id:client_secret)>`) or by passing `client_id` and `client_secret` in the request
     * body. Returns a short-lived Bearer access token to use in the `Authorization` header on all other
     * endpoints.
     * 
     * @return The async call builder
     */
    public CreateOAuthTokenRequestBuilder createOAuthToken() {
        return new CreateOAuthTokenRequestBuilder(sdkConfiguration);
    }

    /**
     * Exchange client credentials for an access token
     * 
     * <p>RFC 6749 client_credentials grant. Authenticate with HTTP Basic auth (`Authorization: Basic
     * <base64(client_id:client_secret)>`) or by passing `client_id` and `client_secret` in the request
     * body. Returns a short-lived Bearer access token to use in the `Authorization` header on all other
     * endpoints.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<CreateOAuthTokenResponse>} - The async response
     */
    public CompletableFuture<CreateOAuthTokenResponse> createOAuthToken(@Nonnull OAuthTokenRequest request) {
        AsyncRequestOperation<OAuthTokenRequest, CreateOAuthTokenResponse> operation
              = new CreateOAuthToken.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
