/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api;

import static net.nova.api.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import net.nova.api.models.components.EntityCreateInput;
import net.nova.api.models.components.EntityPaymentInstructionsInput;
import net.nova.api.models.operations.CreateEntitiesRequest;
import net.nova.api.models.operations.CreatePaymentInstructionsRequest;
import net.nova.api.models.operations.GetEntityRequest;
import net.nova.api.models.operations.async.CreateEntitiesRequestBuilder;
import net.nova.api.models.operations.async.CreateEntitiesResponse;
import net.nova.api.models.operations.async.CreatePaymentInstructionsRequestBuilder;
import net.nova.api.models.operations.async.CreatePaymentInstructionsResponse;
import net.nova.api.models.operations.async.GetEntityRequestBuilder;
import net.nova.api.models.operations.async.GetEntityResponse;
import net.nova.api.operations.CreateEntities;
import net.nova.api.operations.CreatePaymentInstructions;
import net.nova.api.operations.GetEntity;
import net.nova.api.utils.Headers;

/**
 * Manage entities
 */
public class AsyncEntities {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Entities syncSDK;

    AsyncEntities(Entities syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Entities toSync() {
        return syncSDK;
    }


    /**
     * Create payment instructions
     * 
     * <p>Create one or more payment instructions for one or more entities in a single request. Partial
     * instructions are supported, and this endpoint does not do any input validation. The batch is atomic
     * — if any fail to be created, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @return The async call builder
     */
    public CreatePaymentInstructionsRequestBuilder createPaymentInstructions() {
        return new CreatePaymentInstructionsRequestBuilder(sdkConfiguration);
    }

    /**
     * Create payment instructions
     * 
     * <p>Create one or more payment instructions for one or more entities in a single request. Partial
     * instructions are supported, and this endpoint does not do any input validation. The batch is atomic
     * — if any fail to be created, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param xOrganizationId ID of the organization the request acts on
     * @param body 
     * @return {@code CompletableFuture<CreatePaymentInstructionsResponse>} - The async response
     */
    public CompletableFuture<CreatePaymentInstructionsResponse> createPaymentInstructions(@Nonnull String xOrganizationId, @Nonnull List<EntityPaymentInstructionsInput> body) {
        return createPaymentInstructions(xOrganizationId, null, body);
    }

    /**
     * Create payment instructions
     * 
     * <p>Create one or more payment instructions for one or more entities in a single request. Partial
     * instructions are supported, and this endpoint does not do any input validation. The batch is atomic
     * — if any fail to be created, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param xOrganizationId ID of the organization the request acts on
     * @param idempotencyKey Unique key for idempotent requests. If you retry a request with the same key, the API returns the original response without performing the operation again.
     * @param body 
     * @return {@code CompletableFuture<CreatePaymentInstructionsResponse>} - The async response
     */
    public CompletableFuture<CreatePaymentInstructionsResponse> createPaymentInstructions(
            @Nonnull String xOrganizationId, @Nullable String idempotencyKey,
            @Nonnull List<EntityPaymentInstructionsInput> body) {
        CreatePaymentInstructionsRequest request = new CreatePaymentInstructionsRequest(xOrganizationId, idempotencyKey, body);
        AsyncRequestOperation<CreatePaymentInstructionsRequest, CreatePaymentInstructionsResponse> operation
              = new CreatePaymentInstructions.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Create entities
     * 
     * <p>Create one or more entities associated with the organization in a single request. The batch is
     * atomic — if any entity fails, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @return The async call builder
     */
    public CreateEntitiesRequestBuilder createEntities() {
        return new CreateEntitiesRequestBuilder(sdkConfiguration);
    }

    /**
     * Create entities
     * 
     * <p>Create one or more entities associated with the organization in a single request. The batch is
     * atomic — if any entity fails, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param xOrganizationId ID of the organization the request acts on
     * @param body 
     * @return {@code CompletableFuture<CreateEntitiesResponse>} - The async response
     */
    public CompletableFuture<CreateEntitiesResponse> createEntities(@Nonnull String xOrganizationId, @Nonnull List<EntityCreateInput> body) {
        return createEntities(xOrganizationId, null, body);
    }

    /**
     * Create entities
     * 
     * <p>Create one or more entities associated with the organization in a single request. The batch is
     * atomic — if any entity fails, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param xOrganizationId ID of the organization the request acts on
     * @param idempotencyKey Unique key for idempotent requests. If you retry a request with the same key, the API returns the original response without performing the operation again.
     * @param body 
     * @return {@code CompletableFuture<CreateEntitiesResponse>} - The async response
     */
    public CompletableFuture<CreateEntitiesResponse> createEntities(
            @Nonnull String xOrganizationId, @Nullable String idempotencyKey,
            @Nonnull List<EntityCreateInput> body) {
        CreateEntitiesRequest request = new CreateEntitiesRequest(xOrganizationId, idempotencyKey, body);
        AsyncRequestOperation<CreateEntitiesRequest, CreateEntitiesResponse> operation
              = new CreateEntities.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Retrieve an entity
     * 
     * <p>Retrieve a single entity by ID.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @return The async call builder
     */
    public GetEntityRequestBuilder getEntity() {
        return new GetEntityRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve an entity
     * 
     * <p>Retrieve a single entity by ID.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param id ID of the entity
     * @param xOrganizationId ID of the organization the request acts on
     * @return {@code CompletableFuture<GetEntityResponse>} - The async response
     */
    public CompletableFuture<GetEntityResponse> getEntity(@Nonnull String id, @Nonnull String xOrganizationId) {
        GetEntityRequest request = new GetEntityRequest(id, xOrganizationId);
        AsyncRequestOperation<GetEntityRequest, GetEntityResponse> operation
              = new GetEntity.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
