/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api;

import static net.nova.api.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import net.nova.api.models.components.DistributionInput;
import net.nova.api.models.operations.CreateDistributionsRequest;
import net.nova.api.models.operations.GetDistributionRequest;
import net.nova.api.models.operations.async.CreateDistributionsRequestBuilder;
import net.nova.api.models.operations.async.CreateDistributionsResponse;
import net.nova.api.models.operations.async.GetDistributionRequestBuilder;
import net.nova.api.models.operations.async.GetDistributionResponse;
import net.nova.api.operations.CreateDistributions;
import net.nova.api.operations.GetDistribution;
import net.nova.api.utils.Headers;

/**
 * Manage distributions
 */
public class AsyncDistributions {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Distributions syncSDK;

    AsyncDistributions(Distributions syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Distributions toSync() {
        return syncSDK;
    }


    /**
     * Create distributions
     * 
     * <p>Create one or more staged fund distributions in a single request. Each distribution has one or more
     * payments; each payment references an existing entity by ID (`entity`) and an optional list of
     * contacts to notify (`notifications[].contact`). Create entities and contacts first via `POST
     * /entities` and `POST /contacts`.
     * 
     * <p>The batch is atomic — if any distribution fails validation, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @return The async call builder
     */
    public CreateDistributionsRequestBuilder createDistributions() {
        return new CreateDistributionsRequestBuilder(sdkConfiguration);
    }

    /**
     * Create distributions
     * 
     * <p>Create one or more staged fund distributions in a single request. Each distribution has one or more
     * payments; each payment references an existing entity by ID (`entity`) and an optional list of
     * contacts to notify (`notifications[].contact`). Create entities and contacts first via `POST
     * /entities` and `POST /contacts`.
     * 
     * <p>The batch is atomic — if any distribution fails validation, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param xOrganizationId ID of the organization the request acts on
     * @param body 
     * @return {@code CompletableFuture<CreateDistributionsResponse>} - The async response
     */
    public CompletableFuture<CreateDistributionsResponse> createDistributions(@Nonnull String xOrganizationId, @Nonnull List<DistributionInput> body) {
        return createDistributions(xOrganizationId, null, body);
    }

    /**
     * Create distributions
     * 
     * <p>Create one or more staged fund distributions in a single request. Each distribution has one or more
     * payments; each payment references an existing entity by ID (`entity`) and an optional list of
     * contacts to notify (`notifications[].contact`). Create entities and contacts first via `POST
     * /entities` and `POST /contacts`.
     * 
     * <p>The batch is atomic — if any distribution fails validation, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param xOrganizationId ID of the organization the request acts on
     * @param idempotencyKey Unique key for idempotent requests. If you retry a request with the same key, the API returns the original response without performing the operation again.
     * @param body 
     * @return {@code CompletableFuture<CreateDistributionsResponse>} - The async response
     */
    public CompletableFuture<CreateDistributionsResponse> createDistributions(
            @Nonnull String xOrganizationId, @Nullable String idempotencyKey,
            @Nonnull List<DistributionInput> body) {
        CreateDistributionsRequest request = new CreateDistributionsRequest(xOrganizationId, idempotencyKey, body);
        AsyncRequestOperation<CreateDistributionsRequest, CreateDistributionsResponse> operation
              = new CreateDistributions.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Retrieve a distribution
     * 
     * <p>Retrieve a distribution with aggregated payment status.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @return The async call builder
     */
    public GetDistributionRequestBuilder getDistribution() {
        return new GetDistributionRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve a distribution
     * 
     * <p>Retrieve a distribution with aggregated payment status.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param id ID of the distribution
     * @param xOrganizationId ID of the organization the request acts on
     * @return {@code CompletableFuture<GetDistributionResponse>} - The async response
     */
    public CompletableFuture<GetDistributionResponse> getDistribution(@Nonnull String id, @Nonnull String xOrganizationId) {
        GetDistributionRequest request = new GetDistributionRequest(id, xOrganizationId);
        AsyncRequestOperation<GetDistributionRequest, GetDistributionResponse> operation
              = new GetDistribution.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
