/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api;

import static net.nova.api.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import net.nova.api.models.components.OAuthTokenRequest;
import net.nova.api.models.operations.CreateOAuthTokenRequestBuilder;
import net.nova.api.models.operations.CreateOAuthTokenResponse;
import net.nova.api.operations.CreateOAuthToken;
import net.nova.api.utils.Headers;

/**
 * OAuth2 client_credentials token exchange
 */
public class Authentication {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncAuthentication asyncSDK;

    Authentication(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncAuthentication(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncAuthentication toAsync() {
        return asyncSDK;
    }

    /**
     * Exchange client credentials for an access token
     * 
     * <p>RFC 6749 client_credentials grant. Authenticate with HTTP Basic auth (`Authorization: Basic
     * <base64(client_id:client_secret)>`) or by passing `client_id` and `client_secret` in the request
     * body. Returns a short-lived Bearer access token to use in the `Authorization` header on all other
     * endpoints.
     * 
     * @return The call builder
     */
    public CreateOAuthTokenRequestBuilder createOAuthToken() {
        return new CreateOAuthTokenRequestBuilder(sdkConfiguration);
    }

    /**
     * Exchange client credentials for an access token
     * 
     * <p>RFC 6749 client_credentials grant. Authenticate with HTTP Basic auth (`Authorization: Basic
     * <base64(client_id:client_secret)>`) or by passing `client_id` and `client_secret` in the request
     * body. Returns a short-lived Bearer access token to use in the `Authorization` header on all other
     * endpoints.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateOAuthTokenResponse createOAuthToken(@Nonnull OAuthTokenRequest request) {
        RequestOperation<OAuthTokenRequest, CreateOAuthTokenResponse> operation
              = new CreateOAuthToken.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
