/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api;

import static net.nova.api.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.List;
import net.nova.api.models.components.ContactCreateInput;
import net.nova.api.models.operations.CreateContactsRequest;
import net.nova.api.models.operations.CreateContactsRequestBuilder;
import net.nova.api.models.operations.CreateContactsResponse;
import net.nova.api.models.operations.GetContactRequest;
import net.nova.api.models.operations.GetContactRequestBuilder;
import net.nova.api.models.operations.GetContactResponse;
import net.nova.api.operations.CreateContacts;
import net.nova.api.operations.GetContact;
import net.nova.api.utils.Headers;

/**
 * Manage contacts
 */
public class Contacts {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncContacts asyncSDK;

    Contacts(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncContacts(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncContacts toAsync() {
        return asyncSDK;
    }

    /**
     * Create contacts
     * 
     * <p>Create one or more contacts associated with the organization in a single request. The batch is
     * atomic — if any contact fails validation, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @return The call builder
     */
    public CreateContactsRequestBuilder createContacts() {
        return new CreateContactsRequestBuilder(sdkConfiguration);
    }

    /**
     * Create contacts
     * 
     * <p>Create one or more contacts associated with the organization in a single request. The batch is
     * atomic — if any contact fails validation, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param xOrganizationId ID of the organization the request acts on
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateContactsResponse createContacts(@Nonnull String xOrganizationId, @Nonnull List<ContactCreateInput> body) {
        return createContacts(xOrganizationId, null, body);
    }

    /**
     * Create contacts
     * 
     * <p>Create one or more contacts associated with the organization in a single request. The batch is
     * atomic — if any contact fails validation, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param xOrganizationId ID of the organization the request acts on
     * @param idempotencyKey Unique key for idempotent requests. If you retry a request with the same key, the API returns the original response without performing the operation again.
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateContactsResponse createContacts(
            @Nonnull String xOrganizationId, @Nullable String idempotencyKey,
            @Nonnull List<ContactCreateInput> body) {
        CreateContactsRequest request = new CreateContactsRequest(xOrganizationId, idempotencyKey, body);
        RequestOperation<CreateContactsRequest, CreateContactsResponse> operation
              = new CreateContacts.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Retrieve a contact
     * 
     * <p>Retrieve a single contact by ID.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @return The call builder
     */
    public GetContactRequestBuilder getContact() {
        return new GetContactRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve a contact
     * 
     * <p>Retrieve a single contact by ID.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param id ID of the contact
     * @param xOrganizationId ID of the organization the request acts on
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetContactResponse getContact(@Nonnull String id, @Nonnull String xOrganizationId) {
        GetContactRequest request = new GetContactRequest(id, xOrganizationId);
        RequestOperation<GetContactRequest, GetContactResponse> operation
              = new GetContact.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
