/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api;

import static net.nova.api.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.List;
import net.nova.api.models.components.DistributionInput;
import net.nova.api.models.operations.CreateDistributionsRequest;
import net.nova.api.models.operations.CreateDistributionsRequestBuilder;
import net.nova.api.models.operations.CreateDistributionsResponse;
import net.nova.api.models.operations.GetDistributionRequest;
import net.nova.api.models.operations.GetDistributionRequestBuilder;
import net.nova.api.models.operations.GetDistributionResponse;
import net.nova.api.operations.CreateDistributions;
import net.nova.api.operations.GetDistribution;
import net.nova.api.utils.Headers;

/**
 * Manage distributions
 */
public class Distributions {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncDistributions asyncSDK;

    Distributions(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncDistributions(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncDistributions toAsync() {
        return asyncSDK;
    }

    /**
     * Create distributions
     * 
     * <p>Create one or more staged fund distributions in a single request. Each distribution has one or more
     * payments; each payment references an existing entity by ID (`entity`) and an optional list of
     * contacts to notify (`notifications[].contact`). Create entities and contacts first via `POST
     * /entities` and `POST /contacts`.
     * 
     * <p>The batch is atomic — if any distribution fails validation, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @return The call builder
     */
    public CreateDistributionsRequestBuilder createDistributions() {
        return new CreateDistributionsRequestBuilder(sdkConfiguration);
    }

    /**
     * Create distributions
     * 
     * <p>Create one or more staged fund distributions in a single request. Each distribution has one or more
     * payments; each payment references an existing entity by ID (`entity`) and an optional list of
     * contacts to notify (`notifications[].contact`). Create entities and contacts first via `POST
     * /entities` and `POST /contacts`.
     * 
     * <p>The batch is atomic — if any distribution fails validation, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param xOrganizationId ID of the organization the request acts on
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateDistributionsResponse createDistributions(@Nonnull String xOrganizationId, @Nonnull List<DistributionInput> body) {
        return createDistributions(xOrganizationId, null, body);
    }

    /**
     * Create distributions
     * 
     * <p>Create one or more staged fund distributions in a single request. Each distribution has one or more
     * payments; each payment references an existing entity by ID (`entity`) and an optional list of
     * contacts to notify (`notifications[].contact`). Create entities and contacts first via `POST
     * /entities` and `POST /contacts`.
     * 
     * <p>The batch is atomic — if any distribution fails validation, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param xOrganizationId ID of the organization the request acts on
     * @param idempotencyKey Unique key for idempotent requests. If you retry a request with the same key, the API returns the original response without performing the operation again.
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateDistributionsResponse createDistributions(
            @Nonnull String xOrganizationId, @Nullable String idempotencyKey,
            @Nonnull List<DistributionInput> body) {
        CreateDistributionsRequest request = new CreateDistributionsRequest(xOrganizationId, idempotencyKey, body);
        RequestOperation<CreateDistributionsRequest, CreateDistributionsResponse> operation
              = new CreateDistributions.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Retrieve a distribution
     * 
     * <p>Retrieve a distribution with aggregated payment status.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @return The call builder
     */
    public GetDistributionRequestBuilder getDistribution() {
        return new GetDistributionRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve a distribution
     * 
     * <p>Retrieve a distribution with aggregated payment status.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param id ID of the distribution
     * @param xOrganizationId ID of the organization the request acts on
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetDistributionResponse getDistribution(@Nonnull String id, @Nonnull String xOrganizationId) {
        GetDistributionRequest request = new GetDistributionRequest(id, xOrganizationId);
        RequestOperation<GetDistributionRequest, GetDistributionResponse> operation
              = new GetDistribution.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
