/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api;

import static net.nova.api.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.List;
import net.nova.api.models.components.EntityCreateInput;
import net.nova.api.models.components.EntityPaymentInstructionsInput;
import net.nova.api.models.operations.CreateEntitiesRequest;
import net.nova.api.models.operations.CreateEntitiesRequestBuilder;
import net.nova.api.models.operations.CreateEntitiesResponse;
import net.nova.api.models.operations.CreatePaymentInstructionsRequest;
import net.nova.api.models.operations.CreatePaymentInstructionsRequestBuilder;
import net.nova.api.models.operations.CreatePaymentInstructionsResponse;
import net.nova.api.models.operations.GetEntityRequest;
import net.nova.api.models.operations.GetEntityRequestBuilder;
import net.nova.api.models.operations.GetEntityResponse;
import net.nova.api.operations.CreateEntities;
import net.nova.api.operations.CreatePaymentInstructions;
import net.nova.api.operations.GetEntity;
import net.nova.api.utils.Headers;

/**
 * Manage entities
 */
public class Entities {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncEntities asyncSDK;

    Entities(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncEntities(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncEntities toAsync() {
        return asyncSDK;
    }

    /**
     * Create payment instructions
     * 
     * <p>Create one or more payment instructions for one or more entities in a single request. Partial
     * instructions are supported, and this endpoint does not do any input validation. The batch is atomic
     * — if any fail to be created, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @return The call builder
     */
    public CreatePaymentInstructionsRequestBuilder createPaymentInstructions() {
        return new CreatePaymentInstructionsRequestBuilder(sdkConfiguration);
    }

    /**
     * Create payment instructions
     * 
     * <p>Create one or more payment instructions for one or more entities in a single request. Partial
     * instructions are supported, and this endpoint does not do any input validation. The batch is atomic
     * — if any fail to be created, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param xOrganizationId ID of the organization the request acts on
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreatePaymentInstructionsResponse createPaymentInstructions(@Nonnull String xOrganizationId, @Nonnull List<EntityPaymentInstructionsInput> body) {
        return createPaymentInstructions(xOrganizationId, null, body);
    }

    /**
     * Create payment instructions
     * 
     * <p>Create one or more payment instructions for one or more entities in a single request. Partial
     * instructions are supported, and this endpoint does not do any input validation. The batch is atomic
     * — if any fail to be created, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param xOrganizationId ID of the organization the request acts on
     * @param idempotencyKey Unique key for idempotent requests. If you retry a request with the same key, the API returns the original response without performing the operation again.
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreatePaymentInstructionsResponse createPaymentInstructions(
            @Nonnull String xOrganizationId, @Nullable String idempotencyKey,
            @Nonnull List<EntityPaymentInstructionsInput> body) {
        CreatePaymentInstructionsRequest request = new CreatePaymentInstructionsRequest(xOrganizationId, idempotencyKey, body);
        RequestOperation<CreatePaymentInstructionsRequest, CreatePaymentInstructionsResponse> operation
              = new CreatePaymentInstructions.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Create entities
     * 
     * <p>Create one or more entities associated with the organization in a single request. The batch is
     * atomic — if any entity fails, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @return The call builder
     */
    public CreateEntitiesRequestBuilder createEntities() {
        return new CreateEntitiesRequestBuilder(sdkConfiguration);
    }

    /**
     * Create entities
     * 
     * <p>Create one or more entities associated with the organization in a single request. The batch is
     * atomic — if any entity fails, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param xOrganizationId ID of the organization the request acts on
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateEntitiesResponse createEntities(@Nonnull String xOrganizationId, @Nonnull List<EntityCreateInput> body) {
        return createEntities(xOrganizationId, null, body);
    }

    /**
     * Create entities
     * 
     * <p>Create one or more entities associated with the organization in a single request. The batch is
     * atomic — if any entity fails, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param xOrganizationId ID of the organization the request acts on
     * @param idempotencyKey Unique key for idempotent requests. If you retry a request with the same key, the API returns the original response without performing the operation again.
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateEntitiesResponse createEntities(
            @Nonnull String xOrganizationId, @Nullable String idempotencyKey,
            @Nonnull List<EntityCreateInput> body) {
        CreateEntitiesRequest request = new CreateEntitiesRequest(xOrganizationId, idempotencyKey, body);
        RequestOperation<CreateEntitiesRequest, CreateEntitiesResponse> operation
              = new CreateEntities.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Retrieve an entity
     * 
     * <p>Retrieve a single entity by ID.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @return The call builder
     */
    public GetEntityRequestBuilder getEntity() {
        return new GetEntityRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve an entity
     * 
     * <p>Retrieve a single entity by ID.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param id ID of the entity
     * @param xOrganizationId ID of the organization the request acts on
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetEntityResponse getEntity(@Nonnull String id, @Nonnull String xOrganizationId) {
        GetEntityRequest request = new GetEntityRequest(id, xOrganizationId);
        RequestOperation<GetEntityRequest, GetEntityResponse> operation
              = new GetEntity.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
