/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package net.nova.api;

import java.lang.String;
import java.util.Map;
import java.util.Optional;
import net.nova.api.utils.HTTPClient;
import net.nova.api.utils.Headers;
import net.nova.api.utils.RetryConfig;
import net.nova.api.utils.SpeakeasyHTTPClient;
import net.nova.api.utils.Utils;

/**
 * Nova API: The Nova API exposes programmatic access to fund operations including distributions,
 * vehicles, entities, and contacts. Authentication is via OAuth2 client_credentials with per-scope
 * authorization.
 * 
 * <p>Live and test mode share the same host (`api.nova.net`); the mode is discriminated by the credential
 * prefix (`sk_prod_*` vs `sk_test_*`). All write operations require an `X-Organization-Id` header
 * identifying the acting organization.
 */
public class NovaSDK {
    private static final Headers _headers = Headers.EMPTY;


    /**
     * SERVERS contains the list of server urls available to the SDK.
     */
    public static final String[] SERVERS = {

        "https://api.nova.net",
    };

    /**
     * OAuth2 client_credentials token exchange
     */
    private final Authentication authentication;

    /**
     * Manage distributions
     */
    private final Distributions distributions;

    /**
     * Manage payment instructions for entities
     */
    private final PaymentInstructions paymentInstructions;

    /**
     * Manage entities
     */
    private final Entities entities;

    /**
     * Manage contacts
     */
    private final Contacts contacts;

    /**
     * OAuth2 client_credentials token exchange
     */
    public Authentication authentication() {
        return authentication;
    }

    /**
     * Manage distributions
     */
    public Distributions distributions() {
        return distributions;
    }

    /**
     * Manage payment instructions for entities
     */
    public PaymentInstructions paymentInstructions() {
        return paymentInstructions;
    }

    /**
     * Manage entities
     */
    public Entities entities() {
        return entities;
    }

    /**
     * Manage contacts
     */
    public Contacts contacts() {
        return contacts;
    }
    private final AsyncNovaSDK asyncSDK;

    /**
     * The Builder class allows the configuration of a new instance of the SDK.
     */
    public static class Builder {

        private final SDKConfiguration sdkConfiguration = new SDKConfiguration();
        private String serverUrl;
        private String server;
        

        private Builder() {
        }

        /**
         * Allows the default HTTP client to be overridden with a custom implementation.
         *
         * @param client The HTTP client to use for all requests.
         * @return The builder instance.
         */
        public Builder client(HTTPClient client) {
            this.sdkConfiguration.setClient(client);
            return this;
        }
        /**
         * Configures the SDK security to use the provided secret.
         *
         * @param oAuth2 The secret to use for all requests.
         * @return The builder instance.
         */
        public Builder oAuth2(String oAuth2) {
            this.sdkConfiguration.setSecuritySource(SecuritySource.of(net.nova.api.models.components.Security.builder()
              .oAuth2(oAuth2)
              .build()));
            return this;
        }

        /**
         * Configures the SDK to use a custom security source.
         *
         * @param securitySource The security source to use for all requests.
         * @return The builder instance.
         */
        public Builder securitySource(SecuritySource securitySource) {
            Utils.checkNotNull(securitySource, "securitySource");
            this.sdkConfiguration.setSecuritySource(securitySource);
            return this;
        }
        
        /**
         * Overrides the default server URL.
         *
         * @param serverUrl The server URL to use for all requests.
         * @return The builder instance.
         */
        public Builder serverURL(String serverUrl) {
            this.serverUrl = serverUrl;
            return this;
        }

        /**
         * Overrides the default server URL with a templated URL populated with the provided parameters.
         *
         * @param serverUrl The server URL to use for all requests.
         * @param params The parameters to use when templating the URL.
         * @return The builder instance.
         */
        public Builder serverURL(String serverUrl, Map<String, String> params) {
            this.serverUrl = Utils.templateUrl(serverUrl, params);
            return this;
        }
        
        /**
         * Overrides the default server by index.
         *
         * @param serverIdx The server to use for all requests.
         * @return The builder instance.
         */
        public Builder serverIndex(int serverIdx) {
            this.sdkConfiguration.setServerIdx(serverIdx);
            this.serverUrl= SERVERS[serverIdx];
            return this;
        }
        
        /**
         * Overrides the default configuration for retries
         *
         * @param retryConfig The retry configuration to use for all requests.
         * @return The builder instance.
         */
        public Builder retryConfig(RetryConfig retryConfig) {
            this.sdkConfiguration.setRetryConfig(Optional.of(retryConfig));
            return this;
        }

        /**
         * Enables debug logging for HTTP requests and responses, including JSON body content.
         * <p>
         * Convenience method that calls {@link HTTPClient#enableDebugLogging(boolean)}.
         * {@link SpeakeasyHTTPClient} honors this setting. If you are using a custom HTTP client,
         * it is up to the custom client to honor this setting.
         * </p>
         *
         * @param enabled Whether to enable debug logging.
         * @return The builder instance.
         */
        public Builder enableHTTPDebugLogging(boolean enabled) {
            this.sdkConfiguration.client().enableDebugLogging(enabled);
            return this;
        }


        /**
         * Builds a new instance of the SDK.
         *
         * @return The SDK instance.
         */
        public NovaSDK build() {
            if (serverUrl == null || serverUrl.isBlank()) {
                serverUrl = SERVERS[0];
                sdkConfiguration.setServerIdx(0);
            }
            sdkConfiguration.setServerUrl(serverUrl);
            return new NovaSDK(sdkConfiguration);
        }
    }

    /**
     * Get a new instance of the SDK builder to configure a new instance of the SDK.
     *
     * @return The SDK builder instance.
     */
    public static Builder builder() {
        return new Builder();
    }

    public NovaSDK(SDKConfiguration sdkConfiguration) {
        sdkConfiguration.initialize();
        this.authentication = new Authentication(sdkConfiguration);
        this.distributions = new Distributions(sdkConfiguration);
        this.paymentInstructions = new PaymentInstructions(sdkConfiguration);
        this.entities = new Entities(sdkConfiguration);
        this.contacts = new Contacts(sdkConfiguration);
        this.asyncSDK = new AsyncNovaSDK(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncNovaSDK toAsync() {
        return asyncSDK;
    }

}
