/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api;

import static net.nova.api.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.List;
import net.nova.api.models.components.EntityPaymentInstructionsInput;
import net.nova.api.models.operations.CreatePaymentInstructionsRequest;
import net.nova.api.models.operations.CreatePaymentInstructionsRequestBuilder;
import net.nova.api.models.operations.CreatePaymentInstructionsResponse;
import net.nova.api.operations.CreatePaymentInstructions;
import net.nova.api.utils.Headers;

/**
 * Manage payment instructions for entities
 */
public class PaymentInstructions {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncPaymentInstructions asyncSDK;

    PaymentInstructions(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncPaymentInstructions(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncPaymentInstructions toAsync() {
        return asyncSDK;
    }

    /**
     * Create payment instructions
     * 
     * <p>Create one or more payment instructions for one or more entities in a single request. Partial
     * instructions are supported, and this endpoint does not do any input validation. The batch is atomic
     * — if any fail to be created, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @return The call builder
     */
    public CreatePaymentInstructionsRequestBuilder createPaymentInstructions() {
        return new CreatePaymentInstructionsRequestBuilder(sdkConfiguration);
    }

    /**
     * Create payment instructions
     * 
     * <p>Create one or more payment instructions for one or more entities in a single request. Partial
     * instructions are supported, and this endpoint does not do any input validation. The batch is atomic
     * — if any fail to be created, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param xOrganizationId ID of the organization the request acts on
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreatePaymentInstructionsResponse createPaymentInstructions(@Nonnull String xOrganizationId, @Nonnull List<EntityPaymentInstructionsInput> body) {
        return createPaymentInstructions(xOrganizationId, null, body);
    }

    /**
     * Create payment instructions
     * 
     * <p>Create one or more payment instructions for one or more entities in a single request. Partial
     * instructions are supported, and this endpoint does not do any input validation. The batch is atomic
     * — if any fail to be created, none are created.
     * 
     * <p>If set, this operation will use Security#oAuth2 from the global security.
     * 
     * @param xOrganizationId ID of the organization the request acts on
     * @param idempotencyKey Unique key for idempotent requests. If you retry a request with the same key, the API returns the original response without performing the operation again.
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreatePaymentInstructionsResponse createPaymentInstructions(
            @Nonnull String xOrganizationId, @Nullable String idempotencyKey,
            @Nonnull List<EntityPaymentInstructionsInput> body) {
        CreatePaymentInstructionsRequest request = new CreatePaymentInstructionsRequest(xOrganizationId, idempotencyKey, body);
        RequestOperation<CreatePaymentInstructionsRequest, CreatePaymentInstructionsResponse> operation
              = new CreatePaymentInstructions.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
