/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import net.nova.api.utils.Utils;

/**
 * AchInstructionsInput
 * 
 * <p>US ACH instructions
 */
public class AchInstructionsInput implements PaymentInstructionsInput {
    /**
     * Name of the account holder, as registered with the bank.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("beneficiary_name")
    private String beneficiaryName;

    /**
     * Bank account number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("account_number")
    private String accountNumber;

    /**
     * Name of the bank.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("bank_name")
    private String bankName;

    /**
     * Bank branch code (e.g. sort code, IFSC, BSB, etc.). Primarily used for international wires.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("branch_code")
    private String branchCode;


    @JsonProperty("type")
    private AchInstructionsInputType type;

    /**
     * ABA routing number
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("routing_number")
    private String routingNumber;

    @JsonCreator
    public AchInstructionsInput(
            @JsonProperty("beneficiary_name") @Nullable String beneficiaryName,
            @JsonProperty("account_number") @Nullable String accountNumber,
            @JsonProperty("bank_name") @Nullable String bankName,
            @JsonProperty("branch_code") @Nullable String branchCode,
            @JsonProperty("type") @Nonnull AchInstructionsInputType type,
            @JsonProperty("routing_number") @Nullable String routingNumber) {
        this.beneficiaryName = beneficiaryName;
        this.accountNumber = accountNumber;
        this.bankName = bankName;
        this.branchCode = branchCode;
        this.type = Optional.ofNullable(type)
            .orElseThrow(() -> new IllegalArgumentException("type cannot be null"));
        this.routingNumber = routingNumber;
    }
    
    public AchInstructionsInput(
            @Nonnull AchInstructionsInputType type) {
        this(null, null, null,
            null, type, null);
    }

    /**
     * Name of the account holder, as registered with the bank.
     */
    public Optional<String> beneficiaryName() {
        return Optional.ofNullable(this.beneficiaryName);
    }

    /**
     * Bank account number.
     */
    public Optional<String> accountNumber() {
        return Optional.ofNullable(this.accountNumber);
    }

    /**
     * Name of the bank.
     */
    public Optional<String> bankName() {
        return Optional.ofNullable(this.bankName);
    }

    /**
     * Bank branch code (e.g. sort code, IFSC, BSB, etc.). Primarily used for international wires.
     */
    public Optional<String> branchCode() {
        return Optional.ofNullable(this.branchCode);
    }

    @Override
    public String type() {
        return Utils.discriminatorToString(type);
    }

    /**
     * ABA routing number
     */
    public Optional<String> routingNumber() {
        return Optional.ofNullable(this.routingNumber);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Name of the account holder, as registered with the bank.
     */
    public AchInstructionsInput withBeneficiaryName(@Nullable String beneficiaryName) {
        this.beneficiaryName = beneficiaryName;
        return this;
    }


    /**
     * Bank account number.
     */
    public AchInstructionsInput withAccountNumber(@Nullable String accountNumber) {
        this.accountNumber = accountNumber;
        return this;
    }


    /**
     * Name of the bank.
     */
    public AchInstructionsInput withBankName(@Nullable String bankName) {
        this.bankName = bankName;
        return this;
    }


    /**
     * Bank branch code (e.g. sort code, IFSC, BSB, etc.). Primarily used for international wires.
     */
    public AchInstructionsInput withBranchCode(@Nullable String branchCode) {
        this.branchCode = branchCode;
        return this;
    }


    public AchInstructionsInput withType(@Nonnull AchInstructionsInputType type) {
        this.type = Utils.checkNotNull(type, "type");
        return this;
    }


    /**
     * ABA routing number
     */
    public AchInstructionsInput withRoutingNumber(@Nullable String routingNumber) {
        this.routingNumber = routingNumber;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AchInstructionsInput other = (AchInstructionsInput) o;
        return 
            Utils.enhancedDeepEquals(this.beneficiaryName, other.beneficiaryName) &&
            Utils.enhancedDeepEquals(this.accountNumber, other.accountNumber) &&
            Utils.enhancedDeepEquals(this.bankName, other.bankName) &&
            Utils.enhancedDeepEquals(this.branchCode, other.branchCode) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.routingNumber, other.routingNumber);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            beneficiaryName, accountNumber, bankName,
            branchCode, type, routingNumber);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AchInstructionsInput.class,
                "beneficiaryName", beneficiaryName,
                "accountNumber", accountNumber,
                "bankName", bankName,
                "branchCode", branchCode,
                "type", type,
                "routingNumber", routingNumber);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String beneficiaryName;

        private String accountNumber;

        private String bankName;

        private String branchCode;

        private AchInstructionsInputType type;

        private String routingNumber;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Name of the account holder, as registered with the bank.
         */
        public Builder beneficiaryName(@Nullable String beneficiaryName) {
            this.beneficiaryName = beneficiaryName;
            return this;
        }

        /**
         * Bank account number.
         */
        public Builder accountNumber(@Nullable String accountNumber) {
            this.accountNumber = accountNumber;
            return this;
        }

        /**
         * Name of the bank.
         */
        public Builder bankName(@Nullable String bankName) {
            this.bankName = bankName;
            return this;
        }

        /**
         * Bank branch code (e.g. sort code, IFSC, BSB, etc.). Primarily used for international wires.
         */
        public Builder branchCode(@Nullable String branchCode) {
            this.branchCode = branchCode;
            return this;
        }

        public Builder type(@Nonnull AchInstructionsInputType type) {
            this.type = Utils.checkNotNull(type, "type");
            return this;
        }

        /**
         * ABA routing number
         */
        public Builder routingNumber(@Nullable String routingNumber) {
            this.routingNumber = routingNumber;
            return this;
        }

        public AchInstructionsInput build() {
            return new AchInstructionsInput(
                beneficiaryName, accountNumber, bankName,
                branchCode, type, routingNumber);
        }

    }
}
