/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * ApiErrorType
 * 
 * <p>High-level error category.
 */
public class ApiErrorType {

    public static final ApiErrorType AUTHENTICATION_ERROR = new ApiErrorType("authentication_error");
    public static final ApiErrorType PERMISSION_ERROR = new ApiErrorType("permission_error");
    public static final ApiErrorType INVALID_REQUEST_ERROR = new ApiErrorType("invalid_request_error");
    public static final ApiErrorType NOT_FOUND_ERROR = new ApiErrorType("not_found_error");
    public static final ApiErrorType CONFLICT_ERROR = new ApiErrorType("conflict_error");
    public static final ApiErrorType RATE_LIMIT_ERROR = new ApiErrorType("rate_limit_error");
    public static final ApiErrorType API_ERROR = new ApiErrorType("api_error");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, ApiErrorType> values = createValuesMap();
    private static final Map<String, ApiErrorTypeEnum> enums = createEnumsMap();

    private final String value;

    private ApiErrorType(String value) {
        this.value = value;
    }

    /**
     * Returns a ApiErrorType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as ApiErrorType
     */ 
    @JsonCreator
    public static ApiErrorType of(String value) {
        synchronized (ApiErrorType.class) {
            return values.computeIfAbsent(value, v -> new ApiErrorType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<ApiErrorTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        ApiErrorType other = (ApiErrorType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "ApiErrorType [value=" + value + "]";
    }

    // return an array just like an enum
    public static ApiErrorType[] values() {
        synchronized (ApiErrorType.class) {
            return values.values().toArray(new ApiErrorType[] {});
        }
    }

    private static final Map<String, ApiErrorType> createValuesMap() {
        Map<String, ApiErrorType> map = new LinkedHashMap<>();
        map.put("authentication_error", AUTHENTICATION_ERROR);
        map.put("permission_error", PERMISSION_ERROR);
        map.put("invalid_request_error", INVALID_REQUEST_ERROR);
        map.put("not_found_error", NOT_FOUND_ERROR);
        map.put("conflict_error", CONFLICT_ERROR);
        map.put("rate_limit_error", RATE_LIMIT_ERROR);
        map.put("api_error", API_ERROR);
        return map;
    }

    private static final Map<String, ApiErrorTypeEnum> createEnumsMap() {
        Map<String, ApiErrorTypeEnum> map = new HashMap<>();
        map.put("authentication_error", ApiErrorTypeEnum.AUTHENTICATION_ERROR);
        map.put("permission_error", ApiErrorTypeEnum.PERMISSION_ERROR);
        map.put("invalid_request_error", ApiErrorTypeEnum.INVALID_REQUEST_ERROR);
        map.put("not_found_error", ApiErrorTypeEnum.NOT_FOUND_ERROR);
        map.put("conflict_error", ApiErrorTypeEnum.CONFLICT_ERROR);
        map.put("rate_limit_error", ApiErrorTypeEnum.RATE_LIMIT_ERROR);
        map.put("api_error", ApiErrorTypeEnum.API_ERROR);
        return map;
    }
    
    
    public enum ApiErrorTypeEnum {

        AUTHENTICATION_ERROR("authentication_error"),
        PERMISSION_ERROR("permission_error"),
        INVALID_REQUEST_ERROR("invalid_request_error"),
        NOT_FOUND_ERROR("not_found_error"),
        CONFLICT_ERROR("conflict_error"),
        RATE_LIMIT_ERROR("rate_limit_error"),
        API_ERROR("api_error"),;

        private final String value;

        private ApiErrorTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

