/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import net.nova.api.utils.Utils;


public class Contact {
    /**
     * Object type identifier.
     */
    @JsonProperty("object")
    private ContactObject object;

    /**
     * Whether this object exists in live mode (`true`) or test mode (`false`).
     */
    @JsonProperty("livemode")
    private boolean livemode;

    /**
     * ID of the contact
     */
    @JsonProperty("id")
    private String id;

    /**
     * Full legal name
     */
    @JsonProperty("name")
    private String name;

    /**
     * Email address
     */
    @JsonProperty("email")
    private String email;

    /**
     * Your own identifiers for this contact
     */
    @JsonProperty("external_references")
    private List<String> externalReferences;

    @JsonCreator
    public Contact(
            @JsonProperty("object") @Nonnull ContactObject object,
            @JsonProperty("livemode") boolean livemode,
            @JsonProperty("id") @Nonnull String id,
            @JsonProperty("name") @Nonnull String name,
            @JsonProperty("email") @Nonnull String email,
            @JsonProperty("external_references") @Nonnull List<String> externalReferences) {
        this.object = Optional.ofNullable(object)
            .orElseThrow(() -> new IllegalArgumentException("object cannot be null"));
        this.livemode = livemode;
        this.id = Optional.ofNullable(id)
            .orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
        this.name = Optional.ofNullable(name)
            .orElseThrow(() -> new IllegalArgumentException("name cannot be null"));
        this.email = Optional.ofNullable(email)
            .orElseThrow(() -> new IllegalArgumentException("email cannot be null"));
        this.externalReferences = Optional.ofNullable(externalReferences)
            .orElseThrow(() -> new IllegalArgumentException("externalReferences cannot be null"));
    }

    /**
     * Object type identifier.
     */
    public ContactObject object() {
        return this.object;
    }

    /**
     * Whether this object exists in live mode (`true`) or test mode (`false`).
     */
    public boolean livemode() {
        return this.livemode;
    }

    /**
     * ID of the contact
     */
    public String id() {
        return this.id;
    }

    /**
     * Full legal name
     */
    public String name() {
        return this.name;
    }

    /**
     * Email address
     */
    public String email() {
        return this.email;
    }

    /**
     * Your own identifiers for this contact
     */
    public List<String> externalReferences() {
        return this.externalReferences;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Object type identifier.
     */
    public Contact withObject(@Nonnull ContactObject object) {
        this.object = Utils.checkNotNull(object, "object");
        return this;
    }


    /**
     * Whether this object exists in live mode (`true`) or test mode (`false`).
     */
    public Contact withLivemode(boolean livemode) {
        this.livemode = livemode;
        return this;
    }


    /**
     * ID of the contact
     */
    public Contact withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }


    /**
     * Full legal name
     */
    public Contact withName(@Nonnull String name) {
        this.name = Utils.checkNotNull(name, "name");
        return this;
    }


    /**
     * Email address
     */
    public Contact withEmail(@Nonnull String email) {
        this.email = Utils.checkNotNull(email, "email");
        return this;
    }


    /**
     * Your own identifiers for this contact
     */
    public Contact withExternalReferences(@Nonnull List<String> externalReferences) {
        this.externalReferences = Utils.checkNotNull(externalReferences, "externalReferences");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Contact other = (Contact) o;
        return 
            Utils.enhancedDeepEquals(this.object, other.object) &&
            Utils.enhancedDeepEquals(this.livemode, other.livemode) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.email, other.email) &&
            Utils.enhancedDeepEquals(this.externalReferences, other.externalReferences);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            object, livemode, id,
            name, email, externalReferences);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Contact.class,
                "object", object,
                "livemode", livemode,
                "id", id,
                "name", name,
                "email", email,
                "externalReferences", externalReferences);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private ContactObject object;

        private boolean livemode;

        private String id;

        private String name;

        private String email;

        private List<String> externalReferences;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Object type identifier.
         */
        public Builder object(@Nonnull ContactObject object) {
            this.object = Utils.checkNotNull(object, "object");
            return this;
        }

        /**
         * Whether this object exists in live mode (`true`) or test mode (`false`).
         */
        public Builder livemode(boolean livemode) {
            this.livemode = livemode;
            return this;
        }

        /**
         * ID of the contact
         */
        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        /**
         * Full legal name
         */
        public Builder name(@Nonnull String name) {
            this.name = Utils.checkNotNull(name, "name");
            return this;
        }

        /**
         * Email address
         */
        public Builder email(@Nonnull String email) {
            this.email = Utils.checkNotNull(email, "email");
            return this;
        }

        /**
         * Your own identifiers for this contact
         */
        public Builder externalReferences(@Nonnull List<String> externalReferences) {
            this.externalReferences = Utils.checkNotNull(externalReferences, "externalReferences");
            return this;
        }

        public Contact build() {
            return new Contact(
                object, livemode, id,
                name, email, externalReferences);
        }

    }
}
