/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import net.nova.api.utils.Utils;


public class ContactCreateInput {
    /**
     * Full legal name
     */
    @JsonProperty("name")
    private String name;

    /**
     * Email address
     */
    @JsonProperty("email")
    private String email;

    /**
     * Your own identifiers for this contact
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("external_references")
    private List<String> externalReferences;

    @JsonCreator
    public ContactCreateInput(
            @JsonProperty("name") @Nonnull String name,
            @JsonProperty("email") @Nonnull String email,
            @JsonProperty("external_references") @Nullable List<String> externalReferences) {
        this.name = Optional.ofNullable(name)
            .orElseThrow(() -> new IllegalArgumentException("name cannot be null"));
        this.email = Optional.ofNullable(email)
            .orElseThrow(() -> new IllegalArgumentException("email cannot be null"));
        this.externalReferences = externalReferences;
    }
    
    public ContactCreateInput(
            @Nonnull String name,
            @Nonnull String email) {
        this(name, email, null);
    }

    /**
     * Full legal name
     */
    public String name() {
        return this.name;
    }

    /**
     * Email address
     */
    public String email() {
        return this.email;
    }

    /**
     * Your own identifiers for this contact
     */
    public Optional<List<String>> externalReferences() {
        return Optional.ofNullable(this.externalReferences);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Full legal name
     */
    public ContactCreateInput withName(@Nonnull String name) {
        this.name = Utils.checkNotNull(name, "name");
        return this;
    }


    /**
     * Email address
     */
    public ContactCreateInput withEmail(@Nonnull String email) {
        this.email = Utils.checkNotNull(email, "email");
        return this;
    }


    /**
     * Your own identifiers for this contact
     */
    public ContactCreateInput withExternalReferences(@Nullable List<String> externalReferences) {
        this.externalReferences = externalReferences;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ContactCreateInput other = (ContactCreateInput) o;
        return 
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.email, other.email) &&
            Utils.enhancedDeepEquals(this.externalReferences, other.externalReferences);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            name, email, externalReferences);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ContactCreateInput.class,
                "name", name,
                "email", email,
                "externalReferences", externalReferences);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String name;

        private String email;

        private List<String> externalReferences;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Full legal name
         */
        public Builder name(@Nonnull String name) {
            this.name = Utils.checkNotNull(name, "name");
            return this;
        }

        /**
         * Email address
         */
        public Builder email(@Nonnull String email) {
            this.email = Utils.checkNotNull(email, "email");
            return this;
        }

        /**
         * Your own identifiers for this contact
         */
        public Builder externalReferences(@Nullable List<String> externalReferences) {
            this.externalReferences = externalReferences;
            return this;
        }

        public ContactCreateInput build() {
            return new ContactCreateInput(
                name, email, externalReferences);
        }

    }
}
