/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import net.nova.api.utils.Utils;
import org.openapitools.jackson.nullable.JsonNullable;


public class DistributionPayment {
    /**
     * Object type identifier.
     */
    @JsonProperty("object")
    private DistributionPaymentObject object;

    /**
     * Whether this object exists in live mode (`true`) or test mode (`false`).
     */
    @JsonProperty("livemode")
    private boolean livemode;

    /**
     * ID of the distribution payment
     */
    @JsonProperty("id")
    private String id;

    /**
     * Amount in the smallest currency unit
     */
    @JsonProperty("amount")
    private long amount;

    /**
     * ISO 4217 currency code (USD-only currently)
     */
    @JsonProperty("currency")
    private Currency currency;

    /**
     * Distribution date override
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("distribution_date_override")
    private OffsetDateTime distributionDateOverride;


    @JsonProperty("status")
    private DistributionPaymentStatus status;


    @JsonInclude(Include.ALWAYS)
    @JsonProperty("recipient_confirmed_at")
    private JsonNullable<OffsetDateTime> recipientConfirmedAt;


    @JsonInclude(Include.ALWAYS)
    @JsonProperty("verified_at")
    private JsonNullable<OffsetDateTime> verifiedAt;


    @JsonProperty("entity")
    private Entity entity;

    /**
     * Contacts notified when the payment is published.
     */
    @JsonProperty("notifications")
    private List<DistributionNotification> notifications;

    @JsonCreator
    public DistributionPayment(
            @JsonProperty("object") @Nonnull DistributionPaymentObject object,
            @JsonProperty("livemode") boolean livemode,
            @JsonProperty("id") @Nonnull String id,
            @JsonProperty("amount") long amount,
            @JsonProperty("currency") @Nonnull Currency currency,
            @JsonProperty("distribution_date_override") @Nullable OffsetDateTime distributionDateOverride,
            @JsonProperty("status") @Nonnull DistributionPaymentStatus status,
            @JsonProperty("recipient_confirmed_at") @Nullable OffsetDateTime recipientConfirmedAt,
            @JsonProperty("verified_at") @Nullable OffsetDateTime verifiedAt,
            @JsonProperty("entity") @Nonnull Entity entity,
            @JsonProperty("notifications") @Nonnull List<DistributionNotification> notifications) {
        this.object = Optional.ofNullable(object)
            .orElseThrow(() -> new IllegalArgumentException("object cannot be null"));
        this.livemode = livemode;
        this.id = Optional.ofNullable(id)
            .orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
        this.amount = amount;
        this.currency = Optional.ofNullable(currency)
            .orElseThrow(() -> new IllegalArgumentException("currency cannot be null"));
        this.distributionDateOverride = distributionDateOverride;
        this.status = Optional.ofNullable(status)
            .orElseThrow(() -> new IllegalArgumentException("status cannot be null"));
        this.recipientConfirmedAt = JsonNullable.of(recipientConfirmedAt);
        this.verifiedAt = JsonNullable.of(verifiedAt);
        this.entity = Optional.ofNullable(entity)
            .orElseThrow(() -> new IllegalArgumentException("entity cannot be null"));
        this.notifications = Optional.ofNullable(notifications)
            .orElseThrow(() -> new IllegalArgumentException("notifications cannot be null"));
    }
    
    public DistributionPayment(
            @Nonnull DistributionPaymentObject object,
            boolean livemode,
            @Nonnull String id,
            long amount,
            @Nonnull Currency currency,
            @Nonnull DistributionPaymentStatus status,
            @Nonnull Entity entity,
            @Nonnull List<DistributionNotification> notifications) {
        this(object, livemode, id,
            amount, currency, null,
            status, null, null,
            entity, notifications);
    }

    /**
     * Object type identifier.
     */
    public DistributionPaymentObject object() {
        return this.object;
    }

    /**
     * Whether this object exists in live mode (`true`) or test mode (`false`).
     */
    public boolean livemode() {
        return this.livemode;
    }

    /**
     * ID of the distribution payment
     */
    public String id() {
        return this.id;
    }

    /**
     * Amount in the smallest currency unit
     */
    public long amount() {
        return this.amount;
    }

    /**
     * ISO 4217 currency code (USD-only currently)
     */
    public Currency currency() {
        return this.currency;
    }

    /**
     * Distribution date override
     */
    public Optional<OffsetDateTime> distributionDateOverride() {
        return Optional.ofNullable(this.distributionDateOverride);
    }

    public DistributionPaymentStatus status() {
        return this.status;
    }

    public JsonNullable<OffsetDateTime> recipientConfirmedAt() {
        return this.recipientConfirmedAt;
    }

    public JsonNullable<OffsetDateTime> verifiedAt() {
        return this.verifiedAt;
    }

    public Entity entity() {
        return this.entity;
    }

    /**
     * Contacts notified when the payment is published.
     */
    public List<DistributionNotification> notifications() {
        return this.notifications;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Object type identifier.
     */
    public DistributionPayment withObject(@Nonnull DistributionPaymentObject object) {
        this.object = Utils.checkNotNull(object, "object");
        return this;
    }


    /**
     * Whether this object exists in live mode (`true`) or test mode (`false`).
     */
    public DistributionPayment withLivemode(boolean livemode) {
        this.livemode = livemode;
        return this;
    }


    /**
     * ID of the distribution payment
     */
    public DistributionPayment withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }


    /**
     * Amount in the smallest currency unit
     */
    public DistributionPayment withAmount(long amount) {
        this.amount = amount;
        return this;
    }


    /**
     * ISO 4217 currency code (USD-only currently)
     */
    public DistributionPayment withCurrency(@Nonnull Currency currency) {
        this.currency = Utils.checkNotNull(currency, "currency");
        return this;
    }


    /**
     * Distribution date override
     */
    public DistributionPayment withDistributionDateOverride(@Nullable OffsetDateTime distributionDateOverride) {
        this.distributionDateOverride = distributionDateOverride;
        return this;
    }


    public DistributionPayment withStatus(@Nonnull DistributionPaymentStatus status) {
        this.status = Utils.checkNotNull(status, "status");
        return this;
    }


    public DistributionPayment withRecipientConfirmedAt(@Nullable OffsetDateTime recipientConfirmedAt) {
        this.recipientConfirmedAt = JsonNullable.of(recipientConfirmedAt);
        return this;
    }


    public DistributionPayment withVerifiedAt(@Nullable OffsetDateTime verifiedAt) {
        this.verifiedAt = JsonNullable.of(verifiedAt);
        return this;
    }


    public DistributionPayment withEntity(@Nonnull Entity entity) {
        this.entity = Utils.checkNotNull(entity, "entity");
        return this;
    }


    /**
     * Contacts notified when the payment is published.
     */
    public DistributionPayment withNotifications(@Nonnull List<DistributionNotification> notifications) {
        this.notifications = Utils.checkNotNull(notifications, "notifications");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DistributionPayment other = (DistributionPayment) o;
        return 
            Utils.enhancedDeepEquals(this.object, other.object) &&
            Utils.enhancedDeepEquals(this.livemode, other.livemode) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.amount, other.amount) &&
            Utils.enhancedDeepEquals(this.currency, other.currency) &&
            Utils.enhancedDeepEquals(this.distributionDateOverride, other.distributionDateOverride) &&
            Utils.enhancedDeepEquals(this.status, other.status) &&
            Utils.enhancedDeepEquals(this.recipientConfirmedAt, other.recipientConfirmedAt) &&
            Utils.enhancedDeepEquals(this.verifiedAt, other.verifiedAt) &&
            Utils.enhancedDeepEquals(this.entity, other.entity) &&
            Utils.enhancedDeepEquals(this.notifications, other.notifications);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            object, livemode, id,
            amount, currency, distributionDateOverride,
            status, recipientConfirmedAt, verifiedAt,
            entity, notifications);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DistributionPayment.class,
                "object", object,
                "livemode", livemode,
                "id", id,
                "amount", amount,
                "currency", currency,
                "distributionDateOverride", distributionDateOverride,
                "status", status,
                "recipientConfirmedAt", recipientConfirmedAt,
                "verifiedAt", verifiedAt,
                "entity", entity,
                "notifications", notifications);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private DistributionPaymentObject object;

        private boolean livemode;

        private String id;

        private long amount;

        private Currency currency;

        private OffsetDateTime distributionDateOverride;

        private DistributionPaymentStatus status;

        private OffsetDateTime recipientConfirmedAt;

        private OffsetDateTime verifiedAt;

        private Entity entity;

        private List<DistributionNotification> notifications;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Object type identifier.
         */
        public Builder object(@Nonnull DistributionPaymentObject object) {
            this.object = Utils.checkNotNull(object, "object");
            return this;
        }

        /**
         * Whether this object exists in live mode (`true`) or test mode (`false`).
         */
        public Builder livemode(boolean livemode) {
            this.livemode = livemode;
            return this;
        }

        /**
         * ID of the distribution payment
         */
        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        /**
         * Amount in the smallest currency unit
         */
        public Builder amount(long amount) {
            this.amount = amount;
            return this;
        }

        /**
         * ISO 4217 currency code (USD-only currently)
         */
        public Builder currency(@Nonnull Currency currency) {
            this.currency = Utils.checkNotNull(currency, "currency");
            return this;
        }

        /**
         * Distribution date override
         */
        public Builder distributionDateOverride(@Nullable OffsetDateTime distributionDateOverride) {
            this.distributionDateOverride = distributionDateOverride;
            return this;
        }

        public Builder status(@Nonnull DistributionPaymentStatus status) {
            this.status = Utils.checkNotNull(status, "status");
            return this;
        }

        public Builder recipientConfirmedAt(@Nullable OffsetDateTime recipientConfirmedAt) {
            this.recipientConfirmedAt = recipientConfirmedAt;
            return this;
        }

        public Builder verifiedAt(@Nullable OffsetDateTime verifiedAt) {
            this.verifiedAt = verifiedAt;
            return this;
        }

        public Builder entity(@Nonnull Entity entity) {
            this.entity = Utils.checkNotNull(entity, "entity");
            return this;
        }

        /**
         * Contacts notified when the payment is published.
         */
        public Builder notifications(@Nonnull List<DistributionNotification> notifications) {
            this.notifications = Utils.checkNotNull(notifications, "notifications");
            return this;
        }

        public DistributionPayment build() {
            return new DistributionPayment(
                object, livemode, id,
                amount, currency, distributionDateOverride,
                status, recipientConfirmedAt, verifiedAt,
                entity, notifications);
        }

    }
}
