/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class DistributionStatus {

    public static final DistributionStatus DRAFT = new DistributionStatus("draft");
    public static final DistributionStatus PUBLISHED = new DistributionStatus("published");
    public static final DistributionStatus APPROVED = new DistributionStatus("approved");
    public static final DistributionStatus EXECUTED = new DistributionStatus("executed");
    public static final DistributionStatus CANCELLED = new DistributionStatus("cancelled");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, DistributionStatus> values = createValuesMap();
    private static final Map<String, DistributionStatusEnum> enums = createEnumsMap();

    private final String value;

    private DistributionStatus(String value) {
        this.value = value;
    }

    /**
     * Returns a DistributionStatus with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as DistributionStatus
     */ 
    @JsonCreator
    public static DistributionStatus of(String value) {
        synchronized (DistributionStatus.class) {
            return values.computeIfAbsent(value, v -> new DistributionStatus(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<DistributionStatusEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        DistributionStatus other = (DistributionStatus) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "DistributionStatus [value=" + value + "]";
    }

    // return an array just like an enum
    public static DistributionStatus[] values() {
        synchronized (DistributionStatus.class) {
            return values.values().toArray(new DistributionStatus[] {});
        }
    }

    private static final Map<String, DistributionStatus> createValuesMap() {
        Map<String, DistributionStatus> map = new LinkedHashMap<>();
        map.put("draft", DRAFT);
        map.put("published", PUBLISHED);
        map.put("approved", APPROVED);
        map.put("executed", EXECUTED);
        map.put("cancelled", CANCELLED);
        return map;
    }

    private static final Map<String, DistributionStatusEnum> createEnumsMap() {
        Map<String, DistributionStatusEnum> map = new HashMap<>();
        map.put("draft", DistributionStatusEnum.DRAFT);
        map.put("published", DistributionStatusEnum.PUBLISHED);
        map.put("approved", DistributionStatusEnum.APPROVED);
        map.put("executed", DistributionStatusEnum.EXECUTED);
        map.put("cancelled", DistributionStatusEnum.CANCELLED);
        return map;
    }
    
    
    public enum DistributionStatusEnum {

        DRAFT("draft"),
        PUBLISHED("published"),
        APPROVED("approved"),
        EXECUTED("executed"),
        CANCELLED("cancelled"),;

        private final String value;

        private DistributionStatusEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

