/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Optional;
import net.nova.api.utils.Utils;
import org.openapitools.jackson.nullable.JsonNullable;


public class Distribution {
    /**
     * Object type identifier.
     */
    @JsonProperty("object")
    private DistributionObject object;

    /**
     * Whether this object exists in live mode (`true`) or test mode (`false`).
     */
    @JsonProperty("livemode")
    private boolean livemode;

    /**
     * ID of the distribution
     */
    @JsonProperty("id")
    private String id;


    @JsonProperty("name")
    private String name;

    /**
     * Distribution date
     */
    @JsonProperty("distribution_date")
    private OffsetDateTime distributionDate;

    /**
     * ID of the vehicle this distribution pays from
     */
    @JsonProperty("vehicle")
    private String vehicle;


    @JsonProperty("short_id")
    private String shortId;


    @JsonProperty("status")
    private DistributionStatus status;


    @JsonInclude(Include.ALWAYS)
    @JsonProperty("published_at")
    private JsonNullable<OffsetDateTime> publishedAt;


    @JsonInclude(Include.ALWAYS)
    @JsonProperty("approved_at")
    private JsonNullable<OffsetDateTime> approvedAt;


    @JsonInclude(Include.ALWAYS)
    @JsonProperty("executed_at")
    private JsonNullable<OffsetDateTime> executedAt;


    @JsonInclude(Include.ALWAYS)
    @JsonProperty("cancelled_at")
    private JsonNullable<OffsetDateTime> cancelledAt;


    @JsonProperty("created_at")
    private OffsetDateTime createdAt;


    @JsonProperty("updated_at")
    private OffsetDateTime updatedAt;

    /**
     * A link to manage this distribution in the Nova dashboard
     */
    @JsonProperty("sender_url")
    private String senderUrl;


    @JsonProperty("payments")
    private DistributionPaymentList payments;

    @JsonCreator
    public Distribution(
            @JsonProperty("object") @Nonnull DistributionObject object,
            @JsonProperty("livemode") boolean livemode,
            @JsonProperty("id") @Nonnull String id,
            @JsonProperty("name") @Nonnull String name,
            @JsonProperty("distribution_date") @Nonnull OffsetDateTime distributionDate,
            @JsonProperty("vehicle") @Nonnull String vehicle,
            @JsonProperty("short_id") @Nonnull String shortId,
            @JsonProperty("status") @Nonnull DistributionStatus status,
            @JsonProperty("published_at") @Nullable OffsetDateTime publishedAt,
            @JsonProperty("approved_at") @Nullable OffsetDateTime approvedAt,
            @JsonProperty("executed_at") @Nullable OffsetDateTime executedAt,
            @JsonProperty("cancelled_at") @Nullable OffsetDateTime cancelledAt,
            @JsonProperty("created_at") @Nonnull OffsetDateTime createdAt,
            @JsonProperty("updated_at") @Nonnull OffsetDateTime updatedAt,
            @JsonProperty("sender_url") @Nonnull String senderUrl,
            @JsonProperty("payments") @Nonnull DistributionPaymentList payments) {
        this.object = Optional.ofNullable(object)
            .orElseThrow(() -> new IllegalArgumentException("object cannot be null"));
        this.livemode = livemode;
        this.id = Optional.ofNullable(id)
            .orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
        this.name = Optional.ofNullable(name)
            .orElseThrow(() -> new IllegalArgumentException("name cannot be null"));
        this.distributionDate = Optional.ofNullable(distributionDate)
            .orElseThrow(() -> new IllegalArgumentException("distributionDate cannot be null"));
        this.vehicle = Optional.ofNullable(vehicle)
            .orElseThrow(() -> new IllegalArgumentException("vehicle cannot be null"));
        this.shortId = Optional.ofNullable(shortId)
            .orElseThrow(() -> new IllegalArgumentException("shortId cannot be null"));
        this.status = Optional.ofNullable(status)
            .orElseThrow(() -> new IllegalArgumentException("status cannot be null"));
        this.publishedAt = JsonNullable.of(publishedAt);
        this.approvedAt = JsonNullable.of(approvedAt);
        this.executedAt = JsonNullable.of(executedAt);
        this.cancelledAt = JsonNullable.of(cancelledAt);
        this.createdAt = Optional.ofNullable(createdAt)
            .orElseThrow(() -> new IllegalArgumentException("createdAt cannot be null"));
        this.updatedAt = Optional.ofNullable(updatedAt)
            .orElseThrow(() -> new IllegalArgumentException("updatedAt cannot be null"));
        this.senderUrl = Optional.ofNullable(senderUrl)
            .orElseThrow(() -> new IllegalArgumentException("senderUrl cannot be null"));
        this.payments = Optional.ofNullable(payments)
            .orElseThrow(() -> new IllegalArgumentException("payments cannot be null"));
    }
    
    public Distribution(
            @Nonnull DistributionObject object,
            boolean livemode,
            @Nonnull String id,
            @Nonnull String name,
            @Nonnull OffsetDateTime distributionDate,
            @Nonnull String vehicle,
            @Nonnull String shortId,
            @Nonnull DistributionStatus status,
            @Nonnull OffsetDateTime createdAt,
            @Nonnull OffsetDateTime updatedAt,
            @Nonnull String senderUrl,
            @Nonnull DistributionPaymentList payments) {
        this(object, livemode, id,
            name, distributionDate, vehicle,
            shortId, status, null,
            null, null, null,
            createdAt, updatedAt, senderUrl,
            payments);
    }

    /**
     * Object type identifier.
     */
    public DistributionObject object() {
        return this.object;
    }

    /**
     * Whether this object exists in live mode (`true`) or test mode (`false`).
     */
    public boolean livemode() {
        return this.livemode;
    }

    /**
     * ID of the distribution
     */
    public String id() {
        return this.id;
    }

    public String name() {
        return this.name;
    }

    /**
     * Distribution date
     */
    public OffsetDateTime distributionDate() {
        return this.distributionDate;
    }

    /**
     * ID of the vehicle this distribution pays from
     */
    public String vehicle() {
        return this.vehicle;
    }

    public String shortId() {
        return this.shortId;
    }

    public DistributionStatus status() {
        return this.status;
    }

    public JsonNullable<OffsetDateTime> publishedAt() {
        return this.publishedAt;
    }

    public JsonNullable<OffsetDateTime> approvedAt() {
        return this.approvedAt;
    }

    public JsonNullable<OffsetDateTime> executedAt() {
        return this.executedAt;
    }

    public JsonNullable<OffsetDateTime> cancelledAt() {
        return this.cancelledAt;
    }

    public OffsetDateTime createdAt() {
        return this.createdAt;
    }

    public OffsetDateTime updatedAt() {
        return this.updatedAt;
    }

    /**
     * A link to manage this distribution in the Nova dashboard
     */
    public String senderUrl() {
        return this.senderUrl;
    }

    public DistributionPaymentList payments() {
        return this.payments;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Object type identifier.
     */
    public Distribution withObject(@Nonnull DistributionObject object) {
        this.object = Utils.checkNotNull(object, "object");
        return this;
    }


    /**
     * Whether this object exists in live mode (`true`) or test mode (`false`).
     */
    public Distribution withLivemode(boolean livemode) {
        this.livemode = livemode;
        return this;
    }


    /**
     * ID of the distribution
     */
    public Distribution withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }


    public Distribution withName(@Nonnull String name) {
        this.name = Utils.checkNotNull(name, "name");
        return this;
    }


    /**
     * Distribution date
     */
    public Distribution withDistributionDate(@Nonnull OffsetDateTime distributionDate) {
        this.distributionDate = Utils.checkNotNull(distributionDate, "distributionDate");
        return this;
    }


    /**
     * ID of the vehicle this distribution pays from
     */
    public Distribution withVehicle(@Nonnull String vehicle) {
        this.vehicle = Utils.checkNotNull(vehicle, "vehicle");
        return this;
    }


    public Distribution withShortId(@Nonnull String shortId) {
        this.shortId = Utils.checkNotNull(shortId, "shortId");
        return this;
    }


    public Distribution withStatus(@Nonnull DistributionStatus status) {
        this.status = Utils.checkNotNull(status, "status");
        return this;
    }


    public Distribution withPublishedAt(@Nullable OffsetDateTime publishedAt) {
        this.publishedAt = JsonNullable.of(publishedAt);
        return this;
    }


    public Distribution withApprovedAt(@Nullable OffsetDateTime approvedAt) {
        this.approvedAt = JsonNullable.of(approvedAt);
        return this;
    }


    public Distribution withExecutedAt(@Nullable OffsetDateTime executedAt) {
        this.executedAt = JsonNullable.of(executedAt);
        return this;
    }


    public Distribution withCancelledAt(@Nullable OffsetDateTime cancelledAt) {
        this.cancelledAt = JsonNullable.of(cancelledAt);
        return this;
    }


    public Distribution withCreatedAt(@Nonnull OffsetDateTime createdAt) {
        this.createdAt = Utils.checkNotNull(createdAt, "createdAt");
        return this;
    }


    public Distribution withUpdatedAt(@Nonnull OffsetDateTime updatedAt) {
        this.updatedAt = Utils.checkNotNull(updatedAt, "updatedAt");
        return this;
    }


    /**
     * A link to manage this distribution in the Nova dashboard
     */
    public Distribution withSenderUrl(@Nonnull String senderUrl) {
        this.senderUrl = Utils.checkNotNull(senderUrl, "senderUrl");
        return this;
    }


    public Distribution withPayments(@Nonnull DistributionPaymentList payments) {
        this.payments = Utils.checkNotNull(payments, "payments");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Distribution other = (Distribution) o;
        return 
            Utils.enhancedDeepEquals(this.object, other.object) &&
            Utils.enhancedDeepEquals(this.livemode, other.livemode) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.distributionDate, other.distributionDate) &&
            Utils.enhancedDeepEquals(this.vehicle, other.vehicle) &&
            Utils.enhancedDeepEquals(this.shortId, other.shortId) &&
            Utils.enhancedDeepEquals(this.status, other.status) &&
            Utils.enhancedDeepEquals(this.publishedAt, other.publishedAt) &&
            Utils.enhancedDeepEquals(this.approvedAt, other.approvedAt) &&
            Utils.enhancedDeepEquals(this.executedAt, other.executedAt) &&
            Utils.enhancedDeepEquals(this.cancelledAt, other.cancelledAt) &&
            Utils.enhancedDeepEquals(this.createdAt, other.createdAt) &&
            Utils.enhancedDeepEquals(this.updatedAt, other.updatedAt) &&
            Utils.enhancedDeepEquals(this.senderUrl, other.senderUrl) &&
            Utils.enhancedDeepEquals(this.payments, other.payments);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            object, livemode, id,
            name, distributionDate, vehicle,
            shortId, status, publishedAt,
            approvedAt, executedAt, cancelledAt,
            createdAt, updatedAt, senderUrl,
            payments);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Distribution.class,
                "object", object,
                "livemode", livemode,
                "id", id,
                "name", name,
                "distributionDate", distributionDate,
                "vehicle", vehicle,
                "shortId", shortId,
                "status", status,
                "publishedAt", publishedAt,
                "approvedAt", approvedAt,
                "executedAt", executedAt,
                "cancelledAt", cancelledAt,
                "createdAt", createdAt,
                "updatedAt", updatedAt,
                "senderUrl", senderUrl,
                "payments", payments);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private DistributionObject object;

        private boolean livemode;

        private String id;

        private String name;

        private OffsetDateTime distributionDate;

        private String vehicle;

        private String shortId;

        private DistributionStatus status;

        private OffsetDateTime publishedAt;

        private OffsetDateTime approvedAt;

        private OffsetDateTime executedAt;

        private OffsetDateTime cancelledAt;

        private OffsetDateTime createdAt;

        private OffsetDateTime updatedAt;

        private String senderUrl;

        private DistributionPaymentList payments;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Object type identifier.
         */
        public Builder object(@Nonnull DistributionObject object) {
            this.object = Utils.checkNotNull(object, "object");
            return this;
        }

        /**
         * Whether this object exists in live mode (`true`) or test mode (`false`).
         */
        public Builder livemode(boolean livemode) {
            this.livemode = livemode;
            return this;
        }

        /**
         * ID of the distribution
         */
        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        public Builder name(@Nonnull String name) {
            this.name = Utils.checkNotNull(name, "name");
            return this;
        }

        /**
         * Distribution date
         */
        public Builder distributionDate(@Nonnull OffsetDateTime distributionDate) {
            this.distributionDate = Utils.checkNotNull(distributionDate, "distributionDate");
            return this;
        }

        /**
         * ID of the vehicle this distribution pays from
         */
        public Builder vehicle(@Nonnull String vehicle) {
            this.vehicle = Utils.checkNotNull(vehicle, "vehicle");
            return this;
        }

        public Builder shortId(@Nonnull String shortId) {
            this.shortId = Utils.checkNotNull(shortId, "shortId");
            return this;
        }

        public Builder status(@Nonnull DistributionStatus status) {
            this.status = Utils.checkNotNull(status, "status");
            return this;
        }

        public Builder publishedAt(@Nullable OffsetDateTime publishedAt) {
            this.publishedAt = publishedAt;
            return this;
        }

        public Builder approvedAt(@Nullable OffsetDateTime approvedAt) {
            this.approvedAt = approvedAt;
            return this;
        }

        public Builder executedAt(@Nullable OffsetDateTime executedAt) {
            this.executedAt = executedAt;
            return this;
        }

        public Builder cancelledAt(@Nullable OffsetDateTime cancelledAt) {
            this.cancelledAt = cancelledAt;
            return this;
        }

        public Builder createdAt(@Nonnull OffsetDateTime createdAt) {
            this.createdAt = Utils.checkNotNull(createdAt, "createdAt");
            return this;
        }

        public Builder updatedAt(@Nonnull OffsetDateTime updatedAt) {
            this.updatedAt = Utils.checkNotNull(updatedAt, "updatedAt");
            return this;
        }

        /**
         * A link to manage this distribution in the Nova dashboard
         */
        public Builder senderUrl(@Nonnull String senderUrl) {
            this.senderUrl = Utils.checkNotNull(senderUrl, "senderUrl");
            return this;
        }

        public Builder payments(@Nonnull DistributionPaymentList payments) {
            this.payments = Utils.checkNotNull(payments, "payments");
            return this;
        }

        public Distribution build() {
            return new Distribution(
                object, livemode, id,
                name, distributionDate, vehicle,
                shortId, status, publishedAt,
                approvedAt, executedAt, cancelledAt,
                createdAt, updatedAt, senderUrl,
                payments);
        }

    }
}
