/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import net.nova.api.utils.Utils;


public class DistributionPaymentInput {
    /**
     * Amount in the smallest currency unit
     */
    @JsonProperty("amount")
    private long amount;

    /**
     * ISO 4217 currency code (USD-only currently)
     */
    @JsonProperty("currency")
    private Currency currency;

    /**
     * Distribution date override
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("distribution_date_override")
    private OffsetDateTime distributionDateOverride;

    /**
     * ID of the entity receiving this payment. The entity will have an implicit association created with
     * the distribution vehicle.
     */
    @JsonProperty("entity")
    private String entity;

    /**
     * Contacts to notify when the payment is published.
     */
    @JsonProperty("notifications")
    private List<DistributionNotificationInput> notifications;

    @JsonCreator
    public DistributionPaymentInput(
            @JsonProperty("amount") long amount,
            @JsonProperty("currency") @Nonnull Currency currency,
            @JsonProperty("distribution_date_override") @Nullable OffsetDateTime distributionDateOverride,
            @JsonProperty("entity") @Nonnull String entity,
            @JsonProperty("notifications") @Nonnull List<DistributionNotificationInput> notifications) {
        this.amount = amount;
        this.currency = Optional.ofNullable(currency)
            .orElseThrow(() -> new IllegalArgumentException("currency cannot be null"));
        this.distributionDateOverride = distributionDateOverride;
        this.entity = Optional.ofNullable(entity)
            .orElseThrow(() -> new IllegalArgumentException("entity cannot be null"));
        this.notifications = Optional.ofNullable(notifications)
            .orElseThrow(() -> new IllegalArgumentException("notifications cannot be null"));
    }
    
    public DistributionPaymentInput(
            long amount,
            @Nonnull Currency currency,
            @Nonnull String entity,
            @Nonnull List<DistributionNotificationInput> notifications) {
        this(amount, currency, null,
            entity, notifications);
    }

    /**
     * Amount in the smallest currency unit
     */
    public long amount() {
        return this.amount;
    }

    /**
     * ISO 4217 currency code (USD-only currently)
     */
    public Currency currency() {
        return this.currency;
    }

    /**
     * Distribution date override
     */
    public Optional<OffsetDateTime> distributionDateOverride() {
        return Optional.ofNullable(this.distributionDateOverride);
    }

    /**
     * ID of the entity receiving this payment. The entity will have an implicit association created with
     * the distribution vehicle.
     */
    public String entity() {
        return this.entity;
    }

    /**
     * Contacts to notify when the payment is published.
     */
    public List<DistributionNotificationInput> notifications() {
        return this.notifications;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Amount in the smallest currency unit
     */
    public DistributionPaymentInput withAmount(long amount) {
        this.amount = amount;
        return this;
    }


    /**
     * ISO 4217 currency code (USD-only currently)
     */
    public DistributionPaymentInput withCurrency(@Nonnull Currency currency) {
        this.currency = Utils.checkNotNull(currency, "currency");
        return this;
    }


    /**
     * Distribution date override
     */
    public DistributionPaymentInput withDistributionDateOverride(@Nullable OffsetDateTime distributionDateOverride) {
        this.distributionDateOverride = distributionDateOverride;
        return this;
    }


    /**
     * ID of the entity receiving this payment. The entity will have an implicit association created with
     * the distribution vehicle.
     */
    public DistributionPaymentInput withEntity(@Nonnull String entity) {
        this.entity = Utils.checkNotNull(entity, "entity");
        return this;
    }


    /**
     * Contacts to notify when the payment is published.
     */
    public DistributionPaymentInput withNotifications(@Nonnull List<DistributionNotificationInput> notifications) {
        this.notifications = Utils.checkNotNull(notifications, "notifications");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DistributionPaymentInput other = (DistributionPaymentInput) o;
        return 
            Utils.enhancedDeepEquals(this.amount, other.amount) &&
            Utils.enhancedDeepEquals(this.currency, other.currency) &&
            Utils.enhancedDeepEquals(this.distributionDateOverride, other.distributionDateOverride) &&
            Utils.enhancedDeepEquals(this.entity, other.entity) &&
            Utils.enhancedDeepEquals(this.notifications, other.notifications);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            amount, currency, distributionDateOverride,
            entity, notifications);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DistributionPaymentInput.class,
                "amount", amount,
                "currency", currency,
                "distributionDateOverride", distributionDateOverride,
                "entity", entity,
                "notifications", notifications);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private long amount;

        private Currency currency;

        private OffsetDateTime distributionDateOverride;

        private String entity;

        private List<DistributionNotificationInput> notifications;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Amount in the smallest currency unit
         */
        public Builder amount(long amount) {
            this.amount = amount;
            return this;
        }

        /**
         * ISO 4217 currency code (USD-only currently)
         */
        public Builder currency(@Nonnull Currency currency) {
            this.currency = Utils.checkNotNull(currency, "currency");
            return this;
        }

        /**
         * Distribution date override
         */
        public Builder distributionDateOverride(@Nullable OffsetDateTime distributionDateOverride) {
            this.distributionDateOverride = distributionDateOverride;
            return this;
        }

        /**
         * ID of the entity receiving this payment. The entity will have an implicit association created with
         * the distribution vehicle.
         */
        public Builder entity(@Nonnull String entity) {
            this.entity = Utils.checkNotNull(entity, "entity");
            return this;
        }

        /**
         * Contacts to notify when the payment is published.
         */
        public Builder notifications(@Nonnull List<DistributionNotificationInput> notifications) {
            this.notifications = Utils.checkNotNull(notifications, "notifications");
            return this;
        }

        public DistributionPaymentInput build() {
            return new DistributionPaymentInput(
                amount, currency, distributionDateOverride,
                entity, notifications);
        }

    }
}
