/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * DistributionPaymentObject
 * 
 * <p>Object type identifier.
 */
public class DistributionPaymentObject {

    public static final DistributionPaymentObject DISTRIBUTION_PAYMENT = new DistributionPaymentObject("distribution_payment");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, DistributionPaymentObject> values = createValuesMap();
    private static final Map<String, DistributionPaymentObjectEnum> enums = createEnumsMap();

    private final String value;

    private DistributionPaymentObject(String value) {
        this.value = value;
    }

    /**
     * Returns a DistributionPaymentObject with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as DistributionPaymentObject
     */ 
    @JsonCreator
    public static DistributionPaymentObject of(String value) {
        synchronized (DistributionPaymentObject.class) {
            return values.computeIfAbsent(value, v -> new DistributionPaymentObject(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<DistributionPaymentObjectEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        DistributionPaymentObject other = (DistributionPaymentObject) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "DistributionPaymentObject [value=" + value + "]";
    }

    // return an array just like an enum
    public static DistributionPaymentObject[] values() {
        synchronized (DistributionPaymentObject.class) {
            return values.values().toArray(new DistributionPaymentObject[] {});
        }
    }

    private static final Map<String, DistributionPaymentObject> createValuesMap() {
        Map<String, DistributionPaymentObject> map = new LinkedHashMap<>();
        map.put("distribution_payment", DISTRIBUTION_PAYMENT);
        return map;
    }

    private static final Map<String, DistributionPaymentObjectEnum> createEnumsMap() {
        Map<String, DistributionPaymentObjectEnum> map = new HashMap<>();
        map.put("distribution_payment", DistributionPaymentObjectEnum.DISTRIBUTION_PAYMENT);
        return map;
    }
    
    
    public enum DistributionPaymentObjectEnum {

        DISTRIBUTION_PAYMENT("distribution_payment"),;

        private final String value;

        private DistributionPaymentObjectEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

