/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import net.nova.api.utils.Utils;


public class DistributionNotificationInput {

    @JsonProperty("contact")
    private ContactRef contact;

    @JsonCreator
    public DistributionNotificationInput(
            @JsonProperty("contact") @Nonnull ContactRef contact) {
        this.contact = Optional.ofNullable(contact)
            .orElseThrow(() -> new IllegalArgumentException("contact cannot be null"));
    }

    public ContactRef contact() {
        return this.contact;
    }

    public static Builder builder() {
        return new Builder();
    }


    public DistributionNotificationInput withContact(@Nonnull ContactRef contact) {
        this.contact = Utils.checkNotNull(contact, "contact");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DistributionNotificationInput other = (DistributionNotificationInput) o;
        return 
            Utils.enhancedDeepEquals(this.contact, other.contact);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contact);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DistributionNotificationInput.class,
                "contact", contact);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private ContactRef contact;

        private Builder() {
          // force use of static builder() method
        }

        public Builder contact(@Nonnull ContactRef contact) {
            this.contact = Utils.checkNotNull(contact, "contact");
            return this;
        }

        public DistributionNotificationInput build() {
            return new DistributionNotificationInput(
                contact);
        }

    }
}
