/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * DistributionObject
 * 
 * <p>Object type identifier.
 */
public class DistributionObject {

    public static final DistributionObject DISTRIBUTION = new DistributionObject("distribution");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, DistributionObject> values = createValuesMap();
    private static final Map<String, DistributionObjectEnum> enums = createEnumsMap();

    private final String value;

    private DistributionObject(String value) {
        this.value = value;
    }

    /**
     * Returns a DistributionObject with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as DistributionObject
     */ 
    @JsonCreator
    public static DistributionObject of(String value) {
        synchronized (DistributionObject.class) {
            return values.computeIfAbsent(value, v -> new DistributionObject(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<DistributionObjectEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        DistributionObject other = (DistributionObject) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "DistributionObject [value=" + value + "]";
    }

    // return an array just like an enum
    public static DistributionObject[] values() {
        synchronized (DistributionObject.class) {
            return values.values().toArray(new DistributionObject[] {});
        }
    }

    private static final Map<String, DistributionObject> createValuesMap() {
        Map<String, DistributionObject> map = new LinkedHashMap<>();
        map.put("distribution", DISTRIBUTION);
        return map;
    }

    private static final Map<String, DistributionObjectEnum> createEnumsMap() {
        Map<String, DistributionObjectEnum> map = new HashMap<>();
        map.put("distribution", DistributionObjectEnum.DISTRIBUTION);
        return map;
    }
    
    
    public enum DistributionObjectEnum {

        DISTRIBUTION("distribution"),;

        private final String value;

        private DistributionObjectEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

