/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import net.nova.api.utils.Utils;


public class DistributionInput {

    @JsonProperty("name")
    private String name;

    /**
     * Distribution date
     */
    @JsonProperty("distribution_date")
    private OffsetDateTime distributionDate;

    /**
     * ID of the vehicle this distribution pays from
     */
    @JsonProperty("vehicle")
    private String vehicle;

    /**
     * List of payments
     */
    @JsonProperty("payments")
    private List<DistributionPaymentInput> payments;

    @JsonCreator
    public DistributionInput(
            @JsonProperty("name") @Nonnull String name,
            @JsonProperty("distribution_date") @Nonnull OffsetDateTime distributionDate,
            @JsonProperty("vehicle") @Nonnull String vehicle,
            @JsonProperty("payments") @Nonnull List<DistributionPaymentInput> payments) {
        this.name = Optional.ofNullable(name)
            .orElseThrow(() -> new IllegalArgumentException("name cannot be null"));
        this.distributionDate = Optional.ofNullable(distributionDate)
            .orElseThrow(() -> new IllegalArgumentException("distributionDate cannot be null"));
        this.vehicle = Optional.ofNullable(vehicle)
            .orElseThrow(() -> new IllegalArgumentException("vehicle cannot be null"));
        this.payments = Optional.ofNullable(payments)
            .orElseThrow(() -> new IllegalArgumentException("payments cannot be null"));
    }

    public String name() {
        return this.name;
    }

    /**
     * Distribution date
     */
    public OffsetDateTime distributionDate() {
        return this.distributionDate;
    }

    /**
     * ID of the vehicle this distribution pays from
     */
    public String vehicle() {
        return this.vehicle;
    }

    /**
     * List of payments
     */
    public List<DistributionPaymentInput> payments() {
        return this.payments;
    }

    public static Builder builder() {
        return new Builder();
    }


    public DistributionInput withName(@Nonnull String name) {
        this.name = Utils.checkNotNull(name, "name");
        return this;
    }


    /**
     * Distribution date
     */
    public DistributionInput withDistributionDate(@Nonnull OffsetDateTime distributionDate) {
        this.distributionDate = Utils.checkNotNull(distributionDate, "distributionDate");
        return this;
    }


    /**
     * ID of the vehicle this distribution pays from
     */
    public DistributionInput withVehicle(@Nonnull String vehicle) {
        this.vehicle = Utils.checkNotNull(vehicle, "vehicle");
        return this;
    }


    /**
     * List of payments
     */
    public DistributionInput withPayments(@Nonnull List<DistributionPaymentInput> payments) {
        this.payments = Utils.checkNotNull(payments, "payments");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DistributionInput other = (DistributionInput) o;
        return 
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.distributionDate, other.distributionDate) &&
            Utils.enhancedDeepEquals(this.vehicle, other.vehicle) &&
            Utils.enhancedDeepEquals(this.payments, other.payments);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            name, distributionDate, vehicle,
            payments);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DistributionInput.class,
                "name", name,
                "distributionDate", distributionDate,
                "vehicle", vehicle,
                "payments", payments);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String name;

        private OffsetDateTime distributionDate;

        private String vehicle;

        private List<DistributionPaymentInput> payments;

        private Builder() {
          // force use of static builder() method
        }

        public Builder name(@Nonnull String name) {
            this.name = Utils.checkNotNull(name, "name");
            return this;
        }

        /**
         * Distribution date
         */
        public Builder distributionDate(@Nonnull OffsetDateTime distributionDate) {
            this.distributionDate = Utils.checkNotNull(distributionDate, "distributionDate");
            return this;
        }

        /**
         * ID of the vehicle this distribution pays from
         */
        public Builder vehicle(@Nonnull String vehicle) {
            this.vehicle = Utils.checkNotNull(vehicle, "vehicle");
            return this;
        }

        /**
         * List of payments
         */
        public Builder payments(@Nonnull List<DistributionPaymentInput> payments) {
            this.payments = Utils.checkNotNull(payments, "payments");
            return this;
        }

        public DistributionInput build() {
            return new DistributionInput(
                name, distributionDate, vehicle,
                payments);
        }

    }
}
