/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class DistributionPaymentStatus {

    public static final DistributionPaymentStatus STAGED = new DistributionPaymentStatus("staged");
    public static final DistributionPaymentStatus RECIPIENT_CONFIRMED = new DistributionPaymentStatus("recipient_confirmed");
    public static final DistributionPaymentStatus VERIFIED = new DistributionPaymentStatus("verified");
    public static final DistributionPaymentStatus DISBURSED = new DistributionPaymentStatus("disbursed");
    public static final DistributionPaymentStatus FAILED = new DistributionPaymentStatus("failed");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, DistributionPaymentStatus> values = createValuesMap();
    private static final Map<String, DistributionPaymentStatusEnum> enums = createEnumsMap();

    private final String value;

    private DistributionPaymentStatus(String value) {
        this.value = value;
    }

    /**
     * Returns a DistributionPaymentStatus with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as DistributionPaymentStatus
     */ 
    @JsonCreator
    public static DistributionPaymentStatus of(String value) {
        synchronized (DistributionPaymentStatus.class) {
            return values.computeIfAbsent(value, v -> new DistributionPaymentStatus(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<DistributionPaymentStatusEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        DistributionPaymentStatus other = (DistributionPaymentStatus) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "DistributionPaymentStatus [value=" + value + "]";
    }

    // return an array just like an enum
    public static DistributionPaymentStatus[] values() {
        synchronized (DistributionPaymentStatus.class) {
            return values.values().toArray(new DistributionPaymentStatus[] {});
        }
    }

    private static final Map<String, DistributionPaymentStatus> createValuesMap() {
        Map<String, DistributionPaymentStatus> map = new LinkedHashMap<>();
        map.put("staged", STAGED);
        map.put("recipient_confirmed", RECIPIENT_CONFIRMED);
        map.put("verified", VERIFIED);
        map.put("disbursed", DISBURSED);
        map.put("failed", FAILED);
        return map;
    }

    private static final Map<String, DistributionPaymentStatusEnum> createEnumsMap() {
        Map<String, DistributionPaymentStatusEnum> map = new HashMap<>();
        map.put("staged", DistributionPaymentStatusEnum.STAGED);
        map.put("recipient_confirmed", DistributionPaymentStatusEnum.RECIPIENT_CONFIRMED);
        map.put("verified", DistributionPaymentStatusEnum.VERIFIED);
        map.put("disbursed", DistributionPaymentStatusEnum.DISBURSED);
        map.put("failed", DistributionPaymentStatusEnum.FAILED);
        return map;
    }
    
    
    public enum DistributionPaymentStatusEnum {

        STAGED("staged"),
        RECIPIENT_CONFIRMED("recipient_confirmed"),
        VERIFIED("verified"),
        DISBURSED("disbursed"),
        FAILED("failed"),;

        private final String value;

        private DistributionPaymentStatusEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

