/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum DomesticWireInstructionsInputType {
    DOMESTIC_WIRE("domestic_wire");

    @JsonValue
    private final String value;

    DomesticWireInstructionsInputType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<DomesticWireInstructionsInputType> fromValue(String value) {
        for (DomesticWireInstructionsInputType o: DomesticWireInstructionsInputType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

