/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * EntityPaymentInstructionsListObject
 * 
 * <p>Object type identifier.
 */
public class EntityPaymentInstructionsListObject {

    public static final EntityPaymentInstructionsListObject LIST = new EntityPaymentInstructionsListObject("list");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, EntityPaymentInstructionsListObject> values = createValuesMap();
    private static final Map<String, EntityPaymentInstructionsListObjectEnum> enums = createEnumsMap();

    private final String value;

    private EntityPaymentInstructionsListObject(String value) {
        this.value = value;
    }

    /**
     * Returns a EntityPaymentInstructionsListObject with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as EntityPaymentInstructionsListObject
     */ 
    @JsonCreator
    public static EntityPaymentInstructionsListObject of(String value) {
        synchronized (EntityPaymentInstructionsListObject.class) {
            return values.computeIfAbsent(value, v -> new EntityPaymentInstructionsListObject(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<EntityPaymentInstructionsListObjectEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        EntityPaymentInstructionsListObject other = (EntityPaymentInstructionsListObject) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "EntityPaymentInstructionsListObject [value=" + value + "]";
    }

    // return an array just like an enum
    public static EntityPaymentInstructionsListObject[] values() {
        synchronized (EntityPaymentInstructionsListObject.class) {
            return values.values().toArray(new EntityPaymentInstructionsListObject[] {});
        }
    }

    private static final Map<String, EntityPaymentInstructionsListObject> createValuesMap() {
        Map<String, EntityPaymentInstructionsListObject> map = new LinkedHashMap<>();
        map.put("list", LIST);
        return map;
    }

    private static final Map<String, EntityPaymentInstructionsListObjectEnum> createEnumsMap() {
        Map<String, EntityPaymentInstructionsListObjectEnum> map = new HashMap<>();
        map.put("list", EntityPaymentInstructionsListObjectEnum.LIST);
        return map;
    }
    
    
    public enum EntityPaymentInstructionsListObjectEnum {

        LIST("list"),;

        private final String value;

        private EntityPaymentInstructionsListObjectEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

