/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class EntityType {

    public static final EntityType INDIVIDUAL = new EntityType("individual");
    public static final EntityType INDIVIDUAL_RETIREMENT_PLAN = new EntityType("individual_retirement_plan");
    public static final EntityType CORPORATION = new EntityType("corporation");
    public static final EntityType LLC = new EntityType("llc");
    public static final EntityType PARTNERSHIP = new EntityType("partnership");
    public static final EntityType TRUST = new EntityType("trust");
    public static final EntityType JOINT_TENANTS_ROS = new EntityType("joint_tenants_ros");
    public static final EntityType TENANTS_IN_COMMON = new EntityType("tenants_in_common");
    public static final EntityType COMMUNITY_PROPERTY = new EntityType("community_property");
    public static final EntityType REGISTERED_INVESTMENT_COMPANY = new EntityType("registered_investment_company");
    public static final EntityType FOUNDATION = new EntityType("foundation");
    public static final EntityType CHARITABLE_REMAINDER_TRUST = new EntityType("charitable_remainder_trust");
    public static final EntityType ENDOWMENT = new EntityType("endowment");
    public static final EntityType EMPLOYEE_BENEFIT_PLAN = new EntityType("employee_benefit_plan");
    public static final EntityType KEOGH_PLAN = new EntityType("keogh_plan");
    public static final EntityType OTHER_ENTITY = new EntityType("other_entity");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, EntityType> values = createValuesMap();
    private static final Map<String, EntityTypeEnum> enums = createEnumsMap();

    private final String value;

    private EntityType(String value) {
        this.value = value;
    }

    /**
     * Returns a EntityType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as EntityType
     */ 
    @JsonCreator
    public static EntityType of(String value) {
        synchronized (EntityType.class) {
            return values.computeIfAbsent(value, v -> new EntityType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<EntityTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        EntityType other = (EntityType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "EntityType [value=" + value + "]";
    }

    // return an array just like an enum
    public static EntityType[] values() {
        synchronized (EntityType.class) {
            return values.values().toArray(new EntityType[] {});
        }
    }

    private static final Map<String, EntityType> createValuesMap() {
        Map<String, EntityType> map = new LinkedHashMap<>();
        map.put("individual", INDIVIDUAL);
        map.put("individual_retirement_plan", INDIVIDUAL_RETIREMENT_PLAN);
        map.put("corporation", CORPORATION);
        map.put("llc", LLC);
        map.put("partnership", PARTNERSHIP);
        map.put("trust", TRUST);
        map.put("joint_tenants_ros", JOINT_TENANTS_ROS);
        map.put("tenants_in_common", TENANTS_IN_COMMON);
        map.put("community_property", COMMUNITY_PROPERTY);
        map.put("registered_investment_company", REGISTERED_INVESTMENT_COMPANY);
        map.put("foundation", FOUNDATION);
        map.put("charitable_remainder_trust", CHARITABLE_REMAINDER_TRUST);
        map.put("endowment", ENDOWMENT);
        map.put("employee_benefit_plan", EMPLOYEE_BENEFIT_PLAN);
        map.put("keogh_plan", KEOGH_PLAN);
        map.put("other_entity", OTHER_ENTITY);
        return map;
    }

    private static final Map<String, EntityTypeEnum> createEnumsMap() {
        Map<String, EntityTypeEnum> map = new HashMap<>();
        map.put("individual", EntityTypeEnum.INDIVIDUAL);
        map.put("individual_retirement_plan", EntityTypeEnum.INDIVIDUAL_RETIREMENT_PLAN);
        map.put("corporation", EntityTypeEnum.CORPORATION);
        map.put("llc", EntityTypeEnum.LLC);
        map.put("partnership", EntityTypeEnum.PARTNERSHIP);
        map.put("trust", EntityTypeEnum.TRUST);
        map.put("joint_tenants_ros", EntityTypeEnum.JOINT_TENANTS_ROS);
        map.put("tenants_in_common", EntityTypeEnum.TENANTS_IN_COMMON);
        map.put("community_property", EntityTypeEnum.COMMUNITY_PROPERTY);
        map.put("registered_investment_company", EntityTypeEnum.REGISTERED_INVESTMENT_COMPANY);
        map.put("foundation", EntityTypeEnum.FOUNDATION);
        map.put("charitable_remainder_trust", EntityTypeEnum.CHARITABLE_REMAINDER_TRUST);
        map.put("endowment", EntityTypeEnum.ENDOWMENT);
        map.put("employee_benefit_plan", EntityTypeEnum.EMPLOYEE_BENEFIT_PLAN);
        map.put("keogh_plan", EntityTypeEnum.KEOGH_PLAN);
        map.put("other_entity", EntityTypeEnum.OTHER_ENTITY);
        return map;
    }
    
    
    public enum EntityTypeEnum {

        INDIVIDUAL("individual"),
        INDIVIDUAL_RETIREMENT_PLAN("individual_retirement_plan"),
        CORPORATION("corporation"),
        LLC("llc"),
        PARTNERSHIP("partnership"),
        TRUST("trust"),
        JOINT_TENANTS_ROS("joint_tenants_ros"),
        TENANTS_IN_COMMON("tenants_in_common"),
        COMMUNITY_PROPERTY("community_property"),
        REGISTERED_INVESTMENT_COMPANY("registered_investment_company"),
        FOUNDATION("foundation"),
        CHARITABLE_REMAINDER_TRUST("charitable_remainder_trust"),
        ENDOWMENT("endowment"),
        EMPLOYEE_BENEFIT_PLAN("employee_benefit_plan"),
        KEOGH_PLAN("keogh_plan"),
        OTHER_ENTITY("other_entity"),;

        private final String value;

        private EntityTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

