/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import net.nova.api.utils.Utils;


public class EntityCreateInput {
    /**
     * Legal name of the entity
     */
    @JsonProperty("name")
    private String name;


    @JsonProperty("type")
    private EntityType type;

    /**
     * Your own identifiers for this entity
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("external_references")
    private List<String> externalReferences;

    @JsonCreator
    public EntityCreateInput(
            @JsonProperty("name") @Nonnull String name,
            @JsonProperty("type") @Nonnull EntityType type,
            @JsonProperty("external_references") @Nullable List<String> externalReferences) {
        this.name = Optional.ofNullable(name)
            .orElseThrow(() -> new IllegalArgumentException("name cannot be null"));
        this.type = Optional.ofNullable(type)
            .orElseThrow(() -> new IllegalArgumentException("type cannot be null"));
        this.externalReferences = externalReferences;
    }
    
    public EntityCreateInput(
            @Nonnull String name,
            @Nonnull EntityType type) {
        this(name, type, null);
    }

    /**
     * Legal name of the entity
     */
    public String name() {
        return this.name;
    }

    public EntityType type() {
        return this.type;
    }

    /**
     * Your own identifiers for this entity
     */
    public Optional<List<String>> externalReferences() {
        return Optional.ofNullable(this.externalReferences);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Legal name of the entity
     */
    public EntityCreateInput withName(@Nonnull String name) {
        this.name = Utils.checkNotNull(name, "name");
        return this;
    }


    public EntityCreateInput withType(@Nonnull EntityType type) {
        this.type = Utils.checkNotNull(type, "type");
        return this;
    }


    /**
     * Your own identifiers for this entity
     */
    public EntityCreateInput withExternalReferences(@Nullable List<String> externalReferences) {
        this.externalReferences = externalReferences;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EntityCreateInput other = (EntityCreateInput) o;
        return 
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.externalReferences, other.externalReferences);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            name, type, externalReferences);
    }
    
    @Override
    public String toString() {
        return Utils.toString(EntityCreateInput.class,
                "name", name,
                "type", type,
                "externalReferences", externalReferences);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String name;

        private EntityType type;

        private List<String> externalReferences;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Legal name of the entity
         */
        public Builder name(@Nonnull String name) {
            this.name = Utils.checkNotNull(name, "name");
            return this;
        }

        public Builder type(@Nonnull EntityType type) {
            this.type = Utils.checkNotNull(type, "type");
            return this;
        }

        /**
         * Your own identifiers for this entity
         */
        public Builder externalReferences(@Nullable List<String> externalReferences) {
            this.externalReferences = externalReferences;
            return this;
        }

        public EntityCreateInput build() {
            return new EntityCreateInput(
                name, type, externalReferences);
        }

    }
}
