/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import net.nova.api.utils.Utils;


public class Entity {
    /**
     * Object type identifier.
     */
    @JsonProperty("object")
    private EntityObject object;

    /**
     * Whether this object exists in live mode (`true`) or test mode (`false`).
     */
    @JsonProperty("livemode")
    private boolean livemode;

    /**
     * ID of the entity
     */
    @JsonProperty("id")
    private String id;

    /**
     * Legal name of the entity
     */
    @JsonProperty("name")
    private String name;


    @JsonProperty("type")
    private EntityType type;

    /**
     * Your own identifiers for this entity
     */
    @JsonProperty("external_references")
    private List<String> externalReferences;

    @JsonCreator
    public Entity(
            @JsonProperty("object") @Nonnull EntityObject object,
            @JsonProperty("livemode") boolean livemode,
            @JsonProperty("id") @Nonnull String id,
            @JsonProperty("name") @Nonnull String name,
            @JsonProperty("type") @Nonnull EntityType type,
            @JsonProperty("external_references") @Nonnull List<String> externalReferences) {
        this.object = Optional.ofNullable(object)
            .orElseThrow(() -> new IllegalArgumentException("object cannot be null"));
        this.livemode = livemode;
        this.id = Optional.ofNullable(id)
            .orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
        this.name = Optional.ofNullable(name)
            .orElseThrow(() -> new IllegalArgumentException("name cannot be null"));
        this.type = Optional.ofNullable(type)
            .orElseThrow(() -> new IllegalArgumentException("type cannot be null"));
        this.externalReferences = Optional.ofNullable(externalReferences)
            .orElseThrow(() -> new IllegalArgumentException("externalReferences cannot be null"));
    }

    /**
     * Object type identifier.
     */
    public EntityObject object() {
        return this.object;
    }

    /**
     * Whether this object exists in live mode (`true`) or test mode (`false`).
     */
    public boolean livemode() {
        return this.livemode;
    }

    /**
     * ID of the entity
     */
    public String id() {
        return this.id;
    }

    /**
     * Legal name of the entity
     */
    public String name() {
        return this.name;
    }

    public EntityType type() {
        return this.type;
    }

    /**
     * Your own identifiers for this entity
     */
    public List<String> externalReferences() {
        return this.externalReferences;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Object type identifier.
     */
    public Entity withObject(@Nonnull EntityObject object) {
        this.object = Utils.checkNotNull(object, "object");
        return this;
    }


    /**
     * Whether this object exists in live mode (`true`) or test mode (`false`).
     */
    public Entity withLivemode(boolean livemode) {
        this.livemode = livemode;
        return this;
    }


    /**
     * ID of the entity
     */
    public Entity withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }


    /**
     * Legal name of the entity
     */
    public Entity withName(@Nonnull String name) {
        this.name = Utils.checkNotNull(name, "name");
        return this;
    }


    public Entity withType(@Nonnull EntityType type) {
        this.type = Utils.checkNotNull(type, "type");
        return this;
    }


    /**
     * Your own identifiers for this entity
     */
    public Entity withExternalReferences(@Nonnull List<String> externalReferences) {
        this.externalReferences = Utils.checkNotNull(externalReferences, "externalReferences");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Entity other = (Entity) o;
        return 
            Utils.enhancedDeepEquals(this.object, other.object) &&
            Utils.enhancedDeepEquals(this.livemode, other.livemode) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.externalReferences, other.externalReferences);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            object, livemode, id,
            name, type, externalReferences);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Entity.class,
                "object", object,
                "livemode", livemode,
                "id", id,
                "name", name,
                "type", type,
                "externalReferences", externalReferences);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private EntityObject object;

        private boolean livemode;

        private String id;

        private String name;

        private EntityType type;

        private List<String> externalReferences;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Object type identifier.
         */
        public Builder object(@Nonnull EntityObject object) {
            this.object = Utils.checkNotNull(object, "object");
            return this;
        }

        /**
         * Whether this object exists in live mode (`true`) or test mode (`false`).
         */
        public Builder livemode(boolean livemode) {
            this.livemode = livemode;
            return this;
        }

        /**
         * ID of the entity
         */
        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        /**
         * Legal name of the entity
         */
        public Builder name(@Nonnull String name) {
            this.name = Utils.checkNotNull(name, "name");
            return this;
        }

        public Builder type(@Nonnull EntityType type) {
            this.type = Utils.checkNotNull(type, "type");
            return this;
        }

        /**
         * Your own identifiers for this entity
         */
        public Builder externalReferences(@Nonnull List<String> externalReferences) {
            this.externalReferences = Utils.checkNotNull(externalReferences, "externalReferences");
            return this;
        }

        public Entity build() {
            return new Entity(
                object, livemode, id,
                name, type, externalReferences);
        }

    }
}
