/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * EntityObject
 * 
 * <p>Object type identifier.
 */
public class EntityObject {

    public static final EntityObject ENTITY = new EntityObject("entity");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, EntityObject> values = createValuesMap();
    private static final Map<String, EntityObjectEnum> enums = createEnumsMap();

    private final String value;

    private EntityObject(String value) {
        this.value = value;
    }

    /**
     * Returns a EntityObject with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as EntityObject
     */ 
    @JsonCreator
    public static EntityObject of(String value) {
        synchronized (EntityObject.class) {
            return values.computeIfAbsent(value, v -> new EntityObject(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<EntityObjectEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        EntityObject other = (EntityObject) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "EntityObject [value=" + value + "]";
    }

    // return an array just like an enum
    public static EntityObject[] values() {
        synchronized (EntityObject.class) {
            return values.values().toArray(new EntityObject[] {});
        }
    }

    private static final Map<String, EntityObject> createValuesMap() {
        Map<String, EntityObject> map = new LinkedHashMap<>();
        map.put("entity", ENTITY);
        return map;
    }

    private static final Map<String, EntityObjectEnum> createEnumsMap() {
        Map<String, EntityObjectEnum> map = new HashMap<>();
        map.put("entity", EntityObjectEnum.ENTITY);
        return map;
    }
    
    
    public enum EntityObjectEnum {

        ENTITY("entity"),;

        private final String value;

        private EntityObjectEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

