/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import net.nova.api.utils.Utils;


public class EntityPaymentInstructions {
    /**
     * Object type identifier.
     */
    @JsonProperty("object")
    private EntityPaymentInstructionsObject object;

    /**
     * Whether this object exists in live mode (`true`) or test mode (`false`).
     */
    @JsonProperty("livemode")
    private boolean livemode;

    /**
     * ID of the entity
     */
    @JsonProperty("entity")
    private String entity;


    @JsonProperty("payment_instructions")
    private PaymentInstructionsList paymentInstructions;

    @JsonCreator
    public EntityPaymentInstructions(
            @JsonProperty("object") @Nonnull EntityPaymentInstructionsObject object,
            @JsonProperty("livemode") boolean livemode,
            @JsonProperty("entity") @Nonnull String entity,
            @JsonProperty("payment_instructions") @Nonnull PaymentInstructionsList paymentInstructions) {
        this.object = Optional.ofNullable(object)
            .orElseThrow(() -> new IllegalArgumentException("object cannot be null"));
        this.livemode = livemode;
        this.entity = Optional.ofNullable(entity)
            .orElseThrow(() -> new IllegalArgumentException("entity cannot be null"));
        this.paymentInstructions = Optional.ofNullable(paymentInstructions)
            .orElseThrow(() -> new IllegalArgumentException("paymentInstructions cannot be null"));
    }

    /**
     * Object type identifier.
     */
    public EntityPaymentInstructionsObject object() {
        return this.object;
    }

    /**
     * Whether this object exists in live mode (`true`) or test mode (`false`).
     */
    public boolean livemode() {
        return this.livemode;
    }

    /**
     * ID of the entity
     */
    public String entity() {
        return this.entity;
    }

    public PaymentInstructionsList paymentInstructions() {
        return this.paymentInstructions;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Object type identifier.
     */
    public EntityPaymentInstructions withObject(@Nonnull EntityPaymentInstructionsObject object) {
        this.object = Utils.checkNotNull(object, "object");
        return this;
    }


    /**
     * Whether this object exists in live mode (`true`) or test mode (`false`).
     */
    public EntityPaymentInstructions withLivemode(boolean livemode) {
        this.livemode = livemode;
        return this;
    }


    /**
     * ID of the entity
     */
    public EntityPaymentInstructions withEntity(@Nonnull String entity) {
        this.entity = Utils.checkNotNull(entity, "entity");
        return this;
    }


    public EntityPaymentInstructions withPaymentInstructions(@Nonnull PaymentInstructionsList paymentInstructions) {
        this.paymentInstructions = Utils.checkNotNull(paymentInstructions, "paymentInstructions");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EntityPaymentInstructions other = (EntityPaymentInstructions) o;
        return 
            Utils.enhancedDeepEquals(this.object, other.object) &&
            Utils.enhancedDeepEquals(this.livemode, other.livemode) &&
            Utils.enhancedDeepEquals(this.entity, other.entity) &&
            Utils.enhancedDeepEquals(this.paymentInstructions, other.paymentInstructions);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            object, livemode, entity,
            paymentInstructions);
    }
    
    @Override
    public String toString() {
        return Utils.toString(EntityPaymentInstructions.class,
                "object", object,
                "livemode", livemode,
                "entity", entity,
                "paymentInstructions", paymentInstructions);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private EntityPaymentInstructionsObject object;

        private boolean livemode;

        private String entity;

        private PaymentInstructionsList paymentInstructions;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Object type identifier.
         */
        public Builder object(@Nonnull EntityPaymentInstructionsObject object) {
            this.object = Utils.checkNotNull(object, "object");
            return this;
        }

        /**
         * Whether this object exists in live mode (`true`) or test mode (`false`).
         */
        public Builder livemode(boolean livemode) {
            this.livemode = livemode;
            return this;
        }

        /**
         * ID of the entity
         */
        public Builder entity(@Nonnull String entity) {
            this.entity = Utils.checkNotNull(entity, "entity");
            return this;
        }

        public Builder paymentInstructions(@Nonnull PaymentInstructionsList paymentInstructions) {
            this.paymentInstructions = Utils.checkNotNull(paymentInstructions, "paymentInstructions");
            return this;
        }

        public EntityPaymentInstructions build() {
            return new EntityPaymentInstructions(
                object, livemode, entity,
                paymentInstructions);
        }

    }
}
