/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import net.nova.api.utils.Utils;


public class EntityPaymentInstructionsInput {
    /**
     * ID of the entity
     */
    @JsonProperty("entity")
    private String entity;


    @JsonProperty("payment_instructions")
    private List<PaymentInstructionsInput> paymentInstructions;

    @JsonCreator
    public EntityPaymentInstructionsInput(
            @JsonProperty("entity") @Nonnull String entity,
            @JsonProperty("payment_instructions") @Nonnull List<PaymentInstructionsInput> paymentInstructions) {
        this.entity = Optional.ofNullable(entity)
            .orElseThrow(() -> new IllegalArgumentException("entity cannot be null"));
        this.paymentInstructions = Optional.ofNullable(paymentInstructions)
            .orElseThrow(() -> new IllegalArgumentException("paymentInstructions cannot be null"));
    }

    /**
     * ID of the entity
     */
    public String entity() {
        return this.entity;
    }

    public List<PaymentInstructionsInput> paymentInstructions() {
        return this.paymentInstructions;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * ID of the entity
     */
    public EntityPaymentInstructionsInput withEntity(@Nonnull String entity) {
        this.entity = Utils.checkNotNull(entity, "entity");
        return this;
    }


    public EntityPaymentInstructionsInput withPaymentInstructions(@Nonnull List<PaymentInstructionsInput> paymentInstructions) {
        this.paymentInstructions = Utils.checkNotNull(paymentInstructions, "paymentInstructions");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EntityPaymentInstructionsInput other = (EntityPaymentInstructionsInput) o;
        return 
            Utils.enhancedDeepEquals(this.entity, other.entity) &&
            Utils.enhancedDeepEquals(this.paymentInstructions, other.paymentInstructions);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            entity, paymentInstructions);
    }
    
    @Override
    public String toString() {
        return Utils.toString(EntityPaymentInstructionsInput.class,
                "entity", entity,
                "paymentInstructions", paymentInstructions);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String entity;

        private List<PaymentInstructionsInput> paymentInstructions;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * ID of the entity
         */
        public Builder entity(@Nonnull String entity) {
            this.entity = Utils.checkNotNull(entity, "entity");
            return this;
        }

        public Builder paymentInstructions(@Nonnull List<PaymentInstructionsInput> paymentInstructions) {
            this.paymentInstructions = Utils.checkNotNull(paymentInstructions, "paymentInstructions");
            return this;
        }

        public EntityPaymentInstructionsInput build() {
            return new EntityPaymentInstructionsInput(
                entity, paymentInstructions);
        }

    }
}
