/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * EntityPaymentInstructionsObject
 * 
 * <p>Object type identifier.
 */
public class EntityPaymentInstructionsObject {

    public static final EntityPaymentInstructionsObject ENTITY_PAYMENT_INSTRUCTIONS = new EntityPaymentInstructionsObject("entity_payment_instructions");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, EntityPaymentInstructionsObject> values = createValuesMap();
    private static final Map<String, EntityPaymentInstructionsObjectEnum> enums = createEnumsMap();

    private final String value;

    private EntityPaymentInstructionsObject(String value) {
        this.value = value;
    }

    /**
     * Returns a EntityPaymentInstructionsObject with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as EntityPaymentInstructionsObject
     */ 
    @JsonCreator
    public static EntityPaymentInstructionsObject of(String value) {
        synchronized (EntityPaymentInstructionsObject.class) {
            return values.computeIfAbsent(value, v -> new EntityPaymentInstructionsObject(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<EntityPaymentInstructionsObjectEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        EntityPaymentInstructionsObject other = (EntityPaymentInstructionsObject) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "EntityPaymentInstructionsObject [value=" + value + "]";
    }

    // return an array just like an enum
    public static EntityPaymentInstructionsObject[] values() {
        synchronized (EntityPaymentInstructionsObject.class) {
            return values.values().toArray(new EntityPaymentInstructionsObject[] {});
        }
    }

    private static final Map<String, EntityPaymentInstructionsObject> createValuesMap() {
        Map<String, EntityPaymentInstructionsObject> map = new LinkedHashMap<>();
        map.put("entity_payment_instructions", ENTITY_PAYMENT_INSTRUCTIONS);
        return map;
    }

    private static final Map<String, EntityPaymentInstructionsObjectEnum> createEnumsMap() {
        Map<String, EntityPaymentInstructionsObjectEnum> map = new HashMap<>();
        map.put("entity_payment_instructions", EntityPaymentInstructionsObjectEnum.ENTITY_PAYMENT_INSTRUCTIONS);
        return map;
    }
    
    
    public enum EntityPaymentInstructionsObjectEnum {

        ENTITY_PAYMENT_INSTRUCTIONS("entity_payment_instructions"),;

        private final String value;

        private EntityPaymentInstructionsObjectEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

