/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * Error
 * 
 * <p>Machine-readable OAuth error code (RFC 6749 §5.2).
 */
public class Error {

    public static final Error INVALID_REQUEST = new Error("invalid_request");
    public static final Error INVALID_CLIENT = new Error("invalid_client");
    public static final Error INVALID_GRANT = new Error("invalid_grant");
    public static final Error UNAUTHORIZED_CLIENT = new Error("unauthorized_client");
    public static final Error UNSUPPORTED_GRANT_TYPE = new Error("unsupported_grant_type");
    public static final Error INVALID_SCOPE = new Error("invalid_scope");
    public static final Error SERVER_ERROR = new Error("server_error");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, Error> values = createValuesMap();
    private static final Map<String, ErrorEnum> enums = createEnumsMap();

    private final String value;

    private Error(String value) {
        this.value = value;
    }

    /**
     * Returns a Error with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as Error
     */ 
    @JsonCreator
    public static Error of(String value) {
        synchronized (Error.class) {
            return values.computeIfAbsent(value, v -> new Error(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<ErrorEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Error other = (Error) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "Error [value=" + value + "]";
    }

    // return an array just like an enum
    public static Error[] values() {
        synchronized (Error.class) {
            return values.values().toArray(new Error[] {});
        }
    }

    private static final Map<String, Error> createValuesMap() {
        Map<String, Error> map = new LinkedHashMap<>();
        map.put("invalid_request", INVALID_REQUEST);
        map.put("invalid_client", INVALID_CLIENT);
        map.put("invalid_grant", INVALID_GRANT);
        map.put("unauthorized_client", UNAUTHORIZED_CLIENT);
        map.put("unsupported_grant_type", UNSUPPORTED_GRANT_TYPE);
        map.put("invalid_scope", INVALID_SCOPE);
        map.put("server_error", SERVER_ERROR);
        return map;
    }

    private static final Map<String, ErrorEnum> createEnumsMap() {
        Map<String, ErrorEnum> map = new HashMap<>();
        map.put("invalid_request", ErrorEnum.INVALID_REQUEST);
        map.put("invalid_client", ErrorEnum.INVALID_CLIENT);
        map.put("invalid_grant", ErrorEnum.INVALID_GRANT);
        map.put("unauthorized_client", ErrorEnum.UNAUTHORIZED_CLIENT);
        map.put("unsupported_grant_type", ErrorEnum.UNSUPPORTED_GRANT_TYPE);
        map.put("invalid_scope", ErrorEnum.INVALID_SCOPE);
        map.put("server_error", ErrorEnum.SERVER_ERROR);
        return map;
    }
    
    
    public enum ErrorEnum {

        INVALID_REQUEST("invalid_request"),
        INVALID_CLIENT("invalid_client"),
        INVALID_GRANT("invalid_grant"),
        UNAUTHORIZED_CLIENT("unauthorized_client"),
        UNSUPPORTED_GRANT_TYPE("unsupported_grant_type"),
        INVALID_SCOPE("invalid_scope"),
        SERVER_ERROR("server_error"),;

        private final String value;

        private ErrorEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

