/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * ErrorObject
 * 
 * <p>Object type identifier.
 */
public class ErrorObject {

    public static final ErrorObject ERROR = new ErrorObject("error");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, ErrorObject> values = createValuesMap();
    private static final Map<String, ErrorObjectEnum> enums = createEnumsMap();

    private final String value;

    private ErrorObject(String value) {
        this.value = value;
    }

    /**
     * Returns a ErrorObject with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as ErrorObject
     */ 
    @JsonCreator
    public static ErrorObject of(String value) {
        synchronized (ErrorObject.class) {
            return values.computeIfAbsent(value, v -> new ErrorObject(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<ErrorObjectEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        ErrorObject other = (ErrorObject) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "ErrorObject [value=" + value + "]";
    }

    // return an array just like an enum
    public static ErrorObject[] values() {
        synchronized (ErrorObject.class) {
            return values.values().toArray(new ErrorObject[] {});
        }
    }

    private static final Map<String, ErrorObject> createValuesMap() {
        Map<String, ErrorObject> map = new LinkedHashMap<>();
        map.put("error", ERROR);
        return map;
    }

    private static final Map<String, ErrorObjectEnum> createEnumsMap() {
        Map<String, ErrorObjectEnum> map = new HashMap<>();
        map.put("error", ErrorObjectEnum.ERROR);
        return map;
    }
    
    
    public enum ErrorObjectEnum {

        ERROR("error"),;

        private final String value;

        private ErrorObjectEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

