/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * GrantType
 * 
 * <p>Must be `client_credentials`.
 */
public enum GrantType {
    CLIENT_CREDENTIALS("client_credentials");

    @JsonValue
    private final String value;

    GrantType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<GrantType> fromValue(String value) {
        for (GrantType o: GrantType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

