/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import net.nova.api.utils.Utils;

/**
 * InternationalWireInstructionsInput
 * 
 * <p>International wire instructions
 */
public class InternationalWireInstructionsInput implements PaymentInstructionsInput {
    /**
     * Name of the account holder, as registered with the bank.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("beneficiary_name")
    private String beneficiaryName;

    /**
     * Bank account number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("account_number")
    private String accountNumber;

    /**
     * Name of the bank.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("bank_name")
    private String bankName;

    /**
     * Bank branch code (e.g. sort code, IFSC, BSB, etc.). Primarily used for international wires.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("branch_code")
    private String branchCode;

    /**
     * Name of the intermediary bank.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("intermediary_party_name")
    private String intermediaryPartyName;

    /**
     * SWIFT/BIC code of the intermediary bank.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("intermediary_party_swift_code")
    private String intermediaryPartySwiftCode;

    /**
     * Payment instructions line 1.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("originator_to_beneficiary_instructions_line1")
    private String originatorToBeneficiaryInstructionsLine1;

    /**
     * Payment instructions line 2.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("originator_to_beneficiary_instructions_line2")
    private String originatorToBeneficiaryInstructionsLine2;

    /**
     * Payment instructions line 3.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("originator_to_beneficiary_instructions_line3")
    private String originatorToBeneficiaryInstructionsLine3;


    @JsonProperty("type")
    private InternationalWireInstructionsInputType type;

    /**
     * SWIFT/BIC code.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("swift_code")
    private String swiftCode;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("address")
    private WireAddress address;

    @JsonCreator
    public InternationalWireInstructionsInput(
            @JsonProperty("beneficiary_name") @Nullable String beneficiaryName,
            @JsonProperty("account_number") @Nullable String accountNumber,
            @JsonProperty("bank_name") @Nullable String bankName,
            @JsonProperty("branch_code") @Nullable String branchCode,
            @JsonProperty("intermediary_party_name") @Nullable String intermediaryPartyName,
            @JsonProperty("intermediary_party_swift_code") @Nullable String intermediaryPartySwiftCode,
            @JsonProperty("originator_to_beneficiary_instructions_line1") @Nullable String originatorToBeneficiaryInstructionsLine1,
            @JsonProperty("originator_to_beneficiary_instructions_line2") @Nullable String originatorToBeneficiaryInstructionsLine2,
            @JsonProperty("originator_to_beneficiary_instructions_line3") @Nullable String originatorToBeneficiaryInstructionsLine3,
            @JsonProperty("type") @Nonnull InternationalWireInstructionsInputType type,
            @JsonProperty("swift_code") @Nullable String swiftCode,
            @JsonProperty("address") @Nullable WireAddress address) {
        this.beneficiaryName = beneficiaryName;
        this.accountNumber = accountNumber;
        this.bankName = bankName;
        this.branchCode = branchCode;
        this.intermediaryPartyName = intermediaryPartyName;
        this.intermediaryPartySwiftCode = intermediaryPartySwiftCode;
        this.originatorToBeneficiaryInstructionsLine1 = originatorToBeneficiaryInstructionsLine1;
        this.originatorToBeneficiaryInstructionsLine2 = originatorToBeneficiaryInstructionsLine2;
        this.originatorToBeneficiaryInstructionsLine3 = originatorToBeneficiaryInstructionsLine3;
        this.type = Optional.ofNullable(type)
            .orElseThrow(() -> new IllegalArgumentException("type cannot be null"));
        this.swiftCode = swiftCode;
        this.address = address;
    }
    
    public InternationalWireInstructionsInput(
            @Nonnull InternationalWireInstructionsInputType type) {
        this(null, null, null,
            null, null, null,
            null, null, null,
            type, null, null);
    }

    /**
     * Name of the account holder, as registered with the bank.
     */
    public Optional<String> beneficiaryName() {
        return Optional.ofNullable(this.beneficiaryName);
    }

    /**
     * Bank account number.
     */
    public Optional<String> accountNumber() {
        return Optional.ofNullable(this.accountNumber);
    }

    /**
     * Name of the bank.
     */
    public Optional<String> bankName() {
        return Optional.ofNullable(this.bankName);
    }

    /**
     * Bank branch code (e.g. sort code, IFSC, BSB, etc.). Primarily used for international wires.
     */
    public Optional<String> branchCode() {
        return Optional.ofNullable(this.branchCode);
    }

    /**
     * Name of the intermediary bank.
     */
    public Optional<String> intermediaryPartyName() {
        return Optional.ofNullable(this.intermediaryPartyName);
    }

    /**
     * SWIFT/BIC code of the intermediary bank.
     */
    public Optional<String> intermediaryPartySwiftCode() {
        return Optional.ofNullable(this.intermediaryPartySwiftCode);
    }

    /**
     * Payment instructions line 1.
     */
    public Optional<String> originatorToBeneficiaryInstructionsLine1() {
        return Optional.ofNullable(this.originatorToBeneficiaryInstructionsLine1);
    }

    /**
     * Payment instructions line 2.
     */
    public Optional<String> originatorToBeneficiaryInstructionsLine2() {
        return Optional.ofNullable(this.originatorToBeneficiaryInstructionsLine2);
    }

    /**
     * Payment instructions line 3.
     */
    public Optional<String> originatorToBeneficiaryInstructionsLine3() {
        return Optional.ofNullable(this.originatorToBeneficiaryInstructionsLine3);
    }

    @Override
    public String type() {
        return Utils.discriminatorToString(type);
    }

    /**
     * SWIFT/BIC code.
     */
    public Optional<String> swiftCode() {
        return Optional.ofNullable(this.swiftCode);
    }

    public Optional<WireAddress> address() {
        return Optional.ofNullable(this.address);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Name of the account holder, as registered with the bank.
     */
    public InternationalWireInstructionsInput withBeneficiaryName(@Nullable String beneficiaryName) {
        this.beneficiaryName = beneficiaryName;
        return this;
    }


    /**
     * Bank account number.
     */
    public InternationalWireInstructionsInput withAccountNumber(@Nullable String accountNumber) {
        this.accountNumber = accountNumber;
        return this;
    }


    /**
     * Name of the bank.
     */
    public InternationalWireInstructionsInput withBankName(@Nullable String bankName) {
        this.bankName = bankName;
        return this;
    }


    /**
     * Bank branch code (e.g. sort code, IFSC, BSB, etc.). Primarily used for international wires.
     */
    public InternationalWireInstructionsInput withBranchCode(@Nullable String branchCode) {
        this.branchCode = branchCode;
        return this;
    }


    /**
     * Name of the intermediary bank.
     */
    public InternationalWireInstructionsInput withIntermediaryPartyName(@Nullable String intermediaryPartyName) {
        this.intermediaryPartyName = intermediaryPartyName;
        return this;
    }


    /**
     * SWIFT/BIC code of the intermediary bank.
     */
    public InternationalWireInstructionsInput withIntermediaryPartySwiftCode(@Nullable String intermediaryPartySwiftCode) {
        this.intermediaryPartySwiftCode = intermediaryPartySwiftCode;
        return this;
    }


    /**
     * Payment instructions line 1.
     */
    public InternationalWireInstructionsInput withOriginatorToBeneficiaryInstructionsLine1(@Nullable String originatorToBeneficiaryInstructionsLine1) {
        this.originatorToBeneficiaryInstructionsLine1 = originatorToBeneficiaryInstructionsLine1;
        return this;
    }


    /**
     * Payment instructions line 2.
     */
    public InternationalWireInstructionsInput withOriginatorToBeneficiaryInstructionsLine2(@Nullable String originatorToBeneficiaryInstructionsLine2) {
        this.originatorToBeneficiaryInstructionsLine2 = originatorToBeneficiaryInstructionsLine2;
        return this;
    }


    /**
     * Payment instructions line 3.
     */
    public InternationalWireInstructionsInput withOriginatorToBeneficiaryInstructionsLine3(@Nullable String originatorToBeneficiaryInstructionsLine3) {
        this.originatorToBeneficiaryInstructionsLine3 = originatorToBeneficiaryInstructionsLine3;
        return this;
    }


    public InternationalWireInstructionsInput withType(@Nonnull InternationalWireInstructionsInputType type) {
        this.type = Utils.checkNotNull(type, "type");
        return this;
    }


    /**
     * SWIFT/BIC code.
     */
    public InternationalWireInstructionsInput withSwiftCode(@Nullable String swiftCode) {
        this.swiftCode = swiftCode;
        return this;
    }


    public InternationalWireInstructionsInput withAddress(@Nullable WireAddress address) {
        this.address = address;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InternationalWireInstructionsInput other = (InternationalWireInstructionsInput) o;
        return 
            Utils.enhancedDeepEquals(this.beneficiaryName, other.beneficiaryName) &&
            Utils.enhancedDeepEquals(this.accountNumber, other.accountNumber) &&
            Utils.enhancedDeepEquals(this.bankName, other.bankName) &&
            Utils.enhancedDeepEquals(this.branchCode, other.branchCode) &&
            Utils.enhancedDeepEquals(this.intermediaryPartyName, other.intermediaryPartyName) &&
            Utils.enhancedDeepEquals(this.intermediaryPartySwiftCode, other.intermediaryPartySwiftCode) &&
            Utils.enhancedDeepEquals(this.originatorToBeneficiaryInstructionsLine1, other.originatorToBeneficiaryInstructionsLine1) &&
            Utils.enhancedDeepEquals(this.originatorToBeneficiaryInstructionsLine2, other.originatorToBeneficiaryInstructionsLine2) &&
            Utils.enhancedDeepEquals(this.originatorToBeneficiaryInstructionsLine3, other.originatorToBeneficiaryInstructionsLine3) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.swiftCode, other.swiftCode) &&
            Utils.enhancedDeepEquals(this.address, other.address);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            beneficiaryName, accountNumber, bankName,
            branchCode, intermediaryPartyName, intermediaryPartySwiftCode,
            originatorToBeneficiaryInstructionsLine1, originatorToBeneficiaryInstructionsLine2, originatorToBeneficiaryInstructionsLine3,
            type, swiftCode, address);
    }
    
    @Override
    public String toString() {
        return Utils.toString(InternationalWireInstructionsInput.class,
                "beneficiaryName", beneficiaryName,
                "accountNumber", accountNumber,
                "bankName", bankName,
                "branchCode", branchCode,
                "intermediaryPartyName", intermediaryPartyName,
                "intermediaryPartySwiftCode", intermediaryPartySwiftCode,
                "originatorToBeneficiaryInstructionsLine1", originatorToBeneficiaryInstructionsLine1,
                "originatorToBeneficiaryInstructionsLine2", originatorToBeneficiaryInstructionsLine2,
                "originatorToBeneficiaryInstructionsLine3", originatorToBeneficiaryInstructionsLine3,
                "type", type,
                "swiftCode", swiftCode,
                "address", address);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String beneficiaryName;

        private String accountNumber;

        private String bankName;

        private String branchCode;

        private String intermediaryPartyName;

        private String intermediaryPartySwiftCode;

        private String originatorToBeneficiaryInstructionsLine1;

        private String originatorToBeneficiaryInstructionsLine2;

        private String originatorToBeneficiaryInstructionsLine3;

        private InternationalWireInstructionsInputType type;

        private String swiftCode;

        private WireAddress address;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Name of the account holder, as registered with the bank.
         */
        public Builder beneficiaryName(@Nullable String beneficiaryName) {
            this.beneficiaryName = beneficiaryName;
            return this;
        }

        /**
         * Bank account number.
         */
        public Builder accountNumber(@Nullable String accountNumber) {
            this.accountNumber = accountNumber;
            return this;
        }

        /**
         * Name of the bank.
         */
        public Builder bankName(@Nullable String bankName) {
            this.bankName = bankName;
            return this;
        }

        /**
         * Bank branch code (e.g. sort code, IFSC, BSB, etc.). Primarily used for international wires.
         */
        public Builder branchCode(@Nullable String branchCode) {
            this.branchCode = branchCode;
            return this;
        }

        /**
         * Name of the intermediary bank.
         */
        public Builder intermediaryPartyName(@Nullable String intermediaryPartyName) {
            this.intermediaryPartyName = intermediaryPartyName;
            return this;
        }

        /**
         * SWIFT/BIC code of the intermediary bank.
         */
        public Builder intermediaryPartySwiftCode(@Nullable String intermediaryPartySwiftCode) {
            this.intermediaryPartySwiftCode = intermediaryPartySwiftCode;
            return this;
        }

        /**
         * Payment instructions line 1.
         */
        public Builder originatorToBeneficiaryInstructionsLine1(@Nullable String originatorToBeneficiaryInstructionsLine1) {
            this.originatorToBeneficiaryInstructionsLine1 = originatorToBeneficiaryInstructionsLine1;
            return this;
        }

        /**
         * Payment instructions line 2.
         */
        public Builder originatorToBeneficiaryInstructionsLine2(@Nullable String originatorToBeneficiaryInstructionsLine2) {
            this.originatorToBeneficiaryInstructionsLine2 = originatorToBeneficiaryInstructionsLine2;
            return this;
        }

        /**
         * Payment instructions line 3.
         */
        public Builder originatorToBeneficiaryInstructionsLine3(@Nullable String originatorToBeneficiaryInstructionsLine3) {
            this.originatorToBeneficiaryInstructionsLine3 = originatorToBeneficiaryInstructionsLine3;
            return this;
        }

        public Builder type(@Nonnull InternationalWireInstructionsInputType type) {
            this.type = Utils.checkNotNull(type, "type");
            return this;
        }

        /**
         * SWIFT/BIC code.
         */
        public Builder swiftCode(@Nullable String swiftCode) {
            this.swiftCode = swiftCode;
            return this;
        }

        public Builder address(@Nullable WireAddress address) {
            this.address = address;
            return this;
        }

        public InternationalWireInstructionsInput build() {
            return new InternationalWireInstructionsInput(
                beneficiaryName, accountNumber, bankName,
                branchCode, intermediaryPartyName, intermediaryPartySwiftCode,
                originatorToBeneficiaryInstructionsLine1, originatorToBeneficiaryInstructionsLine2, originatorToBeneficiaryInstructionsLine3,
                type, swiftCode, address);
        }

    }
}
