/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum InternationalWireInstructionsInputType {
    INTERNATIONAL_WIRE("international_wire");

    @JsonValue
    private final String value;

    InternationalWireInstructionsInputType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<InternationalWireInstructionsInputType> fromValue(String value) {
        for (InternationalWireInstructionsInputType o: InternationalWireInstructionsInputType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

