/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import net.nova.api.utils.Utils;


public class OAuthTokenResponse {
    /**
     * Bearer token. Send as `Authorization: Bearer &lt;access_token&gt;` on authenticated requests.
     */
    @JsonProperty("access_token")
    private String accessToken;


    @JsonProperty("token_type")
    private TokenType tokenType;

    /**
     * Lifetime of the token, in seconds. Re-exchange credentials before expiry.
     */
    @JsonProperty("expires_in")
    private long expiresIn;

    /**
     * Space-separated list of scopes the token was granted.
     */
    @JsonProperty("scope")
    private String scope;

    @JsonCreator
    public OAuthTokenResponse(
            @JsonProperty("access_token") @Nonnull String accessToken,
            @JsonProperty("token_type") @Nonnull TokenType tokenType,
            @JsonProperty("expires_in") long expiresIn,
            @JsonProperty("scope") @Nonnull String scope) {
        this.accessToken = Optional.ofNullable(accessToken)
            .orElseThrow(() -> new IllegalArgumentException("accessToken cannot be null"));
        this.tokenType = Optional.ofNullable(tokenType)
            .orElseThrow(() -> new IllegalArgumentException("tokenType cannot be null"));
        this.expiresIn = expiresIn;
        this.scope = Optional.ofNullable(scope)
            .orElseThrow(() -> new IllegalArgumentException("scope cannot be null"));
    }

    /**
     * Bearer token. Send as `Authorization: Bearer &lt;access_token&gt;` on authenticated requests.
     */
    public String accessToken() {
        return this.accessToken;
    }

    public TokenType tokenType() {
        return this.tokenType;
    }

    /**
     * Lifetime of the token, in seconds. Re-exchange credentials before expiry.
     */
    public long expiresIn() {
        return this.expiresIn;
    }

    /**
     * Space-separated list of scopes the token was granted.
     */
    public String scope() {
        return this.scope;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Bearer token. Send as `Authorization: Bearer &lt;access_token&gt;` on authenticated requests.
     */
    public OAuthTokenResponse withAccessToken(@Nonnull String accessToken) {
        this.accessToken = Utils.checkNotNull(accessToken, "accessToken");
        return this;
    }


    public OAuthTokenResponse withTokenType(@Nonnull TokenType tokenType) {
        this.tokenType = Utils.checkNotNull(tokenType, "tokenType");
        return this;
    }


    /**
     * Lifetime of the token, in seconds. Re-exchange credentials before expiry.
     */
    public OAuthTokenResponse withExpiresIn(long expiresIn) {
        this.expiresIn = expiresIn;
        return this;
    }


    /**
     * Space-separated list of scopes the token was granted.
     */
    public OAuthTokenResponse withScope(@Nonnull String scope) {
        this.scope = Utils.checkNotNull(scope, "scope");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OAuthTokenResponse other = (OAuthTokenResponse) o;
        return 
            Utils.enhancedDeepEquals(this.accessToken, other.accessToken) &&
            Utils.enhancedDeepEquals(this.tokenType, other.tokenType) &&
            Utils.enhancedDeepEquals(this.expiresIn, other.expiresIn) &&
            Utils.enhancedDeepEquals(this.scope, other.scope);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            accessToken, tokenType, expiresIn,
            scope);
    }
    
    @Override
    public String toString() {
        return Utils.toString(OAuthTokenResponse.class,
                "accessToken", accessToken,
                "tokenType", tokenType,
                "expiresIn", expiresIn,
                "scope", scope);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String accessToken;

        private TokenType tokenType;

        private long expiresIn;

        private String scope;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Bearer token. Send as `Authorization: Bearer &lt;access_token&gt;` on authenticated requests.
         */
        public Builder accessToken(@Nonnull String accessToken) {
            this.accessToken = Utils.checkNotNull(accessToken, "accessToken");
            return this;
        }

        public Builder tokenType(@Nonnull TokenType tokenType) {
            this.tokenType = Utils.checkNotNull(tokenType, "tokenType");
            return this;
        }

        /**
         * Lifetime of the token, in seconds. Re-exchange credentials before expiry.
         */
        public Builder expiresIn(long expiresIn) {
            this.expiresIn = expiresIn;
            return this;
        }

        /**
         * Space-separated list of scopes the token was granted.
         */
        public Builder scope(@Nonnull String scope) {
            this.scope = Utils.checkNotNull(scope, "scope");
            return this;
        }

        public OAuthTokenResponse build() {
            return new OAuthTokenResponse(
                accessToken, tokenType, expiresIn,
                scope);
        }

    }
}
