/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import net.nova.api.utils.SpeakeasyMetadata;
import net.nova.api.utils.Utils;


public class OAuthTokenRequest {
    /**
     * Must be `client_credentials`.
     */
    @JsonProperty("grant_type")
    @SpeakeasyMetadata("form:name=grant_type")
    private GrantType grantType;

    /**
     * Client identifier. Required unless provided via HTTP Basic auth in the `Authorization` header.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("client_id")
    @SpeakeasyMetadata("form:name=client_id")
    private String clientId;

    /**
     * Client secret. Required unless provided via HTTP Basic auth in the `Authorization` header.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("client_secret")
    @SpeakeasyMetadata("form:name=client_secret")
    private String clientSecret;

    /**
     * Space-separated list of requested scopes. Omit to request all scopes granted to the client.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("scope")
    @SpeakeasyMetadata("form:name=scope")
    private String scope;

    @JsonCreator
    public OAuthTokenRequest(
            @JsonProperty("grant_type") @Nonnull GrantType grantType,
            @JsonProperty("client_id") @Nullable String clientId,
            @JsonProperty("client_secret") @Nullable String clientSecret,
            @JsonProperty("scope") @Nullable String scope) {
        this.grantType = Optional.ofNullable(grantType)
            .orElseThrow(() -> new IllegalArgumentException("grantType cannot be null"));
        this.clientId = clientId;
        this.clientSecret = clientSecret;
        this.scope = scope;
    }
    
    public OAuthTokenRequest(
            @Nonnull GrantType grantType) {
        this(grantType, null, null,
            null);
    }

    /**
     * Must be `client_credentials`.
     */
    public GrantType grantType() {
        return this.grantType;
    }

    /**
     * Client identifier. Required unless provided via HTTP Basic auth in the `Authorization` header.
     */
    public Optional<String> clientId() {
        return Optional.ofNullable(this.clientId);
    }

    /**
     * Client secret. Required unless provided via HTTP Basic auth in the `Authorization` header.
     */
    public Optional<String> clientSecret() {
        return Optional.ofNullable(this.clientSecret);
    }

    /**
     * Space-separated list of requested scopes. Omit to request all scopes granted to the client.
     */
    public Optional<String> scope() {
        return Optional.ofNullable(this.scope);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Must be `client_credentials`.
     */
    public OAuthTokenRequest withGrantType(@Nonnull GrantType grantType) {
        this.grantType = Utils.checkNotNull(grantType, "grantType");
        return this;
    }


    /**
     * Client identifier. Required unless provided via HTTP Basic auth in the `Authorization` header.
     */
    public OAuthTokenRequest withClientId(@Nullable String clientId) {
        this.clientId = clientId;
        return this;
    }


    /**
     * Client secret. Required unless provided via HTTP Basic auth in the `Authorization` header.
     */
    public OAuthTokenRequest withClientSecret(@Nullable String clientSecret) {
        this.clientSecret = clientSecret;
        return this;
    }


    /**
     * Space-separated list of requested scopes. Omit to request all scopes granted to the client.
     */
    public OAuthTokenRequest withScope(@Nullable String scope) {
        this.scope = scope;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OAuthTokenRequest other = (OAuthTokenRequest) o;
        return 
            Utils.enhancedDeepEquals(this.grantType, other.grantType) &&
            Utils.enhancedDeepEquals(this.clientId, other.clientId) &&
            Utils.enhancedDeepEquals(this.clientSecret, other.clientSecret) &&
            Utils.enhancedDeepEquals(this.scope, other.scope);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            grantType, clientId, clientSecret,
            scope);
    }
    
    @Override
    public String toString() {
        return Utils.toString(OAuthTokenRequest.class,
                "grantType", grantType,
                "clientId", clientId,
                "clientSecret", clientSecret,
                "scope", scope);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private GrantType grantType;

        private String clientId;

        private String clientSecret;

        private String scope;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Must be `client_credentials`.
         */
        public Builder grantType(@Nonnull GrantType grantType) {
            this.grantType = Utils.checkNotNull(grantType, "grantType");
            return this;
        }

        /**
         * Client identifier. Required unless provided via HTTP Basic auth in the `Authorization` header.
         */
        public Builder clientId(@Nullable String clientId) {
            this.clientId = clientId;
            return this;
        }

        /**
         * Client secret. Required unless provided via HTTP Basic auth in the `Authorization` header.
         */
        public Builder clientSecret(@Nullable String clientSecret) {
            this.clientSecret = clientSecret;
            return this;
        }

        /**
         * Space-separated list of requested scopes. Omit to request all scopes granted to the client.
         */
        public Builder scope(@Nullable String scope) {
            this.scope = scope;
            return this;
        }

        public OAuthTokenRequest build() {
            return new OAuthTokenRequest(
                grantType, clientId, clientSecret,
                scope);
        }

    }
}
