/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * PaymentInstructionsObject
 * 
 * <p>Object type identifier.
 */
public class PaymentInstructionsObject {

    public static final PaymentInstructionsObject PAYMENT_INSTRUCTIONS = new PaymentInstructionsObject("payment_instructions");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, PaymentInstructionsObject> values = createValuesMap();
    private static final Map<String, PaymentInstructionsObjectEnum> enums = createEnumsMap();

    private final String value;

    private PaymentInstructionsObject(String value) {
        this.value = value;
    }

    /**
     * Returns a PaymentInstructionsObject with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as PaymentInstructionsObject
     */ 
    @JsonCreator
    public static PaymentInstructionsObject of(String value) {
        synchronized (PaymentInstructionsObject.class) {
            return values.computeIfAbsent(value, v -> new PaymentInstructionsObject(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<PaymentInstructionsObjectEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        PaymentInstructionsObject other = (PaymentInstructionsObject) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "PaymentInstructionsObject [value=" + value + "]";
    }

    // return an array just like an enum
    public static PaymentInstructionsObject[] values() {
        synchronized (PaymentInstructionsObject.class) {
            return values.values().toArray(new PaymentInstructionsObject[] {});
        }
    }

    private static final Map<String, PaymentInstructionsObject> createValuesMap() {
        Map<String, PaymentInstructionsObject> map = new LinkedHashMap<>();
        map.put("payment_instructions", PAYMENT_INSTRUCTIONS);
        return map;
    }

    private static final Map<String, PaymentInstructionsObjectEnum> createEnumsMap() {
        Map<String, PaymentInstructionsObjectEnum> map = new HashMap<>();
        map.put("payment_instructions", PaymentInstructionsObjectEnum.PAYMENT_INSTRUCTIONS);
        return map;
    }
    
    
    public enum PaymentInstructionsObjectEnum {

        PAYMENT_INSTRUCTIONS("payment_instructions"),;

        private final String value;

        private PaymentInstructionsObjectEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

