/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package net.nova.api.models.components;

import java.lang.IllegalArgumentException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import net.nova.api.utils.GenericTypeIdResolver;


public class PaymentInstructionsInputTypeIdResolver extends GenericTypeIdResolver<PaymentInstructionsInput> {

    public PaymentInstructionsInputTypeIdResolver() {
        super(UnknownPaymentInstructionsInput.class);
        initializeTypeMap();
    }

    private void initializeTypeMap() {
        registerType("ach", AchInstructionsInput.class);
        registerType("domestic_wire", DomesticWireInstructionsInput.class);
        registerType("international_wire", InternationalWireInstructionsInput.class);
    }

    @Override
    public String idFromValue(Object value) {
        if (value == null) {
            return null;
        }
        
        // Handle known types by checking if they implement the discriminator method
        if (value instanceof PaymentInstructionsInput) {
            PaymentInstructionsInput discriminated = (PaymentInstructionsInput) value;
            return discriminated.type();
        }
        
        throw new IllegalArgumentException("Unknown value type: " + value.getClass().getName());
    }

    @Override
    public String getDescForKnownTypeIds() {
        return "PaymentInstructionsInput type resolver";
    }

}