/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import net.nova.api.utils.Utils;


public class PaymentInstructionsList {
    /**
     * Object type identifier.
     */
    @JsonProperty("object")
    private PaymentInstructionsListObject object;

    /**
     * The page of items.
     */
    @JsonProperty("data")
    private List<PaymentInstructions> data;

    /**
     * Whether there are more items available after this page.
     */
    @JsonProperty("has_more")
    private boolean hasMore;

    /**
     * The URL for this list endpoint.
     */
    @JsonProperty("url")
    private String url;

    @JsonCreator
    public PaymentInstructionsList(
            @JsonProperty("object") @Nonnull PaymentInstructionsListObject object,
            @JsonProperty("data") @Nonnull List<PaymentInstructions> data,
            @JsonProperty("has_more") boolean hasMore,
            @JsonProperty("url") @Nonnull String url) {
        this.object = Optional.ofNullable(object)
            .orElseThrow(() -> new IllegalArgumentException("object cannot be null"));
        this.data = Optional.ofNullable(data)
            .orElseThrow(() -> new IllegalArgumentException("data cannot be null"));
        this.hasMore = hasMore;
        this.url = Optional.ofNullable(url)
            .orElseThrow(() -> new IllegalArgumentException("url cannot be null"));
    }

    /**
     * Object type identifier.
     */
    public PaymentInstructionsListObject object() {
        return this.object;
    }

    /**
     * The page of items.
     */
    public List<PaymentInstructions> data() {
        return this.data;
    }

    /**
     * Whether there are more items available after this page.
     */
    public boolean hasMore() {
        return this.hasMore;
    }

    /**
     * The URL for this list endpoint.
     */
    public String url() {
        return this.url;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Object type identifier.
     */
    public PaymentInstructionsList withObject(@Nonnull PaymentInstructionsListObject object) {
        this.object = Utils.checkNotNull(object, "object");
        return this;
    }


    /**
     * The page of items.
     */
    public PaymentInstructionsList withData(@Nonnull List<PaymentInstructions> data) {
        this.data = Utils.checkNotNull(data, "data");
        return this;
    }


    /**
     * Whether there are more items available after this page.
     */
    public PaymentInstructionsList withHasMore(boolean hasMore) {
        this.hasMore = hasMore;
        return this;
    }


    /**
     * The URL for this list endpoint.
     */
    public PaymentInstructionsList withUrl(@Nonnull String url) {
        this.url = Utils.checkNotNull(url, "url");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PaymentInstructionsList other = (PaymentInstructionsList) o;
        return 
            Utils.enhancedDeepEquals(this.object, other.object) &&
            Utils.enhancedDeepEquals(this.data, other.data) &&
            Utils.enhancedDeepEquals(this.hasMore, other.hasMore) &&
            Utils.enhancedDeepEquals(this.url, other.url);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            object, data, hasMore,
            url);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PaymentInstructionsList.class,
                "object", object,
                "data", data,
                "hasMore", hasMore,
                "url", url);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private PaymentInstructionsListObject object;

        private List<PaymentInstructions> data;

        private boolean hasMore;

        private String url;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Object type identifier.
         */
        public Builder object(@Nonnull PaymentInstructionsListObject object) {
            this.object = Utils.checkNotNull(object, "object");
            return this;
        }

        /**
         * The page of items.
         */
        public Builder data(@Nonnull List<PaymentInstructions> data) {
            this.data = Utils.checkNotNull(data, "data");
            return this;
        }

        /**
         * Whether there are more items available after this page.
         */
        public Builder hasMore(boolean hasMore) {
            this.hasMore = hasMore;
            return this;
        }

        /**
         * The URL for this list endpoint.
         */
        public Builder url(@Nonnull String url) {
            this.url = Utils.checkNotNull(url, "url");
            return this;
        }

        public PaymentInstructionsList build() {
            return new PaymentInstructionsList(
                object, data, hasMore,
                url);
        }

    }
}
