/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import net.nova.api.utils.Utils;


public class PaymentInstructions {
    /**
     * Object type identifier.
     */
    @JsonProperty("object")
    private PaymentInstructionsObject object;

    /**
     * Whether this object exists in live mode (`true`) or test mode (`false`).
     */
    @JsonProperty("livemode")
    private boolean livemode;

    /**
     * ID of the payment instructions
     */
    @JsonProperty("id")
    private String id;

    @JsonCreator
    public PaymentInstructions(
            @JsonProperty("object") @Nonnull PaymentInstructionsObject object,
            @JsonProperty("livemode") boolean livemode,
            @JsonProperty("id") @Nonnull String id) {
        this.object = Optional.ofNullable(object)
            .orElseThrow(() -> new IllegalArgumentException("object cannot be null"));
        this.livemode = livemode;
        this.id = Optional.ofNullable(id)
            .orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
    }

    /**
     * Object type identifier.
     */
    public PaymentInstructionsObject object() {
        return this.object;
    }

    /**
     * Whether this object exists in live mode (`true`) or test mode (`false`).
     */
    public boolean livemode() {
        return this.livemode;
    }

    /**
     * ID of the payment instructions
     */
    public String id() {
        return this.id;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Object type identifier.
     */
    public PaymentInstructions withObject(@Nonnull PaymentInstructionsObject object) {
        this.object = Utils.checkNotNull(object, "object");
        return this;
    }


    /**
     * Whether this object exists in live mode (`true`) or test mode (`false`).
     */
    public PaymentInstructions withLivemode(boolean livemode) {
        this.livemode = livemode;
        return this;
    }


    /**
     * ID of the payment instructions
     */
    public PaymentInstructions withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PaymentInstructions other = (PaymentInstructions) o;
        return 
            Utils.enhancedDeepEquals(this.object, other.object) &&
            Utils.enhancedDeepEquals(this.livemode, other.livemode) &&
            Utils.enhancedDeepEquals(this.id, other.id);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            object, livemode, id);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PaymentInstructions.class,
                "object", object,
                "livemode", livemode,
                "id", id);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private PaymentInstructionsObject object;

        private boolean livemode;

        private String id;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Object type identifier.
         */
        public Builder object(@Nonnull PaymentInstructionsObject object) {
            this.object = Utils.checkNotNull(object, "object");
            return this;
        }

        /**
         * Whether this object exists in live mode (`true`) or test mode (`false`).
         */
        public Builder livemode(boolean livemode) {
            this.livemode = livemode;
            return this;
        }

        /**
         * ID of the payment instructions
         */
        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        public PaymentInstructions build() {
            return new PaymentInstructions(
                object, livemode, id);
        }

    }
}
