/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import net.nova.api.utils.HasSecurity;
import net.nova.api.utils.SpeakeasyMetadata;
import net.nova.api.utils.Utils;


public class Security implements HasSecurity {

    @SpeakeasyMetadata("security:scheme=true,type=oauth2,name=Authorization")
    private String oAuth2;

    @JsonCreator
    public Security(
            @Nullable String oAuth2) {
        this.oAuth2 = oAuth2;
    }
    
    public Security() {
        this(null);
    }

    public Optional<String> oAuth2() {
        return Optional.ofNullable(this.oAuth2);
    }

    public static Builder builder() {
        return new Builder();
    }


    public Security withOAuth2(@Nullable String oAuth2) {
        this.oAuth2 = oAuth2;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Security other = (Security) o;
        return 
            Utils.enhancedDeepEquals(this.oAuth2, other.oAuth2);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            oAuth2);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Security.class,
                "oAuth2", oAuth2);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String oAuth2;

        private Builder() {
          // force use of static builder() method
        }

        public Builder oAuth2(@Nullable String oAuth2) {
            this.oAuth2 = oAuth2;
            return this;
        }

        public Security build() {
            return new Security(
                oAuth2);
        }

    }
}
