/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.databind.JsonNode;
import java.lang.Override;
import java.lang.String;
import net.nova.api.utils.UnknownType;


public class UnknownPaymentInstructionsInput extends UnknownType implements PaymentInstructionsInput {

    @JsonCreator
    public UnknownPaymentInstructionsInput(JsonNode rawNode) {
        super(rawNode);
    }

    @Override
    public String type() {
        return extractDiscriminator("type").orElse("UNKNOWN");
    }

}