/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import net.nova.api.utils.Utils;


public class WireAddress {
    /**
     * Street address line 1. Must not be a PO box.
     */
    @JsonProperty("street1")
    private String street1;

    /**
     * Street address line 2. Must not be a PO box.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("street2")
    private String street2;

    /**
     * City
     */
    @JsonProperty("city")
    private String city;

    /**
     * State or province. For US addresses must be exactly 2 chars.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("state")
    private String state;

    /**
     * Postal code. For US addresses, ZIP or ZIP+4.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("postal_code")
    private String postalCode;

    /**
     * ISO 3166-1 alpha-2 country code
     */
    @JsonProperty("country_code")
    private String countryCode;

    @JsonCreator
    public WireAddress(
            @JsonProperty("street1") @Nonnull String street1,
            @JsonProperty("street2") @Nullable String street2,
            @JsonProperty("city") @Nonnull String city,
            @JsonProperty("state") @Nullable String state,
            @JsonProperty("postal_code") @Nullable String postalCode,
            @JsonProperty("country_code") @Nonnull String countryCode) {
        this.street1 = Optional.ofNullable(street1)
            .orElseThrow(() -> new IllegalArgumentException("street1 cannot be null"));
        this.street2 = street2;
        this.city = Optional.ofNullable(city)
            .orElseThrow(() -> new IllegalArgumentException("city cannot be null"));
        this.state = state;
        this.postalCode = postalCode;
        this.countryCode = Optional.ofNullable(countryCode)
            .orElseThrow(() -> new IllegalArgumentException("countryCode cannot be null"));
    }
    
    public WireAddress(
            @Nonnull String street1,
            @Nonnull String city,
            @Nonnull String countryCode) {
        this(street1, null, city,
            null, null, countryCode);
    }

    /**
     * Street address line 1. Must not be a PO box.
     */
    public String street1() {
        return this.street1;
    }

    /**
     * Street address line 2. Must not be a PO box.
     */
    public Optional<String> street2() {
        return Optional.ofNullable(this.street2);
    }

    /**
     * City
     */
    public String city() {
        return this.city;
    }

    /**
     * State or province. For US addresses must be exactly 2 chars.
     */
    public Optional<String> state() {
        return Optional.ofNullable(this.state);
    }

    /**
     * Postal code. For US addresses, ZIP or ZIP+4.
     */
    public Optional<String> postalCode() {
        return Optional.ofNullable(this.postalCode);
    }

    /**
     * ISO 3166-1 alpha-2 country code
     */
    public String countryCode() {
        return this.countryCode;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Street address line 1. Must not be a PO box.
     */
    public WireAddress withStreet1(@Nonnull String street1) {
        this.street1 = Utils.checkNotNull(street1, "street1");
        return this;
    }


    /**
     * Street address line 2. Must not be a PO box.
     */
    public WireAddress withStreet2(@Nullable String street2) {
        this.street2 = street2;
        return this;
    }


    /**
     * City
     */
    public WireAddress withCity(@Nonnull String city) {
        this.city = Utils.checkNotNull(city, "city");
        return this;
    }


    /**
     * State or province. For US addresses must be exactly 2 chars.
     */
    public WireAddress withState(@Nullable String state) {
        this.state = state;
        return this;
    }


    /**
     * Postal code. For US addresses, ZIP or ZIP+4.
     */
    public WireAddress withPostalCode(@Nullable String postalCode) {
        this.postalCode = postalCode;
        return this;
    }


    /**
     * ISO 3166-1 alpha-2 country code
     */
    public WireAddress withCountryCode(@Nonnull String countryCode) {
        this.countryCode = Utils.checkNotNull(countryCode, "countryCode");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        WireAddress other = (WireAddress) o;
        return 
            Utils.enhancedDeepEquals(this.street1, other.street1) &&
            Utils.enhancedDeepEquals(this.street2, other.street2) &&
            Utils.enhancedDeepEquals(this.city, other.city) &&
            Utils.enhancedDeepEquals(this.state, other.state) &&
            Utils.enhancedDeepEquals(this.postalCode, other.postalCode) &&
            Utils.enhancedDeepEquals(this.countryCode, other.countryCode);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            street1, street2, city,
            state, postalCode, countryCode);
    }
    
    @Override
    public String toString() {
        return Utils.toString(WireAddress.class,
                "street1", street1,
                "street2", street2,
                "city", city,
                "state", state,
                "postalCode", postalCode,
                "countryCode", countryCode);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String street1;

        private String street2;

        private String city;

        private String state;

        private String postalCode;

        private String countryCode;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Street address line 1. Must not be a PO box.
         */
        public Builder street1(@Nonnull String street1) {
            this.street1 = Utils.checkNotNull(street1, "street1");
            return this;
        }

        /**
         * Street address line 2. Must not be a PO box.
         */
        public Builder street2(@Nullable String street2) {
            this.street2 = street2;
            return this;
        }

        /**
         * City
         */
        public Builder city(@Nonnull String city) {
            this.city = Utils.checkNotNull(city, "city");
            return this;
        }

        /**
         * State or province. For US addresses must be exactly 2 chars.
         */
        public Builder state(@Nullable String state) {
            this.state = state;
            return this;
        }

        /**
         * Postal code. For US addresses, ZIP or ZIP+4.
         */
        public Builder postalCode(@Nullable String postalCode) {
            this.postalCode = postalCode;
            return this;
        }

        /**
         * ISO 3166-1 alpha-2 country code
         */
        public Builder countryCode(@Nonnull String countryCode) {
            this.countryCode = Utils.checkNotNull(countryCode, "countryCode");
            return this;
        }

        public WireAddress build() {
            return new WireAddress(
                street1, street2, city,
                state, postalCode, countryCode);
        }

    }
}
