/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api;

import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import java.util.concurrent.TimeUnit;

import java.lang.IllegalStateException;
import java.util.Optional;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import net.nova.api.utils.BackoffStrategy;
import net.nova.api.utils.HTTPClient;
import net.nova.api.utils.RetryConfig;
import net.nova.api.utils.SpeakeasyHTTPClient;


/**
 * Spring Boot Auto Configuration for nova-java SDK
 * This configuration class automatically configures the nova-java SDK
 * when Spring Boot detects it on the classpath.
 */
@AutoConfiguration
@ConditionalOnClass(NovaSDK.class)
@EnableConfigurationProperties(NovaJavaAutoConfigProperties.class)
public class NovaJavaAutoConfig {

    /**
     * Constructor.
     */
    public NovaJavaAutoConfig() {
    }

    /**
     * Creates a RetryConfig bean from properties if retry is enabled.
     * 
     * @param properties the configuration properties
     * @return A configured RetryConfig instance
     */
    @Bean
    @ConditionalOnMissingBean
    @ConditionalOnProperty(prefix = "novajava.retry-config", name = "strategy")
    public RetryConfig retryConfig(NovaJavaAutoConfigProperties properties) {
        NovaJavaAutoConfigProperties.RetryConfig retryProps = properties.getRetryConfig();
        
        if (RetryConfig.Strategy.BACKOFF.equals(retryProps.getStrategy())) {
            NovaJavaAutoConfigProperties.RetryConfig.Backoff backoff = retryProps.getBackoff();
            return RetryConfig.builder()
                .backoff(
                    BackoffStrategy.builder()
                        .initialInterval(backoff.getInitialInterval().toMillis(), TimeUnit.MILLISECONDS)
                        .maxInterval(backoff.getMaxInterval().toMillis(), TimeUnit.MILLISECONDS)
                        .maxElapsedTime(backoff.getMaxElapsedTime().toMillis(), TimeUnit.MILLISECONDS)
                        .baseFactor(backoff.getBaseFactor())
                        .jitterFactor(backoff.getJitterFactor())
                        .retryConnectError(backoff.isRetryConnectError())
                        .retryReadTimeoutError(backoff.isRetryReadTimeoutError())
                        .build()
                )
                .build();
        }
        
        // Default retry config for other strategies
        return RetryConfig.builder().build();
    }
    /**
     * Creates an HTTPClient bean if none exists.
     *
     * @param properties the configuration properties
     * @return A configured HTTPClient instance
     */
    @Bean
    @ConditionalOnMissingBean
    public HTTPClient httpClient(NovaJavaAutoConfigProperties properties) {
        NovaJavaAutoConfigProperties.HttpClient httpClientProps = properties.getHttpClient();

        if (httpClientProps != null) {
            // Configure debug logging
            SpeakeasyHTTPClient.setDebugLogging(httpClientProps.isEnableDebugLogging());

            // Configure redacted headers
            if (httpClientProps.getRedactedHeaders() != null && !httpClientProps.getRedactedHeaders().isEmpty()) {
                SpeakeasyHTTPClient.setRedactedHeaders(httpClientProps.getRedactedHeaders());
            }
        }

        return new SpeakeasyHTTPClient();
    }
    /**
     * Creates a SecuritySource bean if none exists and security properties are configured.
     *
     * @param properties the configuration properties
     * @return A configured SecuritySource instance
     */
    @Bean
    @ConditionalOnMissingBean
    @ConditionalOnPropertyPrefix(prefix = "novajava.security")
    public SecuritySource securitySource(NovaJavaAutoConfigProperties properties) {NovaJavaAutoConfigProperties.Security securityProps = properties.getSecurity();
        net.nova.api.models.components.Security.Builder securityBuilder = net.nova.api.models.components.Security.builder();
        boolean hasAnySecurityConfiguration = false;
        // Build OAuth2 security from direct properties (primitive value)
        if (securityProps.getOAuth2() != null) {
            securityBuilder.oAuth2(securityProps.getOAuth2());
            hasAnySecurityConfiguration = true;
        }
        
        if (!hasAnySecurityConfiguration) {
            throw new IllegalStateException("Security configuration is present but no security options are configured. " +
                "Please configure at least one security option in your application properties.");
        }
        
        return SecuritySource.of(securityBuilder.build());
    }

    /**
     * Creates the SDKConfiguration bean as the single source of truth for all SDK configuration.
     *
     * @param properties the configuration properties
     * @param httpClient the HTTP client bean
     * @param hooks the hooks bean
     * @param asyncHooks the async hooks bean
     * @param securitySource the security source bean (optional)
     * @param retryConfig the retry config bean (optional)
     * @return A configured SDKConfiguration instance
     */
    @Bean
    @ConditionalOnMissingBean
    public SDKConfiguration sdkConfiguration(
            NovaJavaAutoConfigProperties properties,
            HTTPClient httpClient,
            net.nova.api.utils.Hooks hooks,
            net.nova.api.utils.AsyncHooks asyncHooks,
            SecuritySource securitySource,
            Optional<RetryConfig> retryConfig) {
        
        SDKConfiguration sdkConfiguration = new SDKConfiguration();
        
        sdkConfiguration.setClient(httpClient);
        
        sdkConfiguration.setHooks(hooks);
        sdkConfiguration.setAsyncHooks(asyncHooks);
        sdkConfiguration.setSecuritySource(securitySource);
        
        if (properties.getServerUrl() != null) {
            sdkConfiguration.setServerUrl(properties.getServerUrl());
        }
        sdkConfiguration.setServerIdx(properties.getServerIdx());
        
        sdkConfiguration.setRetryConfig(retryConfig);
        
        return sdkConfiguration;
    }

    /**
     * Creates the main SDK bean using the configured SDKConfiguration.
     *
     * @param sdkConfiguration the configured SDKConfiguration bean
     * @return A configured NovaSDK instance
     */
    @Bean
    @ConditionalOnMissingBean
    public NovaSDK novaSDK(SDKConfiguration sdkConfiguration) {
        return new NovaSDK(sdkConfiguration);
    }

    /**
     * Creates an AsyncHooks bean if none exists.
     * 
     * @return A configured AsyncHooks instance
     */
    @Bean
    @ConditionalOnMissingBean
    public net.nova.api.utils.AsyncHooks asyncHooks() {
        return new net.nova.api.utils.AsyncHooks();
    }

    /**
     * Creates a ScheduledExecutorService for async retry operations if none exists.
     * 
     * @return A configured ScheduledExecutorService instance
     */
    @Bean
    @ConditionalOnMissingBean
    public ScheduledExecutorService retryScheduler() {
        return Executors.newSingleThreadScheduledExecutor();
    }

    /**
     * Creates a Hooks configuration bean if none exists.
     *
     * @return A configured Hooks instance
     */
    @Bean
    @ConditionalOnMissingBean
    public net.nova.api.utils.Hooks hooks() {
        return new net.nova.api.utils.Hooks();
    }
    /**
     * Creates a Authentication sub-SDK bean if none exists.
     *
     * @param novaSDK the main SDK instance
     * @return A configured Authentication instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Authentication authentication(NovaSDK novaSDK) {
        return novaSDK.authentication();
    }
    /**
     * Creates a Distributions sub-SDK bean if none exists.
     *
     * @param novaSDK the main SDK instance
     * @return A configured Distributions instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Distributions distributions(NovaSDK novaSDK) {
        return novaSDK.distributions();
    }
    /**
     * Creates a PaymentInstructions sub-SDK bean if none exists.
     *
     * @param novaSDK the main SDK instance
     * @return A configured PaymentInstructions instance
     */
    @Bean
    @ConditionalOnMissingBean
    public PaymentInstructions paymentInstructions(NovaSDK novaSDK) {
        return novaSDK.paymentInstructions();
    }
    /**
     * Creates a Entities sub-SDK bean if none exists.
     *
     * @param novaSDK the main SDK instance
     * @return A configured Entities instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Entities entities(NovaSDK novaSDK) {
        return novaSDK.entities();
    }
    /**
     * Creates a Contacts sub-SDK bean if none exists.
     *
     * @param novaSDK the main SDK instance
     * @return A configured Contacts instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Contacts contacts(NovaSDK novaSDK) {
        return novaSDK.contacts();
    }

    /**
     * Creates the async SDK bean if none exists.
     *
     * @param novaSDK the main SDK instance
     * @param sdkConfiguration the configured SDKConfiguration bean
     * @return A configured AsyncNovaSDK instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncNovaSDK asyncNovaSDK(NovaSDK novaSDK, SDKConfiguration sdkConfiguration) {
        return new AsyncNovaSDK(novaSDK, sdkConfiguration);
    }
    /**
     * Creates an AsyncAuthentication sub-SDK bean if none exists.
     *
     * @param asyncNovaSDK the async SDK instance
     * @return A configured AsyncAuthentication instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncAuthentication asyncAuthentication(AsyncNovaSDK asyncNovaSDK) {
        return asyncNovaSDK.authentication();
    }
    /**
     * Creates an AsyncDistributions sub-SDK bean if none exists.
     *
     * @param asyncNovaSDK the async SDK instance
     * @return A configured AsyncDistributions instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncDistributions asyncDistributions(AsyncNovaSDK asyncNovaSDK) {
        return asyncNovaSDK.distributions();
    }
    /**
     * Creates an AsyncPaymentInstructions sub-SDK bean if none exists.
     *
     * @param asyncNovaSDK the async SDK instance
     * @return A configured AsyncPaymentInstructions instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncPaymentInstructions asyncPaymentInstructions(AsyncNovaSDK asyncNovaSDK) {
        return asyncNovaSDK.paymentInstructions();
    }
    /**
     * Creates an AsyncEntities sub-SDK bean if none exists.
     *
     * @param asyncNovaSDK the async SDK instance
     * @return A configured AsyncEntities instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncEntities asyncEntities(AsyncNovaSDK asyncNovaSDK) {
        return asyncNovaSDK.entities();
    }
    /**
     * Creates an AsyncContacts sub-SDK bean if none exists.
     *
     * @param asyncNovaSDK the async SDK instance
     * @return A configured AsyncContacts instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncContacts asyncContacts(AsyncNovaSDK asyncNovaSDK) {
        return asyncNovaSDK.contacts();
    }
}