workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
  nova-spec:
    registry:
      location: registry.speakeasyapi.dev/CHANGEME-workspace/nova/nova-spec
targets:
  nova-java:
    target: java
    source: nova-spec
