workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Nova API:
        registry:
            location: registry.speakeasyapi.dev/angellist/nova-sdk/nova-api
targets:
    nova-sdk:
        target: java
        source: Nova API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/angellist/nova-sdk/nova-api-java-code-samples
            labelOverride:
                fixedValue: Java (SDK)
            blocking: false
