/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.utils;

import net.nova.api.utils.Blob;

import java.net.http.HttpResponse;

public final class AsyncRetryableException extends Exception {
    private final HttpResponse<Blob> response;

    public AsyncRetryableException(HttpResponse<Blob> response) {
        this.response = response;
    }

    public HttpResponse<Blob> response() {
        return response;
    }
}
