/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package net.nova.api.utils;

/**
 * Implemented by classes that have security annotations on fields.
 **/
public interface HasSecurity {
}